// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001301Component } from './my.001301.component';
import { My001302Component } from './my.001302.component';
import { My001303Component } from './my.001303.component';
import { My001304Component } from './my.001304.component';
import { My001305Component } from './my.001305.component';
import { My001306Component } from './my.001306.component';

@NgModule({
  declarations: [
    My001301Component,
    My001302Component,
    My001303Component,
    My001304Component,
    My001305Component,
    My001306Component,
  ],
  imports: [CommonModule],
  exports: [
    My001301Component,
  ]
})
export class Module000216 { }
