// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001735',
  templateUrl: './my.001735.component.html'
})
export class My001735Component {
  @Input() parentName = '';
  myName = 'My001735Component';
}
