// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001741',
  templateUrl: './my.001741.component.html'
})
export class My001741Component {
  @Input() parentName = '';
  myName = 'My001741Component';
}
