// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001737',
  templateUrl: './my.001737.component.html'
})
export class My001737Component {
  @Input() parentName = '';
  myName = 'My001737Component';
}
