// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001738',
  templateUrl: './my.001738.component.html'
})
export class My001738Component {
  @Input() parentName = '';
  myName = 'My001738Component';
}
