// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001306',
  templateUrl: './my.001306.component.html'
})
export class My001306Component {
  @Input() parentName = '';
  myName = 'My001306Component';
}
