// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001736',
  templateUrl: './my.001736.component.html'
})
export class My001736Component {
  @Input() parentName = '';
  myName = 'My001736Component';
}
