// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001740',
  templateUrl: './my.001740.component.html'
})
export class My001740Component {
  @Input() parentName = '';
  myName = 'My001740Component';
}
