// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001023Component } from './my.001023.component';
import { My001024Component } from './my.001024.component';
import { My001025Component } from './my.001025.component';
import { My001026Component } from './my.001026.component';
import { My001027Component } from './my.001027.component';
import { My001028Component } from './my.001028.component';
import { My001029Component } from './my.001029.component';
import { My001030Component } from './my.001030.component';

@NgModule({
  declarations: [
    My001023Component,
    My001024Component,
    My001025Component,
    My001026Component,
    My001027Component,
    My001028Component,
    My001029Component,
    My001030Component,
  ],
  imports: [CommonModule],
  exports: [
    My001023Component,
  ]
})
export class Module000127 { }
