// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000867Component } from './my.000867.component';
import { My000868Component } from './my.000868.component';
import { My000869Component } from './my.000869.component';
import { My000870Component } from './my.000870.component';
import { My000871Component } from './my.000871.component';
import { My000872Component } from './my.000872.component';

@NgModule({
  declarations: [
    My000867Component,
    My000868Component,
    My000869Component,
    My000870Component,
    My000871Component,
    My000872Component,
  ],
  imports: [CommonModule],
  exports: [
    My000867Component,
  ]
})
export class Module000127 { }
