// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001711Component } from './my.001711.component';
import { My001712Component } from './my.001712.component';
import { My001713Component } from './my.001713.component';
import { My001714Component } from './my.001714.component';
import { My001715Component } from './my.001715.component';
import { My001716Component } from './my.001716.component';
import { My001717Component } from './my.001717.component';
import { My001718Component } from './my.001718.component';

@NgModule({
  declarations: [
    My001711Component,
    My001712Component,
    My001713Component,
    My001714Component,
    My001715Component,
    My001716Component,
    My001717Component,
    My001718Component,
  ],
  imports: [CommonModule],
  exports: [
    My001711Component,
  ]
})
export class Module000213 { }
