// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001716',
  templateUrl: './my.001716.component.html'
})
export class My001716Component {
  @Input() parentName = '';
  myName = 'My001716Component';
}
