// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001714',
  templateUrl: './my.001714.component.html'
})
export class My001714Component {
  @Input() parentName = '';
  myName = 'My001714Component';
}
