// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001713',
  templateUrl: './my.001713.component.html'
})
export class My001713Component {
  @Input() parentName = '';
  myName = 'My001713Component';
}
