// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001717',
  templateUrl: './my.001717.component.html'
})
export class My001717Component {
  @Input() parentName = '';
  myName = 'My001717Component';
}
