// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001715',
  templateUrl: './my.001715.component.html'
})
export class My001715Component {
  @Input() parentName = '';
  myName = 'My001715Component';
}
