// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001718',
  templateUrl: './my.001718.component.html'
})
export class My001718Component {
  @Input() parentName = '';
  myName = 'My001718Component';
}
