// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001284',
  templateUrl: './my.001284.component.html'
})
export class My001284Component {
  @Input() parentName = '';
  myName = 'My001284Component';
}
