// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001712',
  templateUrl: './my.001712.component.html'
})
export class My001712Component {
  @Input() parentName = '';
  myName = 'My001712Component';
}
