// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001287',
  templateUrl: './my.001287.component.html'
})
export class My001287Component {
  @Input() parentName = '';
  myName = 'My001287Component';
}
