// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001286',
  templateUrl: './my.001286.component.html'
})
export class My001286Component {
  @Input() parentName = '';
  myName = 'My001286Component';
}
