// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001748',
  templateUrl: './my.001748.component.html'
})
export class My001748Component {
  @Input() parentName = '';
  myName = 'My001748Component';
}
