// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001749',
  templateUrl: './my.001749.component.html'
})
export class My001749Component {
  @Input() parentName = '';
  myName = 'My001749Component';
}
