// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001308',
  templateUrl: './my.001308.component.html'
})
export class My001308Component {
  @Input() parentName = '';
  myName = 'My001308Component';
}
