// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001747',
  templateUrl: './my.001747.component.html'
})
export class My001747Component {
  @Input() parentName = '';
  myName = 'My001747Component';
}
