// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001744',
  templateUrl: './my.001744.component.html'
})
export class My001744Component {
  @Input() parentName = '';
  myName = 'My001744Component';
}
