// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001310',
  templateUrl: './my.001310.component.html'
})
export class My001310Component {
  @Input() parentName = '';
  myName = 'My001310Component';
}
