// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001750',
  templateUrl: './my.001750.component.html'
})
export class My001750Component {
  @Input() parentName = '';
  myName = 'My001750Component';
}
