// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000933Component } from './my.000933.component';
import { My000934Component } from './my.000934.component';
import { My000935Component } from './my.000935.component';
import { My000936Component } from './my.000936.component';
import { My000937Component } from './my.000937.component';
import { My000938Component } from './my.000938.component';

@NgModule({
  declarations: [
    My000933Component,
    My000934Component,
    My000935Component,
    My000936Component,
    My000937Component,
    My000938Component,
  ],
  imports: [CommonModule],
  exports: [
    My000933Component,
  ]
})
export class Module000138 { }
