// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000838',
  templateUrl: './my.000838.component.html'
})
export class My000838Component {
  @Input() parentName = '';
  myName = 'My000838Component';
}
