// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000834',
  templateUrl: './my.000834.component.html'
})
export class My000834Component {
  @Input() parentName = '';
  myName = 'My000834Component';
}
