// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000668',
  templateUrl: './my.000668.component.html'
})
export class My000668Component {
  @Input() parentName = '';
  myName = 'My000668Component';
}
