// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001551Component } from './my.001551.component';
import { My001552Component } from './my.001552.component';
import { My001553Component } from './my.001553.component';
import { My001554Component } from './my.001554.component';
import { My001555Component } from './my.001555.component';
import { My001556Component } from './my.001556.component';
import { My001557Component } from './my.001557.component';
import { My001558Component } from './my.001558.component';

@NgModule({
  declarations: [
    My001551Component,
    My001552Component,
    My001553Component,
    My001554Component,
    My001555Component,
    My001556Component,
    My001557Component,
    My001558Component,
  ],
  imports: [CommonModule],
  exports: [
    My001551Component,
  ]
})
export class Module000193 { }
