// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001163Component } from './my.001163.component';
import { My001164Component } from './my.001164.component';
import { My001165Component } from './my.001165.component';
import { My001166Component } from './my.001166.component';
import { My001167Component } from './my.001167.component';
import { My001168Component } from './my.001168.component';

@NgModule({
  declarations: [
    My001163Component,
    My001164Component,
    My001165Component,
    My001166Component,
    My001167Component,
    My001168Component,
  ],
  imports: [CommonModule],
  exports: [
    My001163Component,
  ]
})
export class Module000193 { }
