// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001557',
  templateUrl: './my.001557.component.html'
})
export class My001557Component {
  @Input() parentName = '';
  myName = 'My001557Component';
}
