// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001554',
  templateUrl: './my.001554.component.html'
})
export class My001554Component {
  @Input() parentName = '';
  myName = 'My001554Component';
}
