// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001551',
  templateUrl: './my.001551.component.html'
})
export class My001551Component {
  @Input() parentName = '';
  myName = 'My001551Component';
}
