// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001555',
  templateUrl: './my.001555.component.html'
})
export class My001555Component {
  @Input() parentName = '';
  myName = 'My001555Component';
}
