// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001556',
  templateUrl: './my.001556.component.html'
})
export class My001556Component {
  @Input() parentName = '';
  myName = 'My001556Component';
}
