// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001595',
  templateUrl: './my.001595.component.html'
})
export class My001595Component {
  @Input() parentName = '';
  myName = 'My001595Component';
}
