// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001591',
  templateUrl: './my.001591.component.html'
})
export class My001591Component {
  @Input() parentName = '';
  myName = 'My001591Component';
}
