// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001596',
  templateUrl: './my.001596.component.html'
})
export class My001596Component {
  @Input() parentName = '';
  myName = 'My001596Component';
}
