// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001594',
  templateUrl: './my.001594.component.html'
})
export class My001594Component {
  @Input() parentName = '';
  myName = 'My001594Component';
}
