// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001598',
  templateUrl: './my.001598.component.html'
})
export class My001598Component {
  @Input() parentName = '';
  myName = 'My001598Component';
}
