// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000525Component } from './my.000525.component';
import { My000526Component } from './my.000526.component';
import { My000527Component } from './my.000527.component';
import { My000528Component } from './my.000528.component';
import { My000529Component } from './my.000529.component';
import { My000530Component } from './my.000530.component';
import { My000531Component } from './my.000531.component';

@NgModule({
  declarations: [
    My000525Component,
    My000526Component,
    My000527Component,
    My000528Component,
    My000529Component,
    My000530Component,
    My000531Component,
  ],
  imports: [CommonModule],
  exports: [
    My000525Component,
  ]
})
export class Module000075 { }
