// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000530',
  templateUrl: './my.000530.component.html'
})
export class My000530Component {
  @Input() parentName = '';
  myName = 'My000530Component';
}
