// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000550',
  templateUrl: './my.000550.component.html'
})
export class My000550Component {
  @Input() parentName = '';
  myName = 'My000550Component';
}
