// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000407',
  templateUrl: './my.000407.component.html'
})
export class My000407Component {
  @Input() parentName = '';
  myName = 'My000407Component';
}
