// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000041Component } from './my.000041.component';
import { My000042Component } from './my.000042.component';
import { My000043Component } from './my.000043.component';
import { My000044Component } from './my.000044.component';
import { My000045Component } from './my.000045.component';
import { My000046Component } from './my.000046.component';

@NgModule({
  declarations: [
    My000041Component,
    My000042Component,
    My000043Component,
    My000044Component,
    My000045Component,
    My000046Component,
  ],
  imports: [CommonModule],
  exports: [
    My000041Component,
  ]
})
export class Module000006 { }
