// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000147Component } from './my.000147.component';
import { My000148Component } from './my.000148.component';
import { My000149Component } from './my.000149.component';
import { My000150Component } from './my.000150.component';
import { My000151Component } from './my.000151.component';
import { My000152Component } from './my.000152.component';
import { My000153Component } from './my.000153.component';

@NgModule({
  declarations: [
    My000147Component,
    My000148Component,
    My000149Component,
    My000150Component,
    My000151Component,
    My000152Component,
    My000153Component,
  ],
  imports: [CommonModule],
  exports: [
    My000147Component,
  ]
})
export class Module000021 { }
