// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000175',
  templateUrl: './my.000175.component.html'
})
export class My000175Component {
  @Input() parentName = '';
  myName = 'My000175Component';
}
