// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000177',
  templateUrl: './my.000177.component.html'
})
export class My000177Component {
  @Input() parentName = '';
  myName = 'My000177Component';
}
