// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000134',
  templateUrl: './my.000134.component.html'
})
export class My000134Component {
  @Input() parentName = '';
  myName = 'My000134Component';
}
