// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000133',
  templateUrl: './my.000133.component.html'
})
export class My000133Component {
  @Input() parentName = '';
  myName = 'My000133Component';
}
