// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000148',
  templateUrl: './my.000148.component.html'
})
export class My000148Component {
  @Input() parentName = '';
  myName = 'My000148Component';
}
