// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000419Component } from './my.000419.component';
import { My000420Component } from './my.000420.component';
import { My000421Component } from './my.000421.component';
import { My000422Component } from './my.000422.component';
import { My000423Component } from './my.000423.component';
import { My000424Component } from './my.000424.component';

@NgModule({
  declarations: [
    My000419Component,
    My000420Component,
    My000421Component,
    My000422Component,
    My000423Component,
    My000424Component,
  ],
  imports: [CommonModule],
  exports: [
    My000419Component,
  ]
})
export class Module000069 { }
