// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000863Component } from './my.000863.component';
import { My000864Component } from './my.000864.component';
import { My000865Component } from './my.000865.component';
import { My000866Component } from './my.000866.component';
import { My000867Component } from './my.000867.component';
import { My000868Component } from './my.000868.component';

@NgModule({
  declarations: [
    My000863Component,
    My000864Component,
    My000865Component,
    My000866Component,
    My000867Component,
    My000868Component,
  ],
  imports: [CommonModule],
  exports: [
    My000863Component,
  ]
})
export class Module000143 { }
