// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000707Component } from './my.000707.component';
import { My000708Component } from './my.000708.component';
import { My000709Component } from './my.000709.component';
import { My000710Component } from './my.000710.component';
import { My000711Component } from './my.000711.component';
import { My000712Component } from './my.000712.component';

@NgModule({
  declarations: [
    My000707Component,
    My000708Component,
    My000709Component,
    My000710Component,
    My000711Component,
    My000712Component,
  ],
  imports: [CommonModule],
  exports: [
    My000707Component,
  ]
})
export class Module000117 { }
