// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000689Component } from './my.000689.component';
import { My000690Component } from './my.000690.component';
import { My000691Component } from './my.000691.component';
import { My000692Component } from './my.000692.component';
import { My000693Component } from './my.000693.component';
import { My000694Component } from './my.000694.component';

@NgModule({
  declarations: [
    My000689Component,
    My000690Component,
    My000691Component,
    My000692Component,
    My000693Component,
    My000694Component,
  ],
  imports: [CommonModule],
  exports: [
    My000689Component,
  ]
})
export class Module000114 { }
