// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000693',
  templateUrl: './my.000693.component.html'
})
export class My000693Component {
  @Input() parentName = '';
  myName = 'My000693Component';
}
