// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000629Component } from './my.000629.component';
import { My000630Component } from './my.000630.component';
import { My000631Component } from './my.000631.component';
import { My000632Component } from './my.000632.component';
import { My000633Component } from './my.000633.component';
import { My000634Component } from './my.000634.component';

@NgModule({
  declarations: [
    My000629Component,
    My000630Component,
    My000631Component,
    My000632Component,
    My000633Component,
    My000634Component,
  ],
  imports: [CommonModule],
  exports: [
    My000629Component,
  ]
})
export class Module000104 { }
