// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000728Component } from './my.000728.component';
import { My000729Component } from './my.000729.component';
import { My000730Component } from './my.000730.component';
import { My000731Component } from './my.000731.component';
import { My000732Component } from './my.000732.component';
import { My000733Component } from './my.000733.component';
import { My000734Component } from './my.000734.component';

@NgModule({
  declarations: [
    My000728Component,
    My000729Component,
    My000730Component,
    My000731Component,
    My000732Component,
    My000733Component,
    My000734Component,
  ],
  imports: [CommonModule],
  exports: [
    My000728Component,
  ]
})
export class Module000104 { }
