// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000841',
  templateUrl: './my.000841.component.html'
})
export class My000841Component {
  @Input() parentName = '';
  myName = 'My000841Component';
}
