// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001367Component } from './my.001367.component';
import { My001368Component } from './my.001368.component';
import { My001369Component } from './my.001369.component';
import { My001370Component } from './my.001370.component';
import { My001371Component } from './my.001371.component';
import { My001372Component } from './my.001372.component';

@NgModule({
  declarations: [
    My001367Component,
    My001368Component,
    My001369Component,
    My001370Component,
    My001371Component,
    My001372Component,
  ],
  imports: [CommonModule],
  exports: [
    My001367Component,
  ]
})
export class Module000227 { }
