// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001367',
  templateUrl: './my.001367.component.html'
})
export class My001367Component {
  @Input() parentName = '';
  myName = 'My001367Component';
}
