// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001825',
  templateUrl: './my.001825.component.html'
})
export class My001825Component {
  @Input() parentName = '';
  myName = 'My001825Component';
}
