// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001370',
  templateUrl: './my.001370.component.html'
})
export class My001370Component {
  @Input() parentName = '';
  myName = 'My001370Component';
}
