// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001824',
  templateUrl: './my.001824.component.html'
})
export class My001824Component {
  @Input() parentName = '';
  myName = 'My001824Component';
}
