// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001830',
  templateUrl: './my.001830.component.html'
})
export class My001830Component {
  @Input() parentName = '';
  myName = 'My001830Component';
}
