// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001827',
  templateUrl: './my.001827.component.html'
})
export class My001827Component {
  @Input() parentName = '';
  myName = 'My001827Component';
}
