// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001828',
  templateUrl: './my.001828.component.html'
})
export class My001828Component {
  @Input() parentName = '';
  myName = 'My001828Component';
}
