// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001369',
  templateUrl: './my.001369.component.html'
})
export class My001369Component {
  @Input() parentName = '';
  myName = 'My001369Component';
}
