// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001282',
  templateUrl: './my.001282.component.html'
})
export class My001282Component {
  @Input() parentName = '';
  myName = 'My001282Component';
}
