// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001703',
  templateUrl: './my.001703.component.html'
})
export class My001703Component {
  @Input() parentName = '';
  myName = 'My001703Component';
}
