// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001710',
  templateUrl: './my.001710.component.html'
})
export class My001710Component {
  @Input() parentName = '';
  myName = 'My001710Component';
}
