// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001281',
  templateUrl: './my.001281.component.html'
})
export class My001281Component {
  @Input() parentName = '';
  myName = 'My001281Component';
}
