// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001708',
  templateUrl: './my.001708.component.html'
})
export class My001708Component {
  @Input() parentName = '';
  myName = 'My001708Component';
}
