// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000591Component } from './my.000591.component';
import { My000592Component } from './my.000592.component';
import { My000593Component } from './my.000593.component';
import { My000594Component } from './my.000594.component';
import { My000595Component } from './my.000595.component';
import { My000596Component } from './my.000596.component';
import { My000597Component } from './my.000597.component';
import { My000598Component } from './my.000598.component';

@NgModule({
  declarations: [
    My000591Component,
    My000592Component,
    My000593Component,
    My000594Component,
    My000595Component,
    My000596Component,
    My000597Component,
    My000598Component,
  ],
  imports: [CommonModule],
  exports: [
    My000591Component,
  ]
})
export class Module000073 { }
