// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000915Component } from './my.000915.component';
import { My000916Component } from './my.000916.component';
import { My000917Component } from './my.000917.component';
import { My000918Component } from './my.000918.component';
import { My000919Component } from './my.000919.component';
import { My000920Component } from './my.000920.component';

@NgModule({
  declarations: [
    My000915Component,
    My000916Component,
    My000917Component,
    My000918Component,
    My000919Component,
    My000920Component,
  ],
  imports: [CommonModule],
  exports: [
    My000915Component,
  ]
})
export class Module000135 { }
