// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001039Component } from './my.001039.component';
import { My001040Component } from './my.001040.component';
import { My001041Component } from './my.001041.component';
import { My001042Component } from './my.001042.component';
import { My001043Component } from './my.001043.component';
import { My001044Component } from './my.001044.component';
import { My001045Component } from './my.001045.component';
import { My001046Component } from './my.001046.component';

@NgModule({
  declarations: [
    My001039Component,
    My001040Component,
    My001041Component,
    My001042Component,
    My001043Component,
    My001044Component,
    My001045Component,
    My001046Component,
  ],
  imports: [CommonModule],
  exports: [
    My001039Component,
  ]
})
export class Module000129 { }
