// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000879Component } from './my.000879.component';
import { My000880Component } from './my.000880.component';
import { My000881Component } from './my.000881.component';
import { My000882Component } from './my.000882.component';
import { My000883Component } from './my.000883.component';
import { My000884Component } from './my.000884.component';

@NgModule({
  declarations: [
    My000879Component,
    My000880Component,
    My000881Component,
    My000882Component,
    My000883Component,
    My000884Component,
  ],
  imports: [CommonModule],
  exports: [
    My000879Component,
  ]
})
export class Module000129 { }
