// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000315Component } from './my.000315.component';
import { My000316Component } from './my.000316.component';
import { My000317Component } from './my.000317.component';
import { My000318Component } from './my.000318.component';
import { My000319Component } from './my.000319.component';
import { My000320Component } from './my.000320.component';
import { My000321Component } from './my.000321.component';

@NgModule({
  declarations: [
    My000315Component,
    My000316Component,
    My000317Component,
    My000318Component,
    My000319Component,
    My000320Component,
    My000321Component,
  ],
  imports: [CommonModule],
  exports: [
    My000315Component,
  ]
})
export class Module000045 { }
