// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000367Component } from './my.000367.component';
import { My000368Component } from './my.000368.component';
import { My000369Component } from './my.000369.component';
import { My000370Component } from './my.000370.component';
import { My000371Component } from './my.000371.component';
import { My000372Component } from './my.000372.component';
import { My000373Component } from './my.000373.component';
import { My000374Component } from './my.000374.component';

@NgModule({
  declarations: [
    My000367Component,
    My000368Component,
    My000369Component,
    My000370Component,
    My000371Component,
    My000372Component,
    My000373Component,
    My000374Component,
  ],
  imports: [CommonModule],
  exports: [
    My000367Component,
  ]
})
export class Module000045 { }
