// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000275',
  templateUrl: './my.000275.component.html'
})
export class My000275Component {
  @Input() parentName = '';
  myName = 'My000275Component';
}
