// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001335',
  templateUrl: './my.001335.component.html'
})
export class My001335Component {
  @Input() parentName = '';
  myName = 'My001335Component';
}
