// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001779',
  templateUrl: './my.001779.component.html'
})
export class My001779Component {
  @Input() parentName = '';
  myName = 'My001779Component';
}
