// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001780',
  templateUrl: './my.001780.component.html'
})
export class My001780Component {
  @Input() parentName = '';
  myName = 'My001780Component';
}
