// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001776',
  templateUrl: './my.001776.component.html'
})
export class My001776Component {
  @Input() parentName = '';
  myName = 'My001776Component';
}
