// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001775',
  templateUrl: './my.001775.component.html'
})
export class My001775Component {
  @Input() parentName = '';
  myName = 'My001775Component';
}
