// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001781',
  templateUrl: './my.001781.component.html'
})
export class My001781Component {
  @Input() parentName = '';
  myName = 'My001781Component';
}
