// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000917Component } from './my.000917.component';
import { My000918Component } from './my.000918.component';
import { My000919Component } from './my.000919.component';
import { My000920Component } from './my.000920.component';
import { My000921Component } from './my.000921.component';
import { My000922Component } from './my.000922.component';

@NgModule({
  declarations: [
    My000917Component,
    My000918Component,
    My000919Component,
    My000920Component,
    My000921Component,
    My000922Component,
  ],
  imports: [CommonModule],
  exports: [
    My000917Component,
  ]
})
export class Module000152 { }
