// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001223',
  templateUrl: './my.001223.component.html'
})
export class My001223Component {
  @Input() parentName = '';
  myName = 'My001223Component';
}
