// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001230',
  templateUrl: './my.001230.component.html'
})
export class My001230Component {
  @Input() parentName = '';
  myName = 'My001230Component';
}
