// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001599Component } from './my.001599.component';
import { My001600Component } from './my.001600.component';
import { My001601Component } from './my.001601.component';
import { My001602Component } from './my.001602.component';
import { My001603Component } from './my.001603.component';
import { My001604Component } from './my.001604.component';
import { My001605Component } from './my.001605.component';
import { My001606Component } from './my.001606.component';

@NgModule({
  declarations: [
    My001599Component,
    My001600Component,
    My001601Component,
    My001602Component,
    My001603Component,
    My001604Component,
    My001605Component,
    My001606Component,
  ],
  imports: [CommonModule],
  exports: [
    My001599Component,
  ]
})
export class Module000199 { }
