// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001200',
  templateUrl: './my.001200.component.html'
})
export class My001200Component {
  @Input() parentName = '';
  myName = 'My001200Component';
}
