// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001201',
  templateUrl: './my.001201.component.html'
})
export class My001201Component {
  @Input() parentName = '';
  myName = 'My001201Component';
}
