// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001599',
  templateUrl: './my.001599.component.html'
})
export class My001599Component {
  @Input() parentName = '';
  myName = 'My001599Component';
}
