// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001600',
  templateUrl: './my.001600.component.html'
})
export class My001600Component {
  @Input() parentName = '';
  myName = 'My001600Component';
}
