// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001606',
  templateUrl: './my.001606.component.html'
})
export class My001606Component {
  @Input() parentName = '';
  myName = 'My001606Component';
}
