// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001604',
  templateUrl: './my.001604.component.html'
})
export class My001604Component {
  @Input() parentName = '';
  myName = 'My001604Component';
}
