// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000647Component } from './my.000647.component';
import { My000648Component } from './my.000648.component';
import { My000649Component } from './my.000649.component';
import { My000650Component } from './my.000650.component';
import { My000651Component } from './my.000651.component';
import { My000652Component } from './my.000652.component';

@NgModule({
  declarations: [
    My000647Component,
    My000648Component,
    My000649Component,
    My000650Component,
    My000651Component,
    My000652Component,
  ],
  imports: [CommonModule],
  exports: [
    My000647Component,
  ]
})
export class Module000107 { }
