// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000747Component } from './my.000747.component';
import { My000748Component } from './my.000748.component';
import { My000749Component } from './my.000749.component';
import { My000750Component } from './my.000750.component';
import { My000751Component } from './my.000751.component';
import { My000752Component } from './my.000752.component';

@NgModule({
  declarations: [
    My000747Component,
    My000748Component,
    My000749Component,
    My000750Component,
    My000751Component,
    My000752Component,
  ],
  imports: [CommonModule],
  exports: [
    My000747Component,
  ]
})
export class Module000107 { }
