// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000647',
  templateUrl: './my.000647.component.html'
})
export class My000647Component {
  @Input() parentName = '';
  myName = 'My000647Component';
}
