// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001423Component } from './my.001423.component';
import { My001424Component } from './my.001424.component';
import { My001425Component } from './my.001425.component';
import { My001426Component } from './my.001426.component';
import { My001427Component } from './my.001427.component';
import { My001428Component } from './my.001428.component';
import { My001429Component } from './my.001429.component';
import { My001430Component } from './my.001430.component';

@NgModule({
  declarations: [
    My001423Component,
    My001424Component,
    My001425Component,
    My001426Component,
    My001427Component,
    My001428Component,
    My001429Component,
    My001430Component,
  ],
  imports: [CommonModule],
  exports: [
    My001423Component,
  ]
})
export class Module000177 { }
