// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001424',
  templateUrl: './my.001424.component.html'
})
export class My001424Component {
  @Input() parentName = '';
  myName = 'My001424Component';
}
