// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001069',
  templateUrl: './my.001069.component.html'
})
export class My001069Component {
  @Input() parentName = '';
  myName = 'My001069Component';
}
