// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001428',
  templateUrl: './my.001428.component.html'
})
export class My001428Component {
  @Input() parentName = '';
  myName = 'My001428Component';
}
