// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001430',
  templateUrl: './my.001430.component.html'
})
export class My001430Component {
  @Input() parentName = '';
  myName = 'My001430Component';
}
