// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001435',
  templateUrl: './my.001435.component.html'
})
export class My001435Component {
  @Input() parentName = '';
  myName = 'My001435Component';
}
