// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001076',
  templateUrl: './my.001076.component.html'
})
export class My001076Component {
  @Input() parentName = '';
  myName = 'My001076Component';
}
