// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000977Component } from './my.000977.component';
import { My000978Component } from './my.000978.component';
import { My000979Component } from './my.000979.component';
import { My000980Component } from './my.000980.component';
import { My000981Component } from './my.000981.component';
import { My000982Component } from './my.000982.component';

@NgModule({
  declarations: [
    My000977Component,
    My000978Component,
    My000979Component,
    My000980Component,
    My000981Component,
    My000982Component,
  ],
  imports: [CommonModule],
  exports: [
    My000977Component,
  ]
})
export class Module000162 { }
