// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001303Component } from './my.001303.component';
import { My001304Component } from './my.001304.component';
import { My001305Component } from './my.001305.component';
import { My001306Component } from './my.001306.component';
import { My001307Component } from './my.001307.component';
import { My001308Component } from './my.001308.component';
import { My001309Component } from './my.001309.component';
import { My001310Component } from './my.001310.component';

@NgModule({
  declarations: [
    My001303Component,
    My001304Component,
    My001305Component,
    My001306Component,
    My001307Component,
    My001308Component,
    My001309Component,
    My001310Component,
  ],
  imports: [CommonModule],
  exports: [
    My001303Component,
  ]
})
export class Module000162 { }
