// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001305',
  templateUrl: './my.001305.component.html'
})
export class My001305Component {
  @Input() parentName = '';
  myName = 'My001305Component';
}
