// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001309',
  templateUrl: './my.001309.component.html'
})
export class My001309Component {
  @Input() parentName = '';
  myName = 'My001309Component';
}
