// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001304',
  templateUrl: './my.001304.component.html'
})
export class My001304Component {
  @Input() parentName = '';
  myName = 'My001304Component';
}
