// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001303',
  templateUrl: './my.001303.component.html'
})
export class My001303Component {
  @Input() parentName = '';
  myName = 'My001303Component';
}
