// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000251Component } from './my.000251.component';
import { My000252Component } from './my.000252.component';
import { My000253Component } from './my.000253.component';
import { My000254Component } from './my.000254.component';
import { My000255Component } from './my.000255.component';
import { My000256Component } from './my.000256.component';

@NgModule({
  declarations: [
    My000251Component,
    My000252Component,
    My000253Component,
    My000254Component,
    My000255Component,
    My000256Component,
  ],
  imports: [CommonModule],
  exports: [
    My000251Component,
  ]
})
export class Module000041 { }
