// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000335Component } from './my.000335.component';
import { My000336Component } from './my.000336.component';
import { My000337Component } from './my.000337.component';
import { My000338Component } from './my.000338.component';
import { My000339Component } from './my.000339.component';
import { My000340Component } from './my.000340.component';
import { My000341Component } from './my.000341.component';
import { My000342Component } from './my.000342.component';

@NgModule({
  declarations: [
    My000335Component,
    My000336Component,
    My000337Component,
    My000338Component,
    My000339Component,
    My000340Component,
    My000341Component,
    My000342Component,
  ],
  imports: [CommonModule],
  exports: [
    My000335Component,
  ]
})
export class Module000041 { }
