// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001847Component } from './my.001847.component';
import { My001848Component } from './my.001848.component';
import { My001849Component } from './my.001849.component';
import { My001850Component } from './my.001850.component';
import { My001851Component } from './my.001851.component';
import { My001852Component } from './my.001852.component';
import { My001853Component } from './my.001853.component';
import { My001854Component } from './my.001854.component';

@NgModule({
  declarations: [
    My001847Component,
    My001848Component,
    My001849Component,
    My001850Component,
    My001851Component,
    My001852Component,
    My001853Component,
    My001854Component,
  ],
  imports: [CommonModule],
  exports: [
    My001847Component,
  ]
})
export class Module000230 { }
