// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001848',
  templateUrl: './my.001848.component.html'
})
export class My001848Component {
  @Input() parentName = '';
  myName = 'My001848Component';
}
