// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001853',
  templateUrl: './my.001853.component.html'
})
export class My001853Component {
  @Input() parentName = '';
  myName = 'My001853Component';
}
