// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001387',
  templateUrl: './my.001387.component.html'
})
export class My001387Component {
  @Input() parentName = '';
  myName = 'My001387Component';
}
