// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001849',
  templateUrl: './my.001849.component.html'
})
export class My001849Component {
  @Input() parentName = '';
  myName = 'My001849Component';
}
