// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001854',
  templateUrl: './my.001854.component.html'
})
export class My001854Component {
  @Input() parentName = '';
  myName = 'My001854Component';
}
