// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000179Component } from './my.000179.component';
import { My000180Component } from './my.000180.component';
import { My000181Component } from './my.000181.component';
import { My000182Component } from './my.000182.component';
import { My000183Component } from './my.000183.component';
import { My000184Component } from './my.000184.component';

@NgModule({
  declarations: [
    My000179Component,
    My000180Component,
    My000181Component,
    My000182Component,
    My000183Component,
    My000184Component,
  ],
  imports: [CommonModule],
  exports: [
    My000179Component,
  ]
})
export class Module000029 { }
