// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001133Component } from './my.001133.component';
import { My001134Component } from './my.001134.component';
import { My001135Component } from './my.001135.component';
import { My001136Component } from './my.001136.component';
import { My001137Component } from './my.001137.component';
import { My001138Component } from './my.001138.component';

@NgModule({
  declarations: [
    My001133Component,
    My001134Component,
    My001135Component,
    My001136Component,
    My001137Component,
    My001138Component,
  ],
  imports: [CommonModule],
  exports: [
    My001133Component,
  ]
})
export class Module000188 { }
