// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001513',
  templateUrl: './my.001513.component.html'
})
export class My001513Component {
  @Input() parentName = '';
  myName = 'My001513Component';
}
