// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001516',
  templateUrl: './my.001516.component.html'
})
export class My001516Component {
  @Input() parentName = '';
  myName = 'My001516Component';
}
