// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001514',
  templateUrl: './my.001514.component.html'
})
export class My001514Component {
  @Input() parentName = '';
  myName = 'My001514Component';
}
