// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001518',
  templateUrl: './my.001518.component.html'
})
export class My001518Component {
  @Input() parentName = '';
  myName = 'My001518Component';
}
