// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001515',
  templateUrl: './my.001515.component.html'
})
export class My001515Component {
  @Input() parentName = '';
  myName = 'My001515Component';
}
