// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001512',
  templateUrl: './my.001512.component.html'
})
export class My001512Component {
  @Input() parentName = '';
  myName = 'My001512Component';
}
