// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000821Component } from './my.000821.component';
import { My000822Component } from './my.000822.component';
import { My000823Component } from './my.000823.component';
import { My000824Component } from './my.000824.component';
import { My000825Component } from './my.000825.component';
import { My000826Component } from './my.000826.component';

@NgModule({
  declarations: [
    My000821Component,
    My000822Component,
    My000823Component,
    My000824Component,
    My000825Component,
    My000826Component,
  ],
  imports: [CommonModule],
  exports: [
    My000821Component,
  ]
})
export class Module000136 { }
