// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000921Component } from './my.000921.component';
import { My000922Component } from './my.000922.component';
import { My000923Component } from './my.000923.component';
import { My000924Component } from './my.000924.component';
import { My000925Component } from './my.000925.component';
import { My000926Component } from './my.000926.component';

@NgModule({
  declarations: [
    My000921Component,
    My000922Component,
    My000923Component,
    My000924Component,
    My000925Component,
    My000926Component,
  ],
  imports: [CommonModule],
  exports: [
    My000921Component,
  ]
})
export class Module000136 { }
