// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001101',
  templateUrl: './my.001101.component.html'
})
export class My001101Component {
  @Input() parentName = '';
  myName = 'My001101Component';
}
