// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000823',
  templateUrl: './my.000823.component.html'
})
export class My000823Component {
  @Input() parentName = '';
  myName = 'My000823Component';
}
