// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000677Component } from './my.000677.component';
import { My000678Component } from './my.000678.component';
import { My000679Component } from './my.000679.component';
import { My000680Component } from './my.000680.component';
import { My000681Component } from './my.000681.component';
import { My000682Component } from './my.000682.component';

@NgModule({
  declarations: [
    My000677Component,
    My000678Component,
    My000679Component,
    My000680Component,
    My000681Component,
    My000682Component,
  ],
  imports: [CommonModule],
  exports: [
    My000677Component,
  ]
})
export class Module000112 { }
