// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000781',
  templateUrl: './my.000781.component.html'
})
export class My000781Component {
  @Input() parentName = '';
  myName = 'My000781Component';
}
