// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000782',
  templateUrl: './my.000782.component.html'
})
export class My000782Component {
  @Input() parentName = '';
  myName = 'My000782Component';
}
