// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000677',
  templateUrl: './my.000677.component.html'
})
export class My000677Component {
  @Input() parentName = '';
  myName = 'My000677Component';
}
