// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000365Component } from './my.000365.component';
import { My000366Component } from './my.000366.component';
import { My000367Component } from './my.000367.component';
import { My000368Component } from './my.000368.component';
import { My000369Component } from './my.000369.component';
import { My000370Component } from './my.000370.component';

@NgModule({
  declarations: [
    My000365Component,
    My000366Component,
    My000367Component,
    My000368Component,
    My000369Component,
    My000370Component,
  ],
  imports: [CommonModule],
  exports: [
    My000365Component,
  ]
})
export class Module000060 { }
