// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000420Component } from './my.000420.component';
import { My000421Component } from './my.000421.component';
import { My000422Component } from './my.000422.component';
import { My000423Component } from './my.000423.component';
import { My000424Component } from './my.000424.component';
import { My000425Component } from './my.000425.component';
import { My000426Component } from './my.000426.component';

@NgModule({
  declarations: [
    My000420Component,
    My000421Component,
    My000422Component,
    My000423Component,
    My000424Component,
    My000425Component,
    My000426Component,
  ],
  imports: [CommonModule],
  exports: [
    My000420Component,
  ]
})
export class Module000060 { }
