// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000420',
  templateUrl: './my.000420.component.html'
})
export class My000420Component {
  @Input() parentName = '';
  myName = 'My000420Component';
}
