// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000489',
  templateUrl: './my.000489.component.html'
})
export class My000489Component {
  @Input() parentName = '';
  myName = 'My000489Component';
}
