// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000945Component } from './my.000945.component';
import { My000946Component } from './my.000946.component';
import { My000947Component } from './my.000947.component';
import { My000948Component } from './my.000948.component';
import { My000949Component } from './my.000949.component';
import { My000950Component } from './my.000950.component';

@NgModule({
  declarations: [
    My000945Component,
    My000946Component,
    My000947Component,
    My000948Component,
    My000949Component,
    My000950Component,
  ],
  imports: [CommonModule],
  exports: [
    My000945Component,
  ]
})
export class Module000140 { }
