// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001127Component } from './my.001127.component';
import { My001128Component } from './my.001128.component';
import { My001129Component } from './my.001129.component';
import { My001130Component } from './my.001130.component';
import { My001131Component } from './my.001131.component';
import { My001132Component } from './my.001132.component';
import { My001133Component } from './my.001133.component';
import { My001134Component } from './my.001134.component';

@NgModule({
  declarations: [
    My001127Component,
    My001128Component,
    My001129Component,
    My001130Component,
    My001131Component,
    My001132Component,
    My001133Component,
    My001134Component,
  ],
  imports: [CommonModule],
  exports: [
    My001127Component,
  ]
})
export class Module000140 { }
