// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000845Component } from './my.000845.component';
import { My000846Component } from './my.000846.component';
import { My000847Component } from './my.000847.component';
import { My000848Component } from './my.000848.component';
import { My000849Component } from './my.000849.component';
import { My000850Component } from './my.000850.component';

@NgModule({
  declarations: [
    My000845Component,
    My000846Component,
    My000847Component,
    My000848Component,
    My000849Component,
    My000850Component,
  ],
  imports: [CommonModule],
  exports: [
    My000845Component,
  ]
})
export class Module000140 { }
