// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000847',
  templateUrl: './my.000847.component.html'
})
export class My000847Component {
  @Input() parentName = '';
  myName = 'My000847Component';
}
