// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000279',
  templateUrl: './my.000279.component.html'
})
export class My000279Component {
  @Input() parentName = '';
  myName = 'My000279Component';
}
