// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000284',
  templateUrl: './my.000284.component.html'
})
export class My000284Component {
  @Input() parentName = '';
  myName = 'My000284Component';
}
