// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001007Component } from './my.001007.component';
import { My001008Component } from './my.001008.component';
import { My001009Component } from './my.001009.component';
import { My001010Component } from './my.001010.component';
import { My001011Component } from './my.001011.component';
import { My001012Component } from './my.001012.component';

@NgModule({
  declarations: [
    My001007Component,
    My001008Component,
    My001009Component,
    My001010Component,
    My001011Component,
    My001012Component,
  ],
  imports: [CommonModule],
  exports: [
    My001007Component,
  ]
})
export class Module000167 { }
