// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001349',
  templateUrl: './my.001349.component.html'
})
export class My001349Component {
  @Input() parentName = '';
  myName = 'My001349Component';
}
