// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001350',
  templateUrl: './my.001350.component.html'
})
export class My001350Component {
  @Input() parentName = '';
  myName = 'My001350Component';
}
