// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001344',
  templateUrl: './my.001344.component.html'
})
export class My001344Component {
  @Input() parentName = '';
  myName = 'My001344Component';
}
