// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001347',
  templateUrl: './my.001347.component.html'
})
export class My001347Component {
  @Input() parentName = '';
  myName = 'My001347Component';
}
