// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001071Component } from './my.001071.component';
import { My001072Component } from './my.001072.component';
import { My001073Component } from './my.001073.component';
import { My001074Component } from './my.001074.component';
import { My001075Component } from './my.001075.component';
import { My001076Component } from './my.001076.component';
import { My001077Component } from './my.001077.component';
import { My001078Component } from './my.001078.component';

@NgModule({
  declarations: [
    My001071Component,
    My001072Component,
    My001073Component,
    My001074Component,
    My001075Component,
    My001076Component,
    My001077Component,
    My001078Component,
  ],
  imports: [CommonModule],
  exports: [
    My001071Component,
  ]
})
export class Module000133 { }
