// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000775Component } from './my.000775.component';
import { My000776Component } from './my.000776.component';
import { My000777Component } from './my.000777.component';
import { My000778Component } from './my.000778.component';
import { My000779Component } from './my.000779.component';
import { My000780Component } from './my.000780.component';
import { My000781Component } from './my.000781.component';
import { My000782Component } from './my.000782.component';

@NgModule({
  declarations: [
    My000775Component,
    My000776Component,
    My000777Component,
    My000778Component,
    My000779Component,
    My000780Component,
    My000781Component,
    My000782Component,
  ],
  imports: [CommonModule],
  exports: [
    My000775Component,
  ]
})
export class Module000096 { }
