// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000263Component } from './my.000263.component';
import { My000264Component } from './my.000264.component';
import { My000265Component } from './my.000265.component';
import { My000266Component } from './my.000266.component';
import { My000267Component } from './my.000267.component';
import { My000268Component } from './my.000268.component';

@NgModule({
  declarations: [
    My000263Component,
    My000264Component,
    My000265Component,
    My000266Component,
    My000267Component,
    My000268Component,
  ],
  imports: [CommonModule],
  exports: [
    My000263Component,
  ]
})
export class Module000043 { }
