// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000301Component } from './my.000301.component';
import { My000302Component } from './my.000302.component';
import { My000303Component } from './my.000303.component';
import { My000304Component } from './my.000304.component';
import { My000305Component } from './my.000305.component';
import { My000306Component } from './my.000306.component';
import { My000307Component } from './my.000307.component';

@NgModule({
  declarations: [
    My000301Component,
    My000302Component,
    My000303Component,
    My000304Component,
    My000305Component,
    My000306Component,
    My000307Component,
  ],
  imports: [CommonModule],
  exports: [
    My000301Component,
  ]
})
export class Module000043 { }
