// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000351Component } from './my.000351.component';
import { My000352Component } from './my.000352.component';
import { My000353Component } from './my.000353.component';
import { My000354Component } from './my.000354.component';
import { My000355Component } from './my.000355.component';
import { My000356Component } from './my.000356.component';
import { My000357Component } from './my.000357.component';
import { My000358Component } from './my.000358.component';

@NgModule({
  declarations: [
    My000351Component,
    My000352Component,
    My000353Component,
    My000354Component,
    My000355Component,
    My000356Component,
    My000357Component,
    My000358Component,
  ],
  imports: [CommonModule],
  exports: [
    My000351Component,
  ]
})
export class Module000043 { }
