// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000665Component } from './my.000665.component';
import { My000666Component } from './my.000666.component';
import { My000667Component } from './my.000667.component';
import { My000668Component } from './my.000668.component';
import { My000669Component } from './my.000669.component';
import { My000670Component } from './my.000670.component';
import { My000671Component } from './my.000671.component';

@NgModule({
  declarations: [
    My000665Component,
    My000666Component,
    My000667Component,
    My000668Component,
    My000669Component,
    My000670Component,
    My000671Component,
  ],
  imports: [CommonModule],
  exports: [
    My000665Component,
  ]
})
export class Module000095 { }
