// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000767Component } from './my.000767.component';
import { My000768Component } from './my.000768.component';
import { My000769Component } from './my.000769.component';
import { My000770Component } from './my.000770.component';
import { My000771Component } from './my.000771.component';
import { My000772Component } from './my.000772.component';
import { My000773Component } from './my.000773.component';
import { My000774Component } from './my.000774.component';

@NgModule({
  declarations: [
    My000767Component,
    My000768Component,
    My000769Component,
    My000770Component,
    My000771Component,
    My000772Component,
    My000773Component,
    My000774Component,
  ],
  imports: [CommonModule],
  exports: [
    My000767Component,
  ]
})
export class Module000095 { }
