// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000399Component } from './my.000399.component';
import { My000400Component } from './my.000400.component';
import { My000401Component } from './my.000401.component';
import { My000402Component } from './my.000402.component';
import { My000403Component } from './my.000403.component';
import { My000404Component } from './my.000404.component';
import { My000405Component } from './my.000405.component';

@NgModule({
  declarations: [
    My000399Component,
    My000400Component,
    My000401Component,
    My000402Component,
    My000403Component,
    My000404Component,
    My000405Component,
  ],
  imports: [CommonModule],
  exports: [
    My000399Component,
  ]
})
export class Module000057 { }
