// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000347Component } from './my.000347.component';
import { My000348Component } from './my.000348.component';
import { My000349Component } from './my.000349.component';
import { My000350Component } from './my.000350.component';
import { My000351Component } from './my.000351.component';
import { My000352Component } from './my.000352.component';

@NgModule({
  declarations: [
    My000347Component,
    My000348Component,
    My000349Component,
    My000350Component,
    My000351Component,
    My000352Component,
  ],
  imports: [CommonModule],
  exports: [
    My000347Component,
  ]
})
export class Module000057 { }
