// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000731Component } from './my.000731.component';
import { My000732Component } from './my.000732.component';
import { My000733Component } from './my.000733.component';
import { My000734Component } from './my.000734.component';
import { My000735Component } from './my.000735.component';
import { My000736Component } from './my.000736.component';

@NgModule({
  declarations: [
    My000731Component,
    My000732Component,
    My000733Component,
    My000734Component,
    My000735Component,
    My000736Component,
  ],
  imports: [CommonModule],
  exports: [
    My000731Component,
  ]
})
export class Module000121 { }
