// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000731',
  templateUrl: './my.000731.component.html'
})
export class My000731Component {
  @Input() parentName = '';
  myName = 'My000731Component';
}
