// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001864',
  templateUrl: './my.001864.component.html'
})
export class My001864Component {
  @Input() parentName = '';
  myName = 'My001864Component';
}
