// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001863',
  templateUrl: './my.001863.component.html'
})
export class My001863Component {
  @Input() parentName = '';
  myName = 'My001863Component';
}
