// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001402',
  templateUrl: './my.001402.component.html'
})
export class My001402Component {
  @Input() parentName = '';
  myName = 'My001402Component';
}
