// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001866',
  templateUrl: './my.001866.component.html'
})
export class My001866Component {
  @Input() parentName = '';
  myName = 'My001866Component';
}
