// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001870',
  templateUrl: './my.001870.component.html'
})
export class My001870Component {
  @Input() parentName = '';
  myName = 'My001870Component';
}
