// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001865',
  templateUrl: './my.001865.component.html'
})
export class My001865Component {
  @Input() parentName = '';
  myName = 'My001865Component';
}
