// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001868',
  templateUrl: './my.001868.component.html'
})
export class My001868Component {
  @Input() parentName = '';
  myName = 'My001868Component';
}
