// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001771',
  templateUrl: './my.001771.component.html'
})
export class My001771Component {
  @Input() parentName = '';
  myName = 'My001771Component';
}
