// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001770',
  templateUrl: './my.001770.component.html'
})
export class My001770Component {
  @Input() parentName = '';
  myName = 'My001770Component';
}
