// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001773',
  templateUrl: './my.001773.component.html'
})
export class My001773Component {
  @Input() parentName = '';
  myName = 'My001773Component';
}
