// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001330',
  templateUrl: './my.001330.component.html'
})
export class My001330Component {
  @Input() parentName = '';
  myName = 'My001330Component';
}
