// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001767',
  templateUrl: './my.001767.component.html'
})
export class My001767Component {
  @Input() parentName = '';
  myName = 'My001767Component';
}
