// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001769',
  templateUrl: './my.001769.component.html'
})
export class My001769Component {
  @Input() parentName = '';
  myName = 'My001769Component';
}
