// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001772',
  templateUrl: './my.001772.component.html'
})
export class My001772Component {
  @Input() parentName = '';
  myName = 'My001772Component';
}
