// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000314',
  templateUrl: './my.000314.component.html'
})
export class My000314Component {
  @Input() parentName = '';
  myName = 'My000314Component';
}
