// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000375',
  templateUrl: './my.000375.component.html'
})
export class My000375Component {
  @Input() parentName = '';
  myName = 'My000375Component';
}
