// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000359Component } from './my.000359.component';
import { My000360Component } from './my.000360.component';
import { My000361Component } from './my.000361.component';
import { My000362Component } from './my.000362.component';
import { My000363Component } from './my.000363.component';
import { My000364Component } from './my.000364.component';
import { My000365Component } from './my.000365.component';
import { My000366Component } from './my.000366.component';

@NgModule({
  declarations: [
    My000359Component,
    My000360Component,
    My000361Component,
    My000362Component,
    My000363Component,
    My000364Component,
    My000365Component,
    My000366Component,
  ],
  imports: [CommonModule],
  exports: [
    My000359Component,
  ]
})
export class Module000044 { }
