// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000365',
  templateUrl: './my.000365.component.html'
})
export class My000365Component {
  @Input() parentName = '';
  myName = 'My000365Component';
}
