// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001672',
  templateUrl: './my.001672.component.html'
})
export class My001672Component {
  @Input() parentName = '';
  myName = 'My001672Component';
}
