// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001674',
  templateUrl: './my.001674.component.html'
})
export class My001674Component {
  @Input() parentName = '';
  myName = 'My001674Component';
}
