// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001671',
  templateUrl: './my.001671.component.html'
})
export class My001671Component {
  @Input() parentName = '';
  myName = 'My001671Component';
}
