// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001676',
  templateUrl: './my.001676.component.html'
})
export class My001676Component {
  @Input() parentName = '';
  myName = 'My001676Component';
}
