// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001258',
  templateUrl: './my.001258.component.html'
})
export class My001258Component {
  @Input() parentName = '';
  myName = 'My001258Component';
}
