// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000071Component } from './my.000071.component';
import { My000072Component } from './my.000072.component';
import { My000073Component } from './my.000073.component';
import { My000074Component } from './my.000074.component';
import { My000075Component } from './my.000075.component';
import { My000076Component } from './my.000076.component';
import { My000077Component } from './my.000077.component';
import { My000078Component } from './my.000078.component';

@NgModule({
  declarations: [
    My000071Component,
    My000072Component,
    My000073Component,
    My000074Component,
    My000075Component,
    My000076Component,
    My000077Component,
    My000078Component,
  ],
  imports: [CommonModule],
  exports: [
    My000071Component,
  ]
})
export class Module000008 { }
