// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001289Component } from './my.001289.component';
import { My001290Component } from './my.001290.component';
import { My001291Component } from './my.001291.component';
import { My001292Component } from './my.001292.component';
import { My001293Component } from './my.001293.component';
import { My001294Component } from './my.001294.component';

@NgModule({
  declarations: [
    My001289Component,
    My001290Component,
    My001291Component,
    My001292Component,
    My001293Component,
    My001294Component,
  ],
  imports: [CommonModule],
  exports: [
    My001289Component,
  ]
})
export class Module000214 { }
