// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001722',
  templateUrl: './my.001722.component.html'
})
export class My001722Component {
  @Input() parentName = '';
  myName = 'My001722Component';
}
