// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001721',
  templateUrl: './my.001721.component.html'
})
export class My001721Component {
  @Input() parentName = '';
  myName = 'My001721Component';
}
