// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001719',
  templateUrl: './my.001719.component.html'
})
export class My001719Component {
  @Input() parentName = '';
  myName = 'My001719Component';
}
