// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001720',
  templateUrl: './my.001720.component.html'
})
export class My001720Component {
  @Input() parentName = '';
  myName = 'My001720Component';
}
