// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001726',
  templateUrl: './my.001726.component.html'
})
export class My001726Component {
  @Input() parentName = '';
  myName = 'My001726Component';
}
