// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001293',
  templateUrl: './my.001293.component.html'
})
export class My001293Component {
  @Input() parentName = '';
  myName = 'My001293Component';
}
