// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001725',
  templateUrl: './my.001725.component.html'
})
export class My001725Component {
  @Input() parentName = '';
  myName = 'My001725Component';
}
