// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001291',
  templateUrl: './my.001291.component.html'
})
export class My001291Component {
  @Input() parentName = '';
  myName = 'My001291Component';
}
