// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001724',
  templateUrl: './my.001724.component.html'
})
export class My001724Component {
  @Input() parentName = '';
  myName = 'My001724Component';
}
