// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000150',
  templateUrl: './my.000150.component.html'
})
export class My000150Component {
  @Input() parentName = '';
  myName = 'My000150Component';
}
