// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000149',
  templateUrl: './my.000149.component.html'
})
export class My000149Component {
  @Input() parentName = '';
  myName = 'My000149Component';
}
