// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001871Component } from './my.001871.component';
import { My001872Component } from './my.001872.component';
import { My001873Component } from './my.001873.component';
import { My001874Component } from './my.001874.component';
import { My001875Component } from './my.001875.component';
import { My001876Component } from './my.001876.component';
import { My001877Component } from './my.001877.component';
import { My001878Component } from './my.001878.component';

@NgModule({
  declarations: [
    My001871Component,
    My001872Component,
    My001873Component,
    My001874Component,
    My001875Component,
    My001876Component,
    My001877Component,
    My001878Component,
  ],
  imports: [CommonModule],
  exports: [
    My001871Component,
  ]
})
export class Module000233 { }
