// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001403Component } from './my.001403.component';
import { My001404Component } from './my.001404.component';
import { My001405Component } from './my.001405.component';
import { My001406Component } from './my.001406.component';
import { My001407Component } from './my.001407.component';
import { My001408Component } from './my.001408.component';

@NgModule({
  declarations: [
    My001403Component,
    My001404Component,
    My001405Component,
    My001406Component,
    My001407Component,
    My001408Component,
  ],
  imports: [CommonModule],
  exports: [
    My001403Component,
  ]
})
export class Module000233 { }
