// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001871',
  templateUrl: './my.001871.component.html'
})
export class My001871Component {
  @Input() parentName = '';
  myName = 'My001871Component';
}
