// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001877',
  templateUrl: './my.001877.component.html'
})
export class My001877Component {
  @Input() parentName = '';
  myName = 'My001877Component';
}
