// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001873',
  templateUrl: './my.001873.component.html'
})
export class My001873Component {
  @Input() parentName = '';
  myName = 'My001873Component';
}
