// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001405',
  templateUrl: './my.001405.component.html'
})
export class My001405Component {
  @Input() parentName = '';
  myName = 'My001405Component';
}
