// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001878',
  templateUrl: './my.001878.component.html'
})
export class My001878Component {
  @Input() parentName = '';
  myName = 'My001878Component';
}
