// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001872',
  templateUrl: './my.001872.component.html'
})
export class My001872Component {
  @Input() parentName = '';
  myName = 'My001872Component';
}
