// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001874',
  templateUrl: './my.001874.component.html'
})
export class My001874Component {
  @Input() parentName = '';
  myName = 'My001874Component';
}
