// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001079Component } from './my.001079.component';
import { My001080Component } from './my.001080.component';
import { My001081Component } from './my.001081.component';
import { My001082Component } from './my.001082.component';
import { My001083Component } from './my.001083.component';
import { My001084Component } from './my.001084.component';
import { My001085Component } from './my.001085.component';
import { My001086Component } from './my.001086.component';

@NgModule({
  declarations: [
    My001079Component,
    My001080Component,
    My001081Component,
    My001082Component,
    My001083Component,
    My001084Component,
    My001085Component,
    My001086Component,
  ],
  imports: [CommonModule],
  exports: [
    My001079Component,
  ]
})
export class Module000134 { }
