// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001081',
  templateUrl: './my.001081.component.html'
})
export class My001081Component {
  @Input() parentName = '';
  myName = 'My001081Component';
}
