// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001433Component } from './my.001433.component';
import { My001434Component } from './my.001434.component';
import { My001435Component } from './my.001435.component';
import { My001436Component } from './my.001436.component';
import { My001437Component } from './my.001437.component';
import { My001438Component } from './my.001438.component';

@NgModule({
  declarations: [
    My001433Component,
    My001434Component,
    My001435Component,
    My001436Component,
    My001437Component,
    My001438Component,
  ],
  imports: [CommonModule],
  exports: [
    My001433Component,
  ]
})
export class Module000238 { }
