// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001914',
  templateUrl: './my.001914.component.html'
})
export class My001914Component {
  @Input() parentName = '';
  myName = 'My001914Component';
}
