// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001434',
  templateUrl: './my.001434.component.html'
})
export class My001434Component {
  @Input() parentName = '';
  myName = 'My001434Component';
}
