// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001433',
  templateUrl: './my.001433.component.html'
})
export class My001433Component {
  @Input() parentName = '';
  myName = 'My001433Component';
}
