// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001913',
  templateUrl: './my.001913.component.html'
})
export class My001913Component {
  @Input() parentName = '';
  myName = 'My001913Component';
}
