// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001436',
  templateUrl: './my.001436.component.html'
})
export class My001436Component {
  @Input() parentName = '';
  myName = 'My001436Component';
}
