// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001437',
  templateUrl: './my.001437.component.html'
})
export class My001437Component {
  @Input() parentName = '';
  myName = 'My001437Component';
}
