// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001918',
  templateUrl: './my.001918.component.html'
})
export class My001918Component {
  @Input() parentName = '';
  myName = 'My001918Component';
}
