// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001916',
  templateUrl: './my.001916.component.html'
})
export class My001916Component {
  @Input() parentName = '';
  myName = 'My001916Component';
}
