// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001438',
  templateUrl: './my.001438.component.html'
})
export class My001438Component {
  @Input() parentName = '';
  myName = 'My001438Component';
}
