// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001421Component } from './my.001421.component';
import { My001422Component } from './my.001422.component';
import { My001423Component } from './my.001423.component';
import { My001424Component } from './my.001424.component';
import { My001425Component } from './my.001425.component';
import { My001426Component } from './my.001426.component';

@NgModule({
  declarations: [
    My001421Component,
    My001422Component,
    My001423Component,
    My001424Component,
    My001425Component,
    My001426Component,
  ],
  imports: [CommonModule],
  exports: [
    My001421Component,
  ]
})
export class Module000236 { }
