// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001898',
  templateUrl: './my.001898.component.html'
})
export class My001898Component {
  @Input() parentName = '';
  myName = 'My001898Component';
}
