// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001423',
  templateUrl: './my.001423.component.html'
})
export class My001423Component {
  @Input() parentName = '';
  myName = 'My001423Component';
}
