// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001900',
  templateUrl: './my.001900.component.html'
})
export class My001900Component {
  @Input() parentName = '';
  myName = 'My001900Component';
}
