// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001902',
  templateUrl: './my.001902.component.html'
})
export class My001902Component {
  @Input() parentName = '';
  myName = 'My001902Component';
}
