// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001901',
  templateUrl: './my.001901.component.html'
})
export class My001901Component {
  @Input() parentName = '';
  myName = 'My001901Component';
}
