// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001895',
  templateUrl: './my.001895.component.html'
})
export class My001895Component {
  @Input() parentName = '';
  myName = 'My001895Component';
}
