// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001421',
  templateUrl: './my.001421.component.html'
})
export class My001421Component {
  @Input() parentName = '';
  myName = 'My001421Component';
}
