// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001899',
  templateUrl: './my.001899.component.html'
})
export class My001899Component {
  @Input() parentName = '';
  myName = 'My001899Component';
}
