// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001401',
  templateUrl: './my.001401.component.html'
})
export class My001401Component {
  @Input() parentName = '';
  myName = 'My001401Component';
}
