// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001406',
  templateUrl: './my.001406.component.html'
})
export class My001406Component {
  @Input() parentName = '';
  myName = 'My001406Component';
}
