// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001400',
  templateUrl: './my.001400.component.html'
})
export class My001400Component {
  @Input() parentName = '';
  myName = 'My001400Component';
}
