// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001143Component } from './my.001143.component';
import { My001144Component } from './my.001144.component';
import { My001145Component } from './my.001145.component';
import { My001146Component } from './my.001146.component';
import { My001147Component } from './my.001147.component';
import { My001148Component } from './my.001148.component';
import { My001149Component } from './my.001149.component';
import { My001150Component } from './my.001150.component';

@NgModule({
  declarations: [
    My001143Component,
    My001144Component,
    My001145Component,
    My001146Component,
    My001147Component,
    My001148Component,
    My001149Component,
    My001150Component,
  ],
  imports: [CommonModule],
  exports: [
    My001143Component,
  ]
})
export class Module000142 { }
