// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000957Component } from './my.000957.component';
import { My000958Component } from './my.000958.component';
import { My000959Component } from './my.000959.component';
import { My000960Component } from './my.000960.component';
import { My000961Component } from './my.000961.component';
import { My000962Component } from './my.000962.component';

@NgModule({
  declarations: [
    My000957Component,
    My000958Component,
    My000959Component,
    My000960Component,
    My000961Component,
    My000962Component,
  ],
  imports: [CommonModule],
  exports: [
    My000957Component,
  ]
})
export class Module000142 { }
