// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000961',
  templateUrl: './my.000961.component.html'
})
export class My000961Component {
  @Input() parentName = '';
  myName = 'My000961Component';
}
