// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000899Component } from './my.000899.component';
import { My000900Component } from './my.000900.component';
import { My000901Component } from './my.000901.component';
import { My000902Component } from './my.000902.component';
import { My000903Component } from './my.000903.component';
import { My000904Component } from './my.000904.component';

@NgModule({
  declarations: [
    My000899Component,
    My000900Component,
    My000901Component,
    My000902Component,
    My000903Component,
    My000904Component,
  ],
  imports: [CommonModule],
  exports: [
    My000899Component,
  ]
})
export class Module000149 { }
