// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001202',
  templateUrl: './my.001202.component.html'
})
export class My001202Component {
  @Input() parentName = '';
  myName = 'My001202Component';
}
