// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001203',
  templateUrl: './my.001203.component.html'
})
export class My001203Component {
  @Input() parentName = '';
  myName = 'My001203Component';
}
