// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001199',
  templateUrl: './my.001199.component.html'
})
export class My001199Component {
  @Input() parentName = '';
  myName = 'My001199Component';
}
