// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001205',
  templateUrl: './my.001205.component.html'
})
export class My001205Component {
  @Input() parentName = '';
  myName = 'My001205Component';
}
