// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001586',
  templateUrl: './my.001586.component.html'
})
export class My001586Component {
  @Input() parentName = '';
  myName = 'My001586Component';
}
