// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001585',
  templateUrl: './my.001585.component.html'
})
export class My001585Component {
  @Input() parentName = '';
  myName = 'My001585Component';
}
