// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001584',
  templateUrl: './my.001584.component.html'
})
export class My001584Component {
  @Input() parentName = '';
  myName = 'My001584Component';
}
