// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001589',
  templateUrl: './my.001589.component.html'
})
export class My001589Component {
  @Input() parentName = '';
  myName = 'My001589Component';
}
