// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001590',
  templateUrl: './my.001590.component.html'
})
export class My001590Component {
  @Input() parentName = '';
  myName = 'My001590Component';
}
