// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001583',
  templateUrl: './my.001583.component.html'
})
export class My001583Component {
  @Input() parentName = '';
  myName = 'My001583Component';
}
