// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001588',
  templateUrl: './my.001588.component.html'
})
export class My001588Component {
  @Input() parentName = '';
  myName = 'My001588Component';
}
