// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001587',
  templateUrl: './my.001587.component.html'
})
export class My001587Component {
  @Input() parentName = '';
  myName = 'My001587Component';
}
