// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000515Component } from './my.000515.component';
import { My000516Component } from './my.000516.component';
import { My000517Component } from './my.000517.component';
import { My000518Component } from './my.000518.component';
import { My000519Component } from './my.000519.component';
import { My000520Component } from './my.000520.component';

@NgModule({
  declarations: [
    My000515Component,
    My000516Component,
    My000517Component,
    My000518Component,
    My000519Component,
    My000520Component,
  ],
  imports: [CommonModule],
  exports: [
    My000515Component,
  ]
})
export class Module000085 { }
