// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000520',
  templateUrl: './my.000520.component.html'
})
export class My000520Component {
  @Input() parentName = '';
  myName = 'My000520Component';
}
