// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000595',
  templateUrl: './my.000595.component.html'
})
export class My000595Component {
  @Input() parentName = '';
  myName = 'My000595Component';
}
