// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000635Component } from './my.000635.component';
import { My000636Component } from './my.000636.component';
import { My000637Component } from './my.000637.component';
import { My000638Component } from './my.000638.component';
import { My000639Component } from './my.000639.component';
import { My000640Component } from './my.000640.component';

@NgModule({
  declarations: [
    My000635Component,
    My000636Component,
    My000637Component,
    My000638Component,
    My000639Component,
    My000640Component,
  ],
  imports: [CommonModule],
  exports: [
    My000635Component,
  ]
})
export class Module000105 { }
