// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001791Component } from './my.001791.component';
import { My001792Component } from './my.001792.component';
import { My001793Component } from './my.001793.component';
import { My001794Component } from './my.001794.component';
import { My001795Component } from './my.001795.component';
import { My001796Component } from './my.001796.component';
import { My001797Component } from './my.001797.component';
import { My001798Component } from './my.001798.component';

@NgModule({
  declarations: [
    My001791Component,
    My001792Component,
    My001793Component,
    My001794Component,
    My001795Component,
    My001796Component,
    My001797Component,
    My001798Component,
  ],
  imports: [CommonModule],
  exports: [
    My001791Component,
  ]
})
export class Module000223 { }
