// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001792',
  templateUrl: './my.001792.component.html'
})
export class My001792Component {
  @Input() parentName = '';
  myName = 'My001792Component';
}
