// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001796',
  templateUrl: './my.001796.component.html'
})
export class My001796Component {
  @Input() parentName = '';
  myName = 'My001796Component';
}
