// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001791',
  templateUrl: './my.001791.component.html'
})
export class My001791Component {
  @Input() parentName = '';
  myName = 'My001791Component';
}
