// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001343',
  templateUrl: './my.001343.component.html'
})
export class My001343Component {
  @Input() parentName = '';
  myName = 'My001343Component';
}
