// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001793',
  templateUrl: './my.001793.component.html'
})
export class My001793Component {
  @Input() parentName = '';
  myName = 'My001793Component';
}
