// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001797',
  templateUrl: './my.001797.component.html'
})
export class My001797Component {
  @Input() parentName = '';
  myName = 'My001797Component';
}
