// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001794',
  templateUrl: './my.001794.component.html'
})
export class My001794Component {
  @Input() parentName = '';
  myName = 'My001794Component';
}
