// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001879Component } from './my.001879.component';
import { My001880Component } from './my.001880.component';
import { My001881Component } from './my.001881.component';
import { My001882Component } from './my.001882.component';
import { My001883Component } from './my.001883.component';
import { My001884Component } from './my.001884.component';
import { My001885Component } from './my.001885.component';
import { My001886Component } from './my.001886.component';

@NgModule({
  declarations: [
    My001879Component,
    My001880Component,
    My001881Component,
    My001882Component,
    My001883Component,
    My001884Component,
    My001885Component,
    My001886Component,
  ],
  imports: [CommonModule],
  exports: [
    My001879Component,
  ]
})
export class Module000234 { }
