// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001881',
  templateUrl: './my.001881.component.html'
})
export class My001881Component {
  @Input() parentName = '';
  myName = 'My001881Component';
}
