// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001413',
  templateUrl: './my.001413.component.html'
})
export class My001413Component {
  @Input() parentName = '';
  myName = 'My001413Component';
}
