// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001886',
  templateUrl: './my.001886.component.html'
})
export class My001886Component {
  @Input() parentName = '';
  myName = 'My001886Component';
}
