// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001414',
  templateUrl: './my.001414.component.html'
})
export class My001414Component {
  @Input() parentName = '';
  myName = 'My001414Component';
}
