// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001411',
  templateUrl: './my.001411.component.html'
})
export class My001411Component {
  @Input() parentName = '';
  myName = 'My001411Component';
}
