// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001880',
  templateUrl: './my.001880.component.html'
})
export class My001880Component {
  @Input() parentName = '';
  myName = 'My001880Component';
}
