// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001885',
  templateUrl: './my.001885.component.html'
})
export class My001885Component {
  @Input() parentName = '';
  myName = 'My001885Component';
}
