// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000104',
  templateUrl: './my.000104.component.html'
})
export class My000104Component {
  @Input() parentName = '';
  myName = 'My000104Component';
}
