// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000101',
  templateUrl: './my.000101.component.html'
})
export class My000101Component {
  @Input() parentName = '';
  myName = 'My000101Component';
}
