// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001337Component } from './my.001337.component';
import { My001338Component } from './my.001338.component';
import { My001339Component } from './my.001339.component';
import { My001340Component } from './my.001340.component';
import { My001341Component } from './my.001341.component';
import { My001342Component } from './my.001342.component';

@NgModule({
  declarations: [
    My001337Component,
    My001338Component,
    My001339Component,
    My001340Component,
    My001341Component,
    My001342Component,
  ],
  imports: [CommonModule],
  exports: [
    My001337Component,
  ]
})
export class Module000222 { }
