// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001788',
  templateUrl: './my.001788.component.html'
})
export class My001788Component {
  @Input() parentName = '';
  myName = 'My001788Component';
}
