// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001789',
  templateUrl: './my.001789.component.html'
})
export class My001789Component {
  @Input() parentName = '';
  myName = 'My001789Component';
}
