// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001784',
  templateUrl: './my.001784.component.html'
})
export class My001784Component {
  @Input() parentName = '';
  myName = 'My001784Component';
}
