// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001790',
  templateUrl: './my.001790.component.html'
})
export class My001790Component {
  @Input() parentName = '';
  myName = 'My001790Component';
}
