// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001787',
  templateUrl: './my.001787.component.html'
})
export class My001787Component {
  @Input() parentName = '';
  myName = 'My001787Component';
}
