// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000439Component } from './my.000439.component';
import { My000440Component } from './my.000440.component';
import { My000441Component } from './my.000441.component';
import { My000442Component } from './my.000442.component';
import { My000443Component } from './my.000443.component';
import { My000444Component } from './my.000444.component';
import { My000445Component } from './my.000445.component';
import { My000446Component } from './my.000446.component';

@NgModule({
  declarations: [
    My000439Component,
    My000440Component,
    My000441Component,
    My000442Component,
    My000443Component,
    My000444Component,
    My000445Component,
    My000446Component,
  ],
  imports: [CommonModule],
  exports: [
    My000439Component,
  ]
})
export class Module000054 { }
