// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000378Component } from './my.000378.component';
import { My000379Component } from './my.000379.component';
import { My000380Component } from './my.000380.component';
import { My000381Component } from './my.000381.component';
import { My000382Component } from './my.000382.component';
import { My000383Component } from './my.000383.component';
import { My000384Component } from './my.000384.component';

@NgModule({
  declarations: [
    My000378Component,
    My000379Component,
    My000380Component,
    My000381Component,
    My000382Component,
    My000383Component,
    My000384Component,
  ],
  imports: [CommonModule],
  exports: [
    My000378Component,
  ]
})
export class Module000054 { }
