// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001623',
  templateUrl: './my.001623.component.html'
})
export class My001623Component {
  @Input() parentName = '';
  myName = 'My001623Component';
}
