// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001629',
  templateUrl: './my.001629.component.html'
})
export class My001629Component {
  @Input() parentName = '';
  myName = 'My001629Component';
}
