// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001218',
  templateUrl: './my.001218.component.html'
})
export class My001218Component {
  @Input() parentName = '';
  myName = 'My001218Component';
}
