// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001630',
  templateUrl: './my.001630.component.html'
})
export class My001630Component {
  @Input() parentName = '';
  myName = 'My001630Component';
}
