// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001628',
  templateUrl: './my.001628.component.html'
})
export class My001628Component {
  @Input() parentName = '';
  myName = 'My001628Component';
}
