// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001217',
  templateUrl: './my.001217.component.html'
})
export class My001217Component {
  @Input() parentName = '';
  myName = 'My001217Component';
}
