// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001624',
  templateUrl: './my.001624.component.html'
})
export class My001624Component {
  @Input() parentName = '';
  myName = 'My001624Component';
}
