// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001115Component } from './my.001115.component';
import { My001116Component } from './my.001116.component';
import { My001117Component } from './my.001117.component';
import { My001118Component } from './my.001118.component';
import { My001119Component } from './my.001119.component';
import { My001120Component } from './my.001120.component';

@NgModule({
  declarations: [
    My001115Component,
    My001116Component,
    My001117Component,
    My001118Component,
    My001119Component,
    My001120Component,
  ],
  imports: [CommonModule],
  exports: [
    My001115Component,
  ]
})
export class Module000185 { }
