// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001492',
  templateUrl: './my.001492.component.html'
})
export class My001492Component {
  @Input() parentName = '';
  myName = 'My001492Component';
}
