// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001494',
  templateUrl: './my.001494.component.html'
})
export class My001494Component {
  @Input() parentName = '';
  myName = 'My001494Component';
}
