// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001491',
  templateUrl: './my.001491.component.html'
})
export class My001491Component {
  @Input() parentName = '';
  myName = 'My001491Component';
}
