// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000951Component } from './my.000951.component';
import { My000952Component } from './my.000952.component';
import { My000953Component } from './my.000953.component';
import { My000954Component } from './my.000954.component';
import { My000955Component } from './my.000955.component';
import { My000956Component } from './my.000956.component';
import { My000957Component } from './my.000957.component';
import { My000958Component } from './my.000958.component';

@NgModule({
  declarations: [
    My000951Component,
    My000952Component,
    My000953Component,
    My000954Component,
    My000955Component,
    My000956Component,
    My000957Component,
    My000958Component,
  ],
  imports: [CommonModule],
  exports: [
    My000951Component,
  ]
})
export class Module000118 { }
