// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000813Component } from './my.000813.component';
import { My000814Component } from './my.000814.component';
import { My000815Component } from './my.000815.component';
import { My000816Component } from './my.000816.component';
import { My000817Component } from './my.000817.component';
import { My000818Component } from './my.000818.component';

@NgModule({
  declarations: [
    My000813Component,
    My000814Component,
    My000815Component,
    My000816Component,
    My000817Component,
    My000818Component,
  ],
  imports: [CommonModule],
  exports: [
    My000813Component,
  ]
})
export class Module000118 { }
