// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001727',
  templateUrl: './my.001727.component.html'
})
export class My001727Component {
  @Input() parentName = '';
  myName = 'My001727Component';
}
