// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001728',
  templateUrl: './my.001728.component.html'
})
export class My001728Component {
  @Input() parentName = '';
  myName = 'My001728Component';
}
