// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001300',
  templateUrl: './my.001300.component.html'
})
export class My001300Component {
  @Input() parentName = '';
  myName = 'My001300Component';
}
