// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001732',
  templateUrl: './my.001732.component.html'
})
export class My001732Component {
  @Input() parentName = '';
  myName = 'My001732Component';
}
