// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001733',
  templateUrl: './my.001733.component.html'
})
export class My001733Component {
  @Input() parentName = '';
  myName = 'My001733Component';
}
