// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001731',
  templateUrl: './my.001731.component.html'
})
export class My001731Component {
  @Input() parentName = '';
  myName = 'My001731Component';
}
