// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001296',
  templateUrl: './my.001296.component.html'
})
export class My001296Component {
  @Input() parentName = '';
  myName = 'My001296Component';
}
