// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001666',
  templateUrl: './my.001666.component.html'
})
export class My001666Component {
  @Input() parentName = '';
  myName = 'My001666Component';
}
