// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001250',
  templateUrl: './my.001250.component.html'
})
export class My001250Component {
  @Input() parentName = '';
  myName = 'My001250Component';
}
