// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001251',
  templateUrl: './my.001251.component.html'
})
export class My001251Component {
  @Input() parentName = '';
  myName = 'My001251Component';
}
