// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001670',
  templateUrl: './my.001670.component.html'
})
export class My001670Component {
  @Input() parentName = '';
  myName = 'My001670Component';
}
