// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001669',
  templateUrl: './my.001669.component.html'
})
export class My001669Component {
  @Input() parentName = '';
  myName = 'My001669Component';
}
