// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001668',
  templateUrl: './my.001668.component.html'
})
export class My001668Component {
  @Input() parentName = '';
  myName = 'My001668Component';
}
