// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001667',
  templateUrl: './my.001667.component.html'
})
export class My001667Component {
  @Input() parentName = '';
  myName = 'My001667Component';
}
