// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001663',
  templateUrl: './my.001663.component.html'
})
export class My001663Component {
  @Input() parentName = '';
  myName = 'My001663Component';
}
