// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000873Component } from './my.000873.component';
import { My000874Component } from './my.000874.component';
import { My000875Component } from './my.000875.component';
import { My000876Component } from './my.000876.component';
import { My000877Component } from './my.000877.component';
import { My000878Component } from './my.000878.component';

@NgModule({
  declarations: [
    My000873Component,
    My000874Component,
    My000875Component,
    My000876Component,
    My000877Component,
    My000878Component,
  ],
  imports: [CommonModule],
  exports: [
    My000873Component,
  ]
})
export class Module000128 { }
