// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000322Component } from './my.000322.component';
import { My000323Component } from './my.000323.component';
import { My000324Component } from './my.000324.component';
import { My000325Component } from './my.000325.component';
import { My000326Component } from './my.000326.component';
import { My000327Component } from './my.000327.component';
import { My000328Component } from './my.000328.component';

@NgModule({
  declarations: [
    My000322Component,
    My000323Component,
    My000324Component,
    My000325Component,
    My000326Component,
    My000327Component,
    My000328Component,
  ],
  imports: [CommonModule],
  exports: [
    My000322Component,
  ]
})
export class Module000046 { }
