// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000281Component } from './my.000281.component';
import { My000282Component } from './my.000282.component';
import { My000283Component } from './my.000283.component';
import { My000284Component } from './my.000284.component';
import { My000285Component } from './my.000285.component';
import { My000286Component } from './my.000286.component';

@NgModule({
  declarations: [
    My000281Component,
    My000282Component,
    My000283Component,
    My000284Component,
    My000285Component,
    My000286Component,
  ],
  imports: [CommonModule],
  exports: [
    My000281Component,
  ]
})
export class Module000046 { }
