// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001352',
  templateUrl: './my.001352.component.html'
})
export class My001352Component {
  @Input() parentName = '';
  myName = 'My001352Component';
}
