// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001355',
  templateUrl: './my.001355.component.html'
})
export class My001355Component {
  @Input() parentName = '';
  myName = 'My001355Component';
}
