// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000855',
  templateUrl: './my.000855.component.html'
})
export class My000855Component {
  @Input() parentName = '';
  myName = 'My000855Component';
}
