// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001607Component } from './my.001607.component';
import { My001608Component } from './my.001608.component';
import { My001609Component } from './my.001609.component';
import { My001610Component } from './my.001610.component';
import { My001611Component } from './my.001611.component';
import { My001612Component } from './my.001612.component';
import { My001613Component } from './my.001613.component';
import { My001614Component } from './my.001614.component';

@NgModule({
  declarations: [
    My001607Component,
    My001608Component,
    My001609Component,
    My001610Component,
    My001611Component,
    My001612Component,
    My001613Component,
    My001614Component,
  ],
  imports: [CommonModule],
  exports: [
    My001607Component,
  ]
})
export class Module000200 { }
