// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001205Component } from './my.001205.component';
import { My001206Component } from './my.001206.component';
import { My001207Component } from './my.001207.component';
import { My001208Component } from './my.001208.component';
import { My001209Component } from './my.001209.component';
import { My001210Component } from './my.001210.component';

@NgModule({
  declarations: [
    My001205Component,
    My001206Component,
    My001207Component,
    My001208Component,
    My001209Component,
    My001210Component,
  ],
  imports: [CommonModule],
  exports: [
    My001205Component,
  ]
})
export class Module000200 { }
