// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001612',
  templateUrl: './my.001612.component.html'
})
export class My001612Component {
  @Input() parentName = '';
  myName = 'My001612Component';
}
