// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001607',
  templateUrl: './my.001607.component.html'
})
export class My001607Component {
  @Input() parentName = '';
  myName = 'My001607Component';
}
