// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001207',
  templateUrl: './my.001207.component.html'
})
export class My001207Component {
  @Input() parentName = '';
  myName = 'My001207Component';
}
