// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001610',
  templateUrl: './my.001610.component.html'
})
export class My001610Component {
  @Input() parentName = '';
  myName = 'My001610Component';
}
