// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001208',
  templateUrl: './my.001208.component.html'
})
export class My001208Component {
  @Input() parentName = '';
  myName = 'My001208Component';
}
