// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001614',
  templateUrl: './my.001614.component.html'
})
export class My001614Component {
  @Input() parentName = '';
  myName = 'My001614Component';
}
