// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001631Component } from './my.001631.component';
import { My001632Component } from './my.001632.component';
import { My001633Component } from './my.001633.component';
import { My001634Component } from './my.001634.component';
import { My001635Component } from './my.001635.component';
import { My001636Component } from './my.001636.component';
import { My001637Component } from './my.001637.component';
import { My001638Component } from './my.001638.component';

@NgModule({
  declarations: [
    My001631Component,
    My001632Component,
    My001633Component,
    My001634Component,
    My001635Component,
    My001636Component,
    My001637Component,
    My001638Component,
  ],
  imports: [CommonModule],
  exports: [
    My001631Component,
  ]
})
export class Module000203 { }
