// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001223Component } from './my.001223.component';
import { My001224Component } from './my.001224.component';
import { My001225Component } from './my.001225.component';
import { My001226Component } from './my.001226.component';
import { My001227Component } from './my.001227.component';
import { My001228Component } from './my.001228.component';

@NgModule({
  declarations: [
    My001223Component,
    My001224Component,
    My001225Component,
    My001226Component,
    My001227Component,
    My001228Component,
  ],
  imports: [CommonModule],
  exports: [
    My001223Component,
  ]
})
export class Module000203 { }
