// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001636',
  templateUrl: './my.001636.component.html'
})
export class My001636Component {
  @Input() parentName = '';
  myName = 'My001636Component';
}
