// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001224',
  templateUrl: './my.001224.component.html'
})
export class My001224Component {
  @Input() parentName = '';
  myName = 'My001224Component';
}
