// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001635',
  templateUrl: './my.001635.component.html'
})
export class My001635Component {
  @Input() parentName = '';
  myName = 'My001635Component';
}
