// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001634',
  templateUrl: './my.001634.component.html'
})
export class My001634Component {
  @Input() parentName = '';
  myName = 'My001634Component';
}
