// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001225',
  templateUrl: './my.001225.component.html'
})
export class My001225Component {
  @Input() parentName = '';
  myName = 'My001225Component';
}
