// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000059Component } from './my.000059.component';
import { My000060Component } from './my.000060.component';
import { My000061Component } from './my.000061.component';
import { My000062Component } from './my.000062.component';
import { My000063Component } from './my.000063.component';
import { My000064Component } from './my.000064.component';

@NgModule({
  declarations: [
    My000059Component,
    My000060Component,
    My000061Component,
    My000062Component,
    My000063Component,
    My000064Component,
  ],
  imports: [CommonModule],
  exports: [
    My000059Component,
  ]
})
export class Module000009 { }
