// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000064',
  templateUrl: './my.000064.component.html'
})
export class My000064Component {
  @Input() parentName = '';
  myName = 'My000064Component';
}
