// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001951Component } from './my.001951.component';
import { My001952Component } from './my.001952.component';
import { My001953Component } from './my.001953.component';
import { My001954Component } from './my.001954.component';
import { My001955Component } from './my.001955.component';
import { My001956Component } from './my.001956.component';
import { My001957Component } from './my.001957.component';
import { My001958Component } from './my.001958.component';

@NgModule({
  declarations: [
    My001951Component,
    My001952Component,
    My001953Component,
    My001954Component,
    My001955Component,
    My001956Component,
    My001957Component,
    My001958Component,
  ],
  imports: [CommonModule],
  exports: [
    My001951Component,
  ]
})
export class Module000243 { }
