// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001463Component } from './my.001463.component';
import { My001464Component } from './my.001464.component';
import { My001465Component } from './my.001465.component';
import { My001466Component } from './my.001466.component';
import { My001467Component } from './my.001467.component';
import { My001468Component } from './my.001468.component';

@NgModule({
  declarations: [
    My001463Component,
    My001464Component,
    My001465Component,
    My001466Component,
    My001467Component,
    My001468Component,
  ],
  imports: [CommonModule],
  exports: [
    My001463Component,
  ]
})
export class Module000243 { }
