// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001468',
  templateUrl: './my.001468.component.html'
})
export class My001468Component {
  @Input() parentName = '';
  myName = 'My001468Component';
}
