// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001955',
  templateUrl: './my.001955.component.html'
})
export class My001955Component {
  @Input() parentName = '';
  myName = 'My001955Component';
}
