// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001467',
  templateUrl: './my.001467.component.html'
})
export class My001467Component {
  @Input() parentName = '';
  myName = 'My001467Component';
}
