// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001956',
  templateUrl: './my.001956.component.html'
})
export class My001956Component {
  @Input() parentName = '';
  myName = 'My001956Component';
}
