// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001466',
  templateUrl: './my.001466.component.html'
})
export class My001466Component {
  @Input() parentName = '';
  myName = 'My001466Component';
}
