// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001958',
  templateUrl: './my.001958.component.html'
})
export class My001958Component {
  @Input() parentName = '';
  myName = 'My001958Component';
}
