// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000009Component } from './my.000009.component';
import { My000010Component } from './my.000010.component';
import { My000011Component } from './my.000011.component';
import { My000012Component } from './my.000012.component';
import { My000013Component } from './my.000013.component';
import { My000014Component } from './my.000014.component';
import { My000015Component } from './my.000015.component';
import { My000016Component } from './my.000016.component';
import { My000017Component } from './my.000017.component';

@NgModule({
  declarations: [
    My000009Component,
    My000010Component,
    My000011Component,
    My000012Component,
    My000013Component,
    My000014Component,
    My000015Component,
    My000016Component,
    My000017Component,
  ],
  imports: [CommonModule],
  exports: [
    My000009Component,
  ]
})
export class Module000001 { }
