// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000007Component } from './my.000007.component';
import { My000008Component } from './my.000008.component';
import { My000009Component } from './my.000009.component';
import { My000010Component } from './my.000010.component';
import { My000011Component } from './my.000011.component';
import { My000012Component } from './my.000012.component';
import { My000013Component } from './my.000013.component';

@NgModule({
  declarations: [
    My000007Component,
    My000008Component,
    My000009Component,
    My000010Component,
    My000011Component,
    My000012Component,
    My000013Component,
  ],
  imports: [CommonModule],
  exports: [
    My000007Component,
  ]
})
export class Module000001 { }
