// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000012',
  templateUrl: './my.000012.component.html'
})
export class My000012Component {
  @Input() parentName = '';
  myName = 'My000012Component';
}
