// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000011',
  templateUrl: './my.000011.component.html'
})
export class My000011Component {
  @Input() parentName = '';
  myName = 'My000011Component';
}
