// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001475Component } from './my.001475.component';
import { My001476Component } from './my.001476.component';
import { My001477Component } from './my.001477.component';
import { My001478Component } from './my.001478.component';
import { My001479Component } from './my.001479.component';
import { My001480Component } from './my.001480.component';

@NgModule({
  declarations: [
    My001475Component,
    My001476Component,
    My001477Component,
    My001478Component,
    My001479Component,
    My001480Component,
  ],
  imports: [CommonModule],
  exports: [
    My001475Component,
  ]
})
export class Module000245 { }
