// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001969',
  templateUrl: './my.001969.component.html'
})
export class My001969Component {
  @Input() parentName = '';
  myName = 'My001969Component';
}
