// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001973',
  templateUrl: './my.001973.component.html'
})
export class My001973Component {
  @Input() parentName = '';
  myName = 'My001973Component';
}
