// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001477',
  templateUrl: './my.001477.component.html'
})
export class My001477Component {
  @Input() parentName = '';
  myName = 'My001477Component';
}
