// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001480',
  templateUrl: './my.001480.component.html'
})
export class My001480Component {
  @Input() parentName = '';
  myName = 'My001480Component';
}
