// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001478',
  templateUrl: './my.001478.component.html'
})
export class My001478Component {
  @Input() parentName = '';
  myName = 'My001478Component';
}
