// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001970',
  templateUrl: './my.001970.component.html'
})
export class My001970Component {
  @Input() parentName = '';
  myName = 'My001970Component';
}
