// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001968',
  templateUrl: './my.001968.component.html'
})
export class My001968Component {
  @Input() parentName = '';
  myName = 'My001968Component';
}
