// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001972',
  templateUrl: './my.001972.component.html'
})
export class My001972Component {
  @Input() parentName = '';
  myName = 'My001972Component';
}
