// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001967',
  templateUrl: './my.001967.component.html'
})
export class My001967Component {
  @Input() parentName = '';
  myName = 'My001967Component';
}
