// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001974',
  templateUrl: './my.001974.component.html'
})
export class My001974Component {
  @Input() parentName = '';
  myName = 'My001974Component';
}
