// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001948',
  templateUrl: './my.001948.component.html'
})
export class My001948Component {
  @Input() parentName = '';
  myName = 'My001948Component';
}
