// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001460',
  templateUrl: './my.001460.component.html'
})
export class My001460Component {
  @Input() parentName = '';
  myName = 'My001460Component';
}
