// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001945',
  templateUrl: './my.001945.component.html'
})
export class My001945Component {
  @Input() parentName = '';
  myName = 'My001945Component';
}
