// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001950',
  templateUrl: './my.001950.component.html'
})
export class My001950Component {
  @Input() parentName = '';
  myName = 'My001950Component';
}
