// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001946',
  templateUrl: './my.001946.component.html'
})
export class My001946Component {
  @Input() parentName = '';
  myName = 'My001946Component';
}
