// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001943',
  templateUrl: './my.001943.component.html'
})
export class My001943Component {
  @Input() parentName = '';
  myName = 'My001943Component';
}
