// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000215Component } from './my.000215.component';
import { My000216Component } from './my.000216.component';
import { My000217Component } from './my.000217.component';
import { My000218Component } from './my.000218.component';
import { My000219Component } from './my.000219.component';
import { My000220Component } from './my.000220.component';
import { My000221Component } from './my.000221.component';
import { My000222Component } from './my.000222.component';

@NgModule({
  declarations: [
    My000215Component,
    My000216Component,
    My000217Component,
    My000218Component,
    My000219Component,
    My000220Component,
    My000221Component,
    My000222Component,
  ],
  imports: [CommonModule],
  exports: [
    My000215Component,
  ]
})
export class Module000026 { }
