// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000161Component } from './my.000161.component';
import { My000162Component } from './my.000162.component';
import { My000163Component } from './my.000163.component';
import { My000164Component } from './my.000164.component';
import { My000165Component } from './my.000165.component';
import { My000166Component } from './my.000166.component';

@NgModule({
  declarations: [
    My000161Component,
    My000162Component,
    My000163Component,
    My000164Component,
    My000165Component,
    My000166Component,
  ],
  imports: [CommonModule],
  exports: [
    My000161Component,
  ]
})
export class Module000026 { }
