// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000166',
  templateUrl: './my.000166.component.html'
})
export class My000166Component {
  @Input() parentName = '';
  myName = 'My000166Component';
}
