// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000476Component } from './my.000476.component';
import { My000477Component } from './my.000477.component';
import { My000478Component } from './my.000478.component';
import { My000479Component } from './my.000479.component';
import { My000480Component } from './my.000480.component';
import { My000481Component } from './my.000481.component';
import { My000482Component } from './my.000482.component';

@NgModule({
  declarations: [
    My000476Component,
    My000477Component,
    My000478Component,
    My000479Component,
    My000480Component,
    My000481Component,
    My000482Component,
  ],
  imports: [CommonModule],
  exports: [
    My000476Component,
  ]
})
export class Module000068 { }
