// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001439Component } from './my.001439.component';
import { My001440Component } from './my.001440.component';
import { My001441Component } from './my.001441.component';
import { My001442Component } from './my.001442.component';
import { My001443Component } from './my.001443.component';
import { My001444Component } from './my.001444.component';

@NgModule({
  declarations: [
    My001439Component,
    My001440Component,
    My001441Component,
    My001442Component,
    My001443Component,
    My001444Component,
  ],
  imports: [CommonModule],
  exports: [
    My001439Component,
  ]
})
export class Module000239 { }
