// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001919',
  templateUrl: './my.001919.component.html'
})
export class My001919Component {
  @Input() parentName = '';
  myName = 'My001919Component';
}
