// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001923',
  templateUrl: './my.001923.component.html'
})
export class My001923Component {
  @Input() parentName = '';
  myName = 'My001923Component';
}
