// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001921',
  templateUrl: './my.001921.component.html'
})
export class My001921Component {
  @Input() parentName = '';
  myName = 'My001921Component';
}
