// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001922',
  templateUrl: './my.001922.component.html'
})
export class My001922Component {
  @Input() parentName = '';
  myName = 'My001922Component';
}
