// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001924',
  templateUrl: './my.001924.component.html'
})
export class My001924Component {
  @Input() parentName = '';
  myName = 'My001924Component';
}
