// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001926',
  templateUrl: './my.001926.component.html'
})
export class My001926Component {
  @Input() parentName = '';
  myName = 'My001926Component';
}
