// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001439',
  templateUrl: './my.001439.component.html'
})
export class My001439Component {
  @Input() parentName = '';
  myName = 'My001439Component';
}
