// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001925',
  templateUrl: './my.001925.component.html'
})
export class My001925Component {
  @Input() parentName = '';
  myName = 'My001925Component';
}
