// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001443',
  templateUrl: './my.001443.component.html'
})
export class My001443Component {
  @Input() parentName = '';
  myName = 'My001443Component';
}
