// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001109Component } from './my.001109.component';
import { My001110Component } from './my.001110.component';
import { My001111Component } from './my.001111.component';
import { My001112Component } from './my.001112.component';
import { My001113Component } from './my.001113.component';
import { My001114Component } from './my.001114.component';

@NgModule({
  declarations: [
    My001109Component,
    My001110Component,
    My001111Component,
    My001112Component,
    My001113Component,
    My001114Component,
  ],
  imports: [CommonModule],
  exports: [
    My001109Component,
  ]
})
export class Module000184 { }
