// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001479Component } from './my.001479.component';
import { My001480Component } from './my.001480.component';
import { My001481Component } from './my.001481.component';
import { My001482Component } from './my.001482.component';
import { My001483Component } from './my.001483.component';
import { My001484Component } from './my.001484.component';
import { My001485Component } from './my.001485.component';
import { My001486Component } from './my.001486.component';

@NgModule({
  declarations: [
    My001479Component,
    My001480Component,
    My001481Component,
    My001482Component,
    My001483Component,
    My001484Component,
    My001485Component,
    My001486Component,
  ],
  imports: [CommonModule],
  exports: [
    My001479Component,
  ]
})
export class Module000184 { }
