// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001486',
  templateUrl: './my.001486.component.html'
})
export class My001486Component {
  @Input() parentName = '';
  myName = 'My001486Component';
}
