// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001483',
  templateUrl: './my.001483.component.html'
})
export class My001483Component {
  @Input() parentName = '';
  myName = 'My001483Component';
}
