// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000999Component } from './my.000999.component';
import { My001000Component } from './my.001000.component';
import { My001001Component } from './my.001001.component';
import { My001002Component } from './my.001002.component';
import { My001003Component } from './my.001003.component';
import { My001004Component } from './my.001004.component';
import { My001005Component } from './my.001005.component';
import { My001006Component } from './my.001006.component';

@NgModule({
  declarations: [
    My000999Component,
    My001000Component,
    My001001Component,
    My001002Component,
    My001003Component,
    My001004Component,
    My001005Component,
    My001006Component,
  ],
  imports: [CommonModule],
  exports: [
    My000999Component,
  ]
})
export class Module000124 { }
