// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000849Component } from './my.000849.component';
import { My000850Component } from './my.000850.component';
import { My000851Component } from './my.000851.component';
import { My000852Component } from './my.000852.component';
import { My000853Component } from './my.000853.component';
import { My000854Component } from './my.000854.component';

@NgModule({
  declarations: [
    My000849Component,
    My000850Component,
    My000851Component,
    My000852Component,
    My000853Component,
    My000854Component,
  ],
  imports: [CommonModule],
  exports: [
    My000849Component,
  ]
})
export class Module000124 { }
