// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000754',
  templateUrl: './my.000754.component.html'
})
export class My000754Component {
  @Input() parentName = '';
  myName = 'My000754Component';
}
