// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001004',
  templateUrl: './my.001004.component.html'
})
export class My001004Component {
  @Input() parentName = '';
  myName = 'My001004Component';
}
