// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000341Component } from './my.000341.component';
import { My000342Component } from './my.000342.component';
import { My000343Component } from './my.000343.component';
import { My000344Component } from './my.000344.component';
import { My000345Component } from './my.000345.component';
import { My000346Component } from './my.000346.component';

@NgModule({
  declarations: [
    My000341Component,
    My000342Component,
    My000343Component,
    My000344Component,
    My000345Component,
    My000346Component,
  ],
  imports: [CommonModule],
  exports: [
    My000341Component,
  ]
})
export class Module000056 { }
