// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000983Component } from './my.000983.component';
import { My000984Component } from './my.000984.component';
import { My000985Component } from './my.000985.component';
import { My000986Component } from './my.000986.component';
import { My000987Component } from './my.000987.component';
import { My000988Component } from './my.000988.component';

@NgModule({
  declarations: [
    My000983Component,
    My000984Component,
    My000985Component,
    My000986Component,
    My000987Component,
    My000988Component,
  ],
  imports: [CommonModule],
  exports: [
    My000983Component,
  ]
})
export class Module000163 { }
