// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001311Component } from './my.001311.component';
import { My001312Component } from './my.001312.component';
import { My001313Component } from './my.001313.component';
import { My001314Component } from './my.001314.component';
import { My001315Component } from './my.001315.component';
import { My001316Component } from './my.001316.component';
import { My001317Component } from './my.001317.component';
import { My001318Component } from './my.001318.component';

@NgModule({
  declarations: [
    My001311Component,
    My001312Component,
    My001313Component,
    My001314Component,
    My001315Component,
    My001316Component,
    My001317Component,
    My001318Component,
  ],
  imports: [CommonModule],
  exports: [
    My001311Component,
  ]
})
export class Module000163 { }
