// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001312',
  templateUrl: './my.001312.component.html'
})
export class My001312Component {
  @Input() parentName = '';
  myName = 'My001312Component';
}
