// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001317',
  templateUrl: './my.001317.component.html'
})
export class My001317Component {
  @Input() parentName = '';
  myName = 'My001317Component';
}
