// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001313',
  templateUrl: './my.001313.component.html'
})
export class My001313Component {
  @Input() parentName = '';
  myName = 'My001313Component';
}
