// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001314',
  templateUrl: './my.001314.component.html'
})
export class My001314Component {
  @Input() parentName = '';
  myName = 'My001314Component';
}
