// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001318',
  templateUrl: './my.001318.component.html'
})
export class My001318Component {
  @Input() parentName = '';
  myName = 'My001318Component';
}
