// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001311',
  templateUrl: './my.001311.component.html'
})
export class My001311Component {
  @Input() parentName = '';
  myName = 'My001311Component';
}
