// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001316',
  templateUrl: './my.001316.component.html'
})
export class My001316Component {
  @Input() parentName = '';
  myName = 'My001316Component';
}
