// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000641Component } from './my.000641.component';
import { My000642Component } from './my.000642.component';
import { My000643Component } from './my.000643.component';
import { My000644Component } from './my.000644.component';
import { My000645Component } from './my.000645.component';
import { My000646Component } from './my.000646.component';

@NgModule({
  declarations: [
    My000641Component,
    My000642Component,
    My000643Component,
    My000644Component,
    My000645Component,
    My000646Component,
  ],
  imports: [CommonModule],
  exports: [
    My000641Component,
  ]
})
export class Module000106 { }
