// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001527Component } from './my.001527.component';
import { My001528Component } from './my.001528.component';
import { My001529Component } from './my.001529.component';
import { My001530Component } from './my.001530.component';
import { My001531Component } from './my.001531.component';
import { My001532Component } from './my.001532.component';
import { My001533Component } from './my.001533.component';
import { My001534Component } from './my.001534.component';

@NgModule({
  declarations: [
    My001527Component,
    My001528Component,
    My001529Component,
    My001530Component,
    My001531Component,
    My001532Component,
    My001533Component,
    My001534Component,
  ],
  imports: [CommonModule],
  exports: [
    My001527Component,
  ]
})
export class Module000190 { }
