// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001531',
  templateUrl: './my.001531.component.html'
})
export class My001531Component {
  @Input() parentName = '';
  myName = 'My001531Component';
}
