// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001527',
  templateUrl: './my.001527.component.html'
})
export class My001527Component {
  @Input() parentName = '';
  myName = 'My001527Component';
}
