// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001532',
  templateUrl: './my.001532.component.html'
})
export class My001532Component {
  @Input() parentName = '';
  myName = 'My001532Component';
}
