// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000065Component } from './my.000065.component';
import { My000066Component } from './my.000066.component';
import { My000067Component } from './my.000067.component';
import { My000068Component } from './my.000068.component';
import { My000069Component } from './my.000069.component';
import { My000070Component } from './my.000070.component';

@NgModule({
  declarations: [
    My000065Component,
    My000066Component,
    My000067Component,
    My000068Component,
    My000069Component,
    My000070Component,
  ],
  imports: [CommonModule],
  exports: [
    My000065Component,
  ]
})
export class Module000010 { }
