// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000098Component } from './my.000098.component';
import { My000099Component } from './my.000099.component';
import { My000100Component } from './my.000100.component';
import { My000101Component } from './my.000101.component';
import { My000102Component } from './my.000102.component';
import { My000103Component } from './my.000103.component';
import { My000104Component } from './my.000104.component';

@NgModule({
  declarations: [
    My000098Component,
    My000099Component,
    My000100Component,
    My000101Component,
    My000102Component,
    My000103Component,
    My000104Component,
  ],
  imports: [CommonModule],
  exports: [
    My000098Component,
  ]
})
export class Module000014 { }
