// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000100',
  templateUrl: './my.000100.component.html'
})
export class My000100Component {
  @Input() parentName = '';
  myName = 'My000100Component';
}
