// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001043Component } from './my.001043.component';
import { My001044Component } from './my.001044.component';
import { My001045Component } from './my.001045.component';
import { My001046Component } from './my.001046.component';
import { My001047Component } from './my.001047.component';
import { My001048Component } from './my.001048.component';

@NgModule({
  declarations: [
    My001043Component,
    My001044Component,
    My001045Component,
    My001046Component,
    My001047Component,
    My001048Component,
  ],
  imports: [CommonModule],
  exports: [
    My001043Component,
  ]
})
export class Module000173 { }
