// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001393',
  templateUrl: './my.001393.component.html'
})
export class My001393Component {
  @Input() parentName = '';
  myName = 'My001393Component';
}
