// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000257Component } from './my.000257.component';
import { My000258Component } from './my.000258.component';
import { My000259Component } from './my.000259.component';
import { My000260Component } from './my.000260.component';
import { My000261Component } from './my.000261.component';
import { My000262Component } from './my.000262.component';

@NgModule({
  declarations: [
    My000257Component,
    My000258Component,
    My000259Component,
    My000260Component,
    My000261Component,
    My000262Component,
  ],
  imports: [CommonModule],
  exports: [
    My000257Component,
  ]
})
export class Module000042 { }
