// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000343Component } from './my.000343.component';
import { My000344Component } from './my.000344.component';
import { My000345Component } from './my.000345.component';
import { My000346Component } from './my.000346.component';
import { My000347Component } from './my.000347.component';
import { My000348Component } from './my.000348.component';
import { My000349Component } from './my.000349.component';
import { My000350Component } from './my.000350.component';

@NgModule({
  declarations: [
    My000343Component,
    My000344Component,
    My000345Component,
    My000346Component,
    My000347Component,
    My000348Component,
    My000349Component,
    My000350Component,
  ],
  imports: [CommonModule],
  exports: [
    My000343Component,
  ]
})
export class Module000042 { }
