// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000294Component } from './my.000294.component';
import { My000295Component } from './my.000295.component';
import { My000296Component } from './my.000296.component';
import { My000297Component } from './my.000297.component';
import { My000298Component } from './my.000298.component';
import { My000299Component } from './my.000299.component';
import { My000300Component } from './my.000300.component';

@NgModule({
  declarations: [
    My000294Component,
    My000295Component,
    My000296Component,
    My000297Component,
    My000298Component,
    My000299Component,
    My000300Component,
  ],
  imports: [CommonModule],
  exports: [
    My000294Component,
  ]
})
export class Module000042 { }
