// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000631Component } from './my.000631.component';
import { My000632Component } from './my.000632.component';
import { My000633Component } from './my.000633.component';
import { My000634Component } from './my.000634.component';
import { My000635Component } from './my.000635.component';
import { My000636Component } from './my.000636.component';
import { My000637Component } from './my.000637.component';
import { My000638Component } from './my.000638.component';

@NgModule({
  declarations: [
    My000631Component,
    My000632Component,
    My000633Component,
    My000634Component,
    My000635Component,
    My000636Component,
    My000637Component,
    My000638Component,
  ],
  imports: [CommonModule],
  exports: [
    My000631Component,
  ]
})
export class Module000078 { }
