// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000207Component } from './my.000207.component';
import { My000208Component } from './my.000208.component';
import { My000209Component } from './my.000209.component';
import { My000210Component } from './my.000210.component';
import { My000211Component } from './my.000211.component';
import { My000212Component } from './my.000212.component';
import { My000213Component } from './my.000213.component';
import { My000214Component } from './my.000214.component';

@NgModule({
  declarations: [
    My000207Component,
    My000208Component,
    My000209Component,
    My000210Component,
    My000211Component,
    My000212Component,
    My000213Component,
    My000214Component,
  ],
  imports: [CommonModule],
  exports: [
    My000207Component,
  ]
})
export class Module000025 { }
