// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001272',
  templateUrl: './my.001272.component.html'
})
export class My001272Component {
  @Input() parentName = '';
  myName = 'My001272Component';
}
