// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001271',
  templateUrl: './my.001271.component.html'
})
export class My001271Component {
  @Input() parentName = '';
  myName = 'My001271Component';
}
