// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001278',
  templateUrl: './my.001278.component.html'
})
export class My001278Component {
  @Input() parentName = '';
  myName = 'My001278Component';
}
