// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001575Component } from './my.001575.component';
import { My001576Component } from './my.001576.component';
import { My001577Component } from './my.001577.component';
import { My001578Component } from './my.001578.component';
import { My001579Component } from './my.001579.component';
import { My001580Component } from './my.001580.component';
import { My001581Component } from './my.001581.component';
import { My001582Component } from './my.001582.component';

@NgModule({
  declarations: [
    My001575Component,
    My001576Component,
    My001577Component,
    My001578Component,
    My001579Component,
    My001580Component,
    My001581Component,
    My001582Component,
  ],
  imports: [CommonModule],
  exports: [
    My001575Component,
  ]
})
export class Module000196 { }
