// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001578',
  templateUrl: './my.001578.component.html'
})
export class My001578Component {
  @Input() parentName = '';
  myName = 'My001578Component';
}
