// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001581',
  templateUrl: './my.001581.component.html'
})
export class My001581Component {
  @Input() parentName = '';
  myName = 'My001581Component';
}
