// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001576',
  templateUrl: './my.001576.component.html'
})
export class My001576Component {
  @Input() parentName = '';
  myName = 'My001576Component';
}
