// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001582',
  templateUrl: './my.001582.component.html'
})
export class My001582Component {
  @Input() parentName = '';
  myName = 'My001582Component';
}
