// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001265Component } from './my.001265.component';
import { My001266Component } from './my.001266.component';
import { My001267Component } from './my.001267.component';
import { My001268Component } from './my.001268.component';
import { My001269Component } from './my.001269.component';
import { My001270Component } from './my.001270.component';

@NgModule({
  declarations: [
    My001265Component,
    My001266Component,
    My001267Component,
    My001268Component,
    My001269Component,
    My001270Component,
  ],
  imports: [CommonModule],
  exports: [
    My001265Component,
  ]
})
export class Module000210 { }
