// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001687Component } from './my.001687.component';
import { My001688Component } from './my.001688.component';
import { My001689Component } from './my.001689.component';
import { My001690Component } from './my.001690.component';
import { My001691Component } from './my.001691.component';
import { My001692Component } from './my.001692.component';
import { My001693Component } from './my.001693.component';
import { My001694Component } from './my.001694.component';

@NgModule({
  declarations: [
    My001687Component,
    My001688Component,
    My001689Component,
    My001690Component,
    My001691Component,
    My001692Component,
    My001693Component,
    My001694Component,
  ],
  imports: [CommonModule],
  exports: [
    My001687Component,
  ]
})
export class Module000210 { }
