// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001687',
  templateUrl: './my.001687.component.html'
})
export class My001687Component {
  @Input() parentName = '';
  myName = 'My001687Component';
}
