// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001689',
  templateUrl: './my.001689.component.html'
})
export class My001689Component {
  @Input() parentName = '';
  myName = 'My001689Component';
}
