// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001690',
  templateUrl: './my.001690.component.html'
})
export class My001690Component {
  @Input() parentName = '';
  myName = 'My001690Component';
}
