// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001692',
  templateUrl: './my.001692.component.html'
})
export class My001692Component {
  @Input() parentName = '';
  myName = 'My001692Component';
}
