// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001268',
  templateUrl: './my.001268.component.html'
})
export class My001268Component {
  @Input() parentName = '';
  myName = 'My001268Component';
}
