// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001269',
  templateUrl: './my.001269.component.html'
})
export class My001269Component {
  @Input() parentName = '';
  myName = 'My001269Component';
}
