// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001391Component } from './my.001391.component';
import { My001392Component } from './my.001392.component';
import { My001393Component } from './my.001393.component';
import { My001394Component } from './my.001394.component';
import { My001395Component } from './my.001395.component';
import { My001396Component } from './my.001396.component';

@NgModule({
  declarations: [
    My001391Component,
    My001392Component,
    My001393Component,
    My001394Component,
    My001395Component,
    My001396Component,
  ],
  imports: [CommonModule],
  exports: [
    My001391Component,
  ]
})
export class Module000231 { }
