// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001857',
  templateUrl: './my.001857.component.html'
})
export class My001857Component {
  @Input() parentName = '';
  myName = 'My001857Component';
}
