// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001859',
  templateUrl: './my.001859.component.html'
})
export class My001859Component {
  @Input() parentName = '';
  myName = 'My001859Component';
}
