// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001860',
  templateUrl: './my.001860.component.html'
})
export class My001860Component {
  @Input() parentName = '';
  myName = 'My001860Component';
}
