// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001862',
  templateUrl: './my.001862.component.html'
})
export class My001862Component {
  @Input() parentName = '';
  myName = 'My001862Component';
}
