// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001858',
  templateUrl: './my.001858.component.html'
})
export class My001858Component {
  @Input() parentName = '';
  myName = 'My001858Component';
}
