// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001861',
  templateUrl: './my.001861.component.html'
})
export class My001861Component {
  @Input() parentName = '';
  myName = 'My001861Component';
}
