// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001239Component } from './my.001239.component';
import { My001240Component } from './my.001240.component';
import { My001241Component } from './my.001241.component';
import { My001242Component } from './my.001242.component';
import { My001243Component } from './my.001243.component';
import { My001244Component } from './my.001244.component';
import { My001245Component } from './my.001245.component';
import { My001246Component } from './my.001246.component';

@NgModule({
  declarations: [
    My001239Component,
    My001240Component,
    My001241Component,
    My001242Component,
    My001243Component,
    My001244Component,
    My001245Component,
    My001246Component,
  ],
  imports: [CommonModule],
  exports: [
    My001239Component,
  ]
})
export class Module000154 { }
