// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001246',
  templateUrl: './my.001246.component.html'
})
export class My001246Component {
  @Input() parentName = '';
  myName = 'My001246Component';
}
