// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001241',
  templateUrl: './my.001241.component.html'
})
export class My001241Component {
  @Input() parentName = '';
  myName = 'My001241Component';
}
