// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001245',
  templateUrl: './my.001245.component.html'
})
export class My001245Component {
  @Input() parentName = '';
  myName = 'My001245Component';
}
