// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001244',
  templateUrl: './my.001244.component.html'
})
export class My001244Component {
  @Input() parentName = '';
  myName = 'My001244Component';
}
