// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001243',
  templateUrl: './my.001243.component.html'
})
export class My001243Component {
  @Input() parentName = '';
  myName = 'My001243Component';
}
