// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001240',
  templateUrl: './my.001240.component.html'
})
export class My001240Component {
  @Input() parentName = '';
  myName = 'My001240Component';
}
