// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000711Component } from './my.000711.component';
import { My000712Component } from './my.000712.component';
import { My000713Component } from './my.000713.component';
import { My000714Component } from './my.000714.component';
import { My000715Component } from './my.000715.component';
import { My000716Component } from './my.000716.component';
import { My000717Component } from './my.000717.component';
import { My000718Component } from './my.000718.component';

@NgModule({
  declarations: [
    My000711Component,
    My000712Component,
    My000713Component,
    My000714Component,
    My000715Component,
    My000716Component,
    My000717Component,
    My000718Component,
  ],
  imports: [CommonModule],
  exports: [
    My000711Component,
  ]
})
export class Module000088 { }
