// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000616Component } from './my.000616.component';
import { My000617Component } from './my.000617.component';
import { My000618Component } from './my.000618.component';
import { My000619Component } from './my.000619.component';
import { My000620Component } from './my.000620.component';
import { My000621Component } from './my.000621.component';
import { My000622Component } from './my.000622.component';

@NgModule({
  declarations: [
    My000616Component,
    My000617Component,
    My000618Component,
    My000619Component,
    My000620Component,
    My000621Component,
    My000622Component,
  ],
  imports: [CommonModule],
  exports: [
    My000616Component,
  ]
})
export class Module000088 { }
