// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000716',
  templateUrl: './my.000716.component.html'
})
export class My000716Component {
  @Input() parentName = '';
  myName = 'My000716Component';
}
