// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000837Component } from './my.000837.component';
import { My000838Component } from './my.000838.component';
import { My000839Component } from './my.000839.component';
import { My000840Component } from './my.000840.component';
import { My000841Component } from './my.000841.component';
import { My000842Component } from './my.000842.component';

@NgModule({
  declarations: [
    My000837Component,
    My000838Component,
    My000839Component,
    My000840Component,
    My000841Component,
    My000842Component,
  ],
  imports: [CommonModule],
  exports: [
    My000837Component,
  ]
})
export class Module000122 { }
