// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000975Component } from './my.000975.component';
import { My000976Component } from './my.000976.component';
import { My000977Component } from './my.000977.component';
import { My000978Component } from './my.000978.component';
import { My000979Component } from './my.000979.component';
import { My000980Component } from './my.000980.component';

@NgModule({
  declarations: [
    My000975Component,
    My000976Component,
    My000977Component,
    My000978Component,
    My000979Component,
    My000980Component,
  ],
  imports: [CommonModule],
  exports: [
    My000975Component,
  ]
})
export class Module000145 { }
