// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000875Component } from './my.000875.component';
import { My000876Component } from './my.000876.component';
import { My000877Component } from './my.000877.component';
import { My000878Component } from './my.000878.component';
import { My000879Component } from './my.000879.component';
import { My000880Component } from './my.000880.component';

@NgModule({
  declarations: [
    My000875Component,
    My000876Component,
    My000877Component,
    My000878Component,
    My000879Component,
    My000880Component,
  ],
  imports: [CommonModule],
  exports: [
    My000875Component,
  ]
})
export class Module000145 { }
