// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000935Component } from './my.000935.component';
import { My000936Component } from './my.000936.component';
import { My000937Component } from './my.000937.component';
import { My000938Component } from './my.000938.component';
import { My000939Component } from './my.000939.component';
import { My000940Component } from './my.000940.component';

@NgModule({
  declarations: [
    My000935Component,
    My000936Component,
    My000937Component,
    My000938Component,
    My000939Component,
    My000940Component,
  ],
  imports: [CommonModule],
  exports: [
    My000935Component,
  ]
})
export class Module000155 { }
