// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001247Component } from './my.001247.component';
import { My001248Component } from './my.001248.component';
import { My001249Component } from './my.001249.component';
import { My001250Component } from './my.001250.component';
import { My001251Component } from './my.001251.component';
import { My001252Component } from './my.001252.component';
import { My001253Component } from './my.001253.component';
import { My001254Component } from './my.001254.component';

@NgModule({
  declarations: [
    My001247Component,
    My001248Component,
    My001249Component,
    My001250Component,
    My001251Component,
    My001252Component,
    My001253Component,
    My001254Component,
  ],
  imports: [CommonModule],
  exports: [
    My001247Component,
  ]
})
export class Module000155 { }
