// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000938',
  templateUrl: './my.000938.component.html'
})
export class My000938Component {
  @Input() parentName = '';
  myName = 'My000938Component';
}
