// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000939',
  templateUrl: './my.000939.component.html'
})
export class My000939Component {
  @Input() parentName = '';
  myName = 'My000939Component';
}
