// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001254',
  templateUrl: './my.001254.component.html'
})
export class My001254Component {
  @Input() parentName = '';
  myName = 'My001254Component';
}
