// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001252',
  templateUrl: './my.001252.component.html'
})
export class My001252Component {
  @Input() parentName = '';
  myName = 'My001252Component';
}
