// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001248',
  templateUrl: './my.001248.component.html'
})
export class My001248Component {
  @Input() parentName = '';
  myName = 'My001248Component';
}
