// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001365',
  templateUrl: './my.001365.component.html'
})
export class My001365Component {
  @Input() parentName = '';
  myName = 'My001365Component';
}
