// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001362',
  templateUrl: './my.001362.component.html'
})
export class My001362Component {
  @Input() parentName = '';
  myName = 'My001362Component';
}
