// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001361',
  templateUrl: './my.001361.component.html'
})
export class My001361Component {
  @Input() parentName = '';
  myName = 'My001361Component';
}
