// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001169Component } from './my.001169.component';
import { My001170Component } from './my.001170.component';
import { My001171Component } from './my.001171.component';
import { My001172Component } from './my.001172.component';
import { My001173Component } from './my.001173.component';
import { My001174Component } from './my.001174.component';

@NgModule({
  declarations: [
    My001169Component,
    My001170Component,
    My001171Component,
    My001172Component,
    My001173Component,
    My001174Component,
  ],
  imports: [CommonModule],
  exports: [
    My001169Component,
  ]
})
export class Module000194 { }
