// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001561',
  templateUrl: './my.001561.component.html'
})
export class My001561Component {
  @Input() parentName = '';
  myName = 'My001561Component';
}
