// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001564',
  templateUrl: './my.001564.component.html'
})
export class My001564Component {
  @Input() parentName = '';
  myName = 'My001564Component';
}
