// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001560',
  templateUrl: './my.001560.component.html'
})
export class My001560Component {
  @Input() parentName = '';
  myName = 'My001560Component';
}
