// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001559',
  templateUrl: './my.001559.component.html'
})
export class My001559Component {
  @Input() parentName = '';
  myName = 'My001559Component';
}
