// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001563',
  templateUrl: './my.001563.component.html'
})
export class My001563Component {
  @Input() parentName = '';
  myName = 'My001563Component';
}
