// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001562',
  templateUrl: './my.001562.component.html'
})
export class My001562Component {
  @Input() parentName = '';
  myName = 'My001562Component';
}
