// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001566',
  templateUrl: './my.001566.component.html'
})
export class My001566Component {
  @Input() parentName = '';
  myName = 'My001566Component';
}
