// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000628',
  templateUrl: './my.000628.component.html'
})
export class My000628Component {
  @Input() parentName = '';
  myName = 'My000628Component';
}
