// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000542',
  templateUrl: './my.000542.component.html'
})
export class My000542Component {
  @Input() parentName = '';
  myName = 'My000542Component';
}
