// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000905Component } from './my.000905.component';
import { My000906Component } from './my.000906.component';
import { My000907Component } from './my.000907.component';
import { My000908Component } from './my.000908.component';
import { My000909Component } from './my.000909.component';
import { My000910Component } from './my.000910.component';

@NgModule({
  declarations: [
    My000905Component,
    My000906Component,
    My000907Component,
    My000908Component,
    My000909Component,
    My000910Component,
  ],
  imports: [CommonModule],
  exports: [
    My000905Component,
  ]
})
export class Module000150 { }
