// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001207Component } from './my.001207.component';
import { My001208Component } from './my.001208.component';
import { My001209Component } from './my.001209.component';
import { My001210Component } from './my.001210.component';
import { My001211Component } from './my.001211.component';
import { My001212Component } from './my.001212.component';
import { My001213Component } from './my.001213.component';
import { My001214Component } from './my.001214.component';

@NgModule({
  declarations: [
    My001207Component,
    My001208Component,
    My001209Component,
    My001210Component,
    My001211Component,
    My001212Component,
    My001213Component,
    My001214Component,
  ],
  imports: [CommonModule],
  exports: [
    My001207Component,
  ]
})
export class Module000150 { }
