// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001213',
  templateUrl: './my.001213.component.html'
})
export class My001213Component {
  @Input() parentName = '';
  myName = 'My001213Component';
}
