// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000797Component } from './my.000797.component';
import { My000798Component } from './my.000798.component';
import { My000799Component } from './my.000799.component';
import { My000800Component } from './my.000800.component';
import { My000801Component } from './my.000801.component';
import { My000802Component } from './my.000802.component';

@NgModule({
  declarations: [
    My000797Component,
    My000798Component,
    My000799Component,
    My000800Component,
    My000801Component,
    My000802Component,
  ],
  imports: [CommonModule],
  exports: [
    My000797Component,
  ]
})
export class Module000132 { }
