// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000897Component } from './my.000897.component';
import { My000898Component } from './my.000898.component';
import { My000899Component } from './my.000899.component';
import { My000900Component } from './my.000900.component';
import { My000901Component } from './my.000901.component';
import { My000902Component } from './my.000902.component';

@NgModule({
  declarations: [
    My000897Component,
    My000898Component,
    My000899Component,
    My000900Component,
    My000901Component,
    My000902Component,
  ],
  imports: [CommonModule],
  exports: [
    My000897Component,
  ]
})
export class Module000132 { }
