// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000466',
  templateUrl: './my.000466.component.html'
})
export class My000466Component {
  @Input() parentName = '';
  myName = 'My000466Component';
}
