// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001549',
  templateUrl: './my.001549.component.html'
})
export class My001549Component {
  @Input() parentName = '';
  myName = 'My001549Component';
}
