// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001543',
  templateUrl: './my.001543.component.html'
})
export class My001543Component {
  @Input() parentName = '';
  myName = 'My001543Component';
}
