// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001544',
  templateUrl: './my.001544.component.html'
})
export class My001544Component {
  @Input() parentName = '';
  myName = 'My001544Component';
}
