// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001548',
  templateUrl: './my.001548.component.html'
})
export class My001548Component {
  @Input() parentName = '';
  myName = 'My001548Component';
}
