// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001550',
  templateUrl: './my.001550.component.html'
})
export class My001550Component {
  @Input() parentName = '';
  myName = 'My001550Component';
}
