// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000140Component } from './my.000140.component';
import { My000141Component } from './my.000141.component';
import { My000142Component } from './my.000142.component';
import { My000143Component } from './my.000143.component';
import { My000144Component } from './my.000144.component';
import { My000145Component } from './my.000145.component';
import { My000146Component } from './my.000146.component';

@NgModule({
  declarations: [
    My000140Component,
    My000141Component,
    My000142Component,
    My000143Component,
    My000144Component,
    My000145Component,
    My000146Component,
  ],
  imports: [CommonModule],
  exports: [
    My000140Component,
  ]
})
export class Module000020 { }
