// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000125Component } from './my.000125.component';
import { My000126Component } from './my.000126.component';
import { My000127Component } from './my.000127.component';
import { My000128Component } from './my.000128.component';
import { My000129Component } from './my.000129.component';
import { My000130Component } from './my.000130.component';

@NgModule({
  declarations: [
    My000125Component,
    My000126Component,
    My000127Component,
    My000128Component,
    My000129Component,
    My000130Component,
  ],
  imports: [CommonModule],
  exports: [
    My000125Component,
  ]
})
export class Module000020 { }
