// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000167Component } from './my.000167.component';
import { My000168Component } from './my.000168.component';
import { My000169Component } from './my.000169.component';
import { My000170Component } from './my.000170.component';
import { My000171Component } from './my.000171.component';
import { My000172Component } from './my.000172.component';
import { My000173Component } from './my.000173.component';
import { My000174Component } from './my.000174.component';

@NgModule({
  declarations: [
    My000167Component,
    My000168Component,
    My000169Component,
    My000170Component,
    My000171Component,
    My000172Component,
    My000173Component,
    My000174Component,
  ],
  imports: [CommonModule],
  exports: [
    My000167Component,
  ]
})
export class Module000020 { }
