// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000168',
  templateUrl: './my.000168.component.html'
})
export class My000168Component {
  @Input() parentName = '';
  myName = 'My000168Component';
}
