// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000527Component } from './my.000527.component';
import { My000528Component } from './my.000528.component';
import { My000529Component } from './my.000529.component';
import { My000530Component } from './my.000530.component';
import { My000531Component } from './my.000531.component';
import { My000532Component } from './my.000532.component';
import { My000533Component } from './my.000533.component';
import { My000534Component } from './my.000534.component';

@NgModule({
  declarations: [
    My000527Component,
    My000528Component,
    My000529Component,
    My000530Component,
    My000531Component,
    My000532Component,
    My000533Component,
    My000534Component,
  ],
  imports: [CommonModule],
  exports: [
    My000527Component,
  ]
})
export class Module000065 { }
