// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000395Component } from './my.000395.component';
import { My000396Component } from './my.000396.component';
import { My000397Component } from './my.000397.component';
import { My000398Component } from './my.000398.component';
import { My000399Component } from './my.000399.component';
import { My000400Component } from './my.000400.component';

@NgModule({
  declarations: [
    My000395Component,
    My000396Component,
    My000397Component,
    My000398Component,
    My000399Component,
    My000400Component,
  ],
  imports: [CommonModule],
  exports: [
    My000395Component,
  ]
})
export class Module000065 { }
