// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001229Component } from './my.001229.component';
import { My001230Component } from './my.001230.component';
import { My001231Component } from './my.001231.component';
import { My001232Component } from './my.001232.component';
import { My001233Component } from './my.001233.component';
import { My001234Component } from './my.001234.component';

@NgModule({
  declarations: [
    My001229Component,
    My001230Component,
    My001231Component,
    My001232Component,
    My001233Component,
    My001234Component,
  ],
  imports: [CommonModule],
  exports: [
    My001229Component,
  ]
})
export class Module000204 { }
