// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001639Component } from './my.001639.component';
import { My001640Component } from './my.001640.component';
import { My001641Component } from './my.001641.component';
import { My001642Component } from './my.001642.component';
import { My001643Component } from './my.001643.component';
import { My001644Component } from './my.001644.component';
import { My001645Component } from './my.001645.component';
import { My001646Component } from './my.001646.component';

@NgModule({
  declarations: [
    My001639Component,
    My001640Component,
    My001641Component,
    My001642Component,
    My001643Component,
    My001644Component,
    My001645Component,
    My001646Component,
  ],
  imports: [CommonModule],
  exports: [
    My001639Component,
  ]
})
export class Module000204 { }
