// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001639',
  templateUrl: './my.001639.component.html'
})
export class My001639Component {
  @Input() parentName = '';
  myName = 'My001639Component';
}
