// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001234',
  templateUrl: './my.001234.component.html'
})
export class My001234Component {
  @Input() parentName = '';
  myName = 'My001234Component';
}
