// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001645',
  templateUrl: './my.001645.component.html'
})
export class My001645Component {
  @Input() parentName = '';
  myName = 'My001645Component';
}
