// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001231',
  templateUrl: './my.001231.component.html'
})
export class My001231Component {
  @Input() parentName = '';
  myName = 'My001231Component';
}
