// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001641',
  templateUrl: './my.001641.component.html'
})
export class My001641Component {
  @Input() parentName = '';
  myName = 'My001641Component';
}
