// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001646',
  templateUrl: './my.001646.component.html'
})
export class My001646Component {
  @Input() parentName = '';
  myName = 'My001646Component';
}
