// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001642',
  templateUrl: './my.001642.component.html'
})
export class My001642Component {
  @Input() parentName = '';
  myName = 'My001642Component';
}
