// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001963',
  templateUrl: './my.001963.component.html'
})
export class My001963Component {
  @Input() parentName = '';
  myName = 'My001963Component';
}
