// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001965',
  templateUrl: './my.001965.component.html'
})
export class My001965Component {
  @Input() parentName = '';
  myName = 'My001965Component';
}
