// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001469',
  templateUrl: './my.001469.component.html'
})
export class My001469Component {
  @Input() parentName = '';
  myName = 'My001469Component';
}
