// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001964',
  templateUrl: './my.001964.component.html'
})
export class My001964Component {
  @Input() parentName = '';
  myName = 'My001964Component';
}
