// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001966',
  templateUrl: './my.001966.component.html'
})
export class My001966Component {
  @Input() parentName = '';
  myName = 'My001966Component';
}
