// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001959',
  templateUrl: './my.001959.component.html'
})
export class My001959Component {
  @Input() parentName = '';
  myName = 'My001959Component';
}
