// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001962',
  templateUrl: './my.001962.component.html'
})
export class My001962Component {
  @Input() parentName = '';
  myName = 'My001962Component';
}
