// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001960',
  templateUrl: './my.001960.component.html'
})
export class My001960Component {
  @Input() parentName = '';
  myName = 'My001960Component';
}
