// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000111Component } from './my.000111.component';
import { My000112Component } from './my.000112.component';
import { My000113Component } from './my.000113.component';
import { My000114Component } from './my.000114.component';
import { My000115Component } from './my.000115.component';
import { My000116Component } from './my.000116.component';
import { My000117Component } from './my.000117.component';
import { My000118Component } from './my.000118.component';

@NgModule({
  declarations: [
    My000111Component,
    My000112Component,
    My000113Component,
    My000114Component,
    My000115Component,
    My000116Component,
    My000117Component,
    My000118Component,
  ],
  imports: [CommonModule],
  exports: [
    My000111Component,
  ]
})
export class Module000013 { }
