// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001487Component } from './my.001487.component';
import { My001488Component } from './my.001488.component';
import { My001489Component } from './my.001489.component';
import { My001490Component } from './my.001490.component';
import { My001491Component } from './my.001491.component';
import { My001492Component } from './my.001492.component';

@NgModule({
  declarations: [
    My001487Component,
    My001488Component,
    My001489Component,
    My001490Component,
    My001491Component,
    My001492Component,
  ],
  imports: [CommonModule],
  exports: [
    My001487Component,
  ]
})
export class Module000247 { }
