// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001489',
  templateUrl: './my.001489.component.html'
})
export class My001489Component {
  @Input() parentName = '';
  myName = 'My001489Component';
}
