// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001984',
  templateUrl: './my.001984.component.html'
})
export class My001984Component {
  @Input() parentName = '';
  myName = 'My001984Component';
}
