// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001990',
  templateUrl: './my.001990.component.html'
})
export class My001990Component {
  @Input() parentName = '';
  myName = 'My001990Component';
}
