// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001988',
  templateUrl: './my.001988.component.html'
})
export class My001988Component {
  @Input() parentName = '';
  myName = 'My001988Component';
}
