// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001987',
  templateUrl: './my.001987.component.html'
})
export class My001987Component {
  @Input() parentName = '';
  myName = 'My001987Component';
}
