// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001986',
  templateUrl: './my.001986.component.html'
})
export class My001986Component {
  @Input() parentName = '';
  myName = 'My001986Component';
}
