// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000783Component } from './my.000783.component';
import { My000784Component } from './my.000784.component';
import { My000785Component } from './my.000785.component';
import { My000786Component } from './my.000786.component';
import { My000787Component } from './my.000787.component';
import { My000788Component } from './my.000788.component';

@NgModule({
  declarations: [
    My000783Component,
    My000784Component,
    My000785Component,
    My000786Component,
    My000787Component,
    My000788Component,
  ],
  imports: [CommonModule],
  exports: [
    My000783Component,
  ]
})
export class Module000113 { }
