// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000911Component } from './my.000911.component';
import { My000912Component } from './my.000912.component';
import { My000913Component } from './my.000913.component';
import { My000914Component } from './my.000914.component';
import { My000915Component } from './my.000915.component';
import { My000916Component } from './my.000916.component';
import { My000917Component } from './my.000917.component';
import { My000918Component } from './my.000918.component';

@NgModule({
  declarations: [
    My000911Component,
    My000912Component,
    My000913Component,
    My000914Component,
    My000915Component,
    My000916Component,
    My000917Component,
    My000918Component,
  ],
  imports: [CommonModule],
  exports: [
    My000911Component,
  ]
})
export class Module000113 { }
