// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000913',
  templateUrl: './my.000913.component.html'
})
export class My000913Component {
  @Input() parentName = '';
  myName = 'My000913Component';
}
