// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000563Component } from './my.000563.component';
import { My000564Component } from './my.000564.component';
import { My000565Component } from './my.000565.component';
import { My000566Component } from './my.000566.component';
import { My000567Component } from './my.000567.component';
import { My000568Component } from './my.000568.component';

@NgModule({
  declarations: [
    My000563Component,
    My000564Component,
    My000565Component,
    My000566Component,
    My000567Component,
    My000568Component,
  ],
  imports: [CommonModule],
  exports: [
    My000563Component,
  ]
})
export class Module000093 { }
