// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000317Component } from './my.000317.component';
import { My000318Component } from './my.000318.component';
import { My000319Component } from './my.000319.component';
import { My000320Component } from './my.000320.component';
import { My000321Component } from './my.000321.component';
import { My000322Component } from './my.000322.component';

@NgModule({
  declarations: [
    My000317Component,
    My000318Component,
    My000319Component,
    My000320Component,
    My000321Component,
    My000322Component,
  ],
  imports: [CommonModule],
  exports: [
    My000317Component,
  ]
})
export class Module000052 { }
