// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001888',
  templateUrl: './my.001888.component.html'
})
export class My001888Component {
  @Input() parentName = '';
  myName = 'My001888Component';
}
