// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001894',
  templateUrl: './my.001894.component.html'
})
export class My001894Component {
  @Input() parentName = '';
  myName = 'My001894Component';
}
