// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001887',
  templateUrl: './my.001887.component.html'
})
export class My001887Component {
  @Input() parentName = '';
  myName = 'My001887Component';
}
