// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001889',
  templateUrl: './my.001889.component.html'
})
export class My001889Component {
  @Input() parentName = '';
  myName = 'My001889Component';
}
