// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001890',
  templateUrl: './my.001890.component.html'
})
export class My001890Component {
  @Input() parentName = '';
  myName = 'My001890Component';
}
