// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001893',
  templateUrl: './my.001893.component.html'
})
export class My001893Component {
  @Input() parentName = '';
  myName = 'My001893Component';
}
