// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001419',
  templateUrl: './my.001419.component.html'
})
export class My001419Component {
  @Input() parentName = '';
  myName = 'My001419Component';
}
