// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001891',
  templateUrl: './my.001891.component.html'
})
export class My001891Component {
  @Input() parentName = '';
  myName = 'My001891Component';
}
