// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000617',
  templateUrl: './my.000617.component.html'
})
export class My000617Component {
  @Input() parentName = '';
  myName = 'My000617Component';
}
