// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000720',
  templateUrl: './my.000720.component.html'
})
export class My000720Component {
  @Input() parentName = '';
  myName = 'My000720Component';
}
