// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001259Component } from './my.001259.component';
import { My001260Component } from './my.001260.component';
import { My001261Component } from './my.001261.component';
import { My001262Component } from './my.001262.component';
import { My001263Component } from './my.001263.component';
import { My001264Component } from './my.001264.component';

@NgModule({
  declarations: [
    My001259Component,
    My001260Component,
    My001261Component,
    My001262Component,
    My001263Component,
    My001264Component,
  ],
  imports: [CommonModule],
  exports: [
    My001259Component,
  ]
})
export class Module000209 { }
