// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001683',
  templateUrl: './my.001683.component.html'
})
export class My001683Component {
  @Input() parentName = '';
  myName = 'My001683Component';
}
