// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001685',
  templateUrl: './my.001685.component.html'
})
export class My001685Component {
  @Input() parentName = '';
  myName = 'My001685Component';
}
