// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001262',
  templateUrl: './my.001262.component.html'
})
export class My001262Component {
  @Input() parentName = '';
  myName = 'My001262Component';
}
