// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001263',
  templateUrl: './my.001263.component.html'
})
export class My001263Component {
  @Input() parentName = '';
  myName = 'My001263Component';
}
