// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001679',
  templateUrl: './my.001679.component.html'
})
export class My001679Component {
  @Input() parentName = '';
  myName = 'My001679Component';
}
