// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000467Component } from './my.000467.component';
import { My000468Component } from './my.000468.component';
import { My000469Component } from './my.000469.component';
import { My000470Component } from './my.000470.component';
import { My000471Component } from './my.000471.component';
import { My000472Component } from './my.000472.component';

@NgModule({
  declarations: [
    My000467Component,
    My000468Component,
    My000469Component,
    My000470Component,
    My000471Component,
    My000472Component,
  ],
  imports: [CommonModule],
  exports: [
    My000467Component,
  ]
})
export class Module000077 { }
