// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000467',
  templateUrl: './my.000467.component.html'
})
export class My000467Component {
  @Input() parentName = '';
  myName = 'My000467Component';
}
