// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001445Component } from './my.001445.component';
import { My001446Component } from './my.001446.component';
import { My001447Component } from './my.001447.component';
import { My001448Component } from './my.001448.component';
import { My001449Component } from './my.001449.component';
import { My001450Component } from './my.001450.component';

@NgModule({
  declarations: [
    My001445Component,
    My001446Component,
    My001447Component,
    My001448Component,
    My001449Component,
    My001450Component,
  ],
  imports: [CommonModule],
  exports: [
    My001445Component,
  ]
})
export class Module000240 { }
