// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001929',
  templateUrl: './my.001929.component.html'
})
export class My001929Component {
  @Input() parentName = '';
  myName = 'My001929Component';
}
