// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001450',
  templateUrl: './my.001450.component.html'
})
export class My001450Component {
  @Input() parentName = '';
  myName = 'My001450Component';
}
