// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001449',
  templateUrl: './my.001449.component.html'
})
export class My001449Component {
  @Input() parentName = '';
  myName = 'My001449Component';
}
