// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001447',
  templateUrl: './my.001447.component.html'
})
export class My001447Component {
  @Input() parentName = '';
  myName = 'My001447Component';
}
