// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001927',
  templateUrl: './my.001927.component.html'
})
export class My001927Component {
  @Input() parentName = '';
  myName = 'My001927Component';
}
