// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001931',
  templateUrl: './my.001931.component.html'
})
export class My001931Component {
  @Input() parentName = '';
  myName = 'My001931Component';
}
