// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001930',
  templateUrl: './my.001930.component.html'
})
export class My001930Component {
  @Input() parentName = '';
  myName = 'My001930Component';
}
