// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000221Component } from './my.000221.component';
import { My000222Component } from './my.000222.component';
import { My000223Component } from './my.000223.component';
import { My000224Component } from './my.000224.component';
import { My000225Component } from './my.000225.component';
import { My000226Component } from './my.000226.component';

@NgModule({
  declarations: [
    My000221Component,
    My000222Component,
    My000223Component,
    My000224Component,
    My000225Component,
    My000226Component,
  ],
  imports: [CommonModule],
  exports: [
    My000221Component,
  ]
})
export class Module000036 { }
