// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000221',
  templateUrl: './my.000221.component.html'
})
export class My000221Component {
  @Input() parentName = '';
  myName = 'My000221Component';
}
