// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000385Component } from './my.000385.component';
import { My000386Component } from './my.000386.component';
import { My000387Component } from './my.000387.component';
import { My000388Component } from './my.000388.component';
import { My000389Component } from './my.000389.component';
import { My000390Component } from './my.000390.component';
import { My000391Component } from './my.000391.component';

@NgModule({
  declarations: [
    My000385Component,
    My000386Component,
    My000387Component,
    My000388Component,
    My000389Component,
    My000390Component,
    My000391Component,
  ],
  imports: [CommonModule],
  exports: [
    My000385Component,
  ]
})
export class Module000055 { }
