// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000452',
  templateUrl: './my.000452.component.html'
})
export class My000452Component {
  @Input() parentName = '';
  myName = 'My000452Component';
}
