// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000511Component } from './my.000511.component';
import { My000512Component } from './my.000512.component';
import { My000513Component } from './my.000513.component';
import { My000514Component } from './my.000514.component';
import { My000515Component } from './my.000515.component';
import { My000516Component } from './my.000516.component';
import { My000517Component } from './my.000517.component';
import { My000518Component } from './my.000518.component';

@NgModule({
  declarations: [
    My000511Component,
    My000512Component,
    My000513Component,
    My000514Component,
    My000515Component,
    My000516Component,
    My000517Component,
    My000518Component,
  ],
  imports: [CommonModule],
  exports: [
    My000511Component,
  ]
})
export class Module000063 { }
