// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000947Component } from './my.000947.component';
import { My000948Component } from './my.000948.component';
import { My000949Component } from './my.000949.component';
import { My000950Component } from './my.000950.component';
import { My000951Component } from './my.000951.component';
import { My000952Component } from './my.000952.component';

@NgModule({
  declarations: [
    My000947Component,
    My000948Component,
    My000949Component,
    My000950Component,
    My000951Component,
    My000952Component,
  ],
  imports: [CommonModule],
  exports: [
    My000947Component,
  ]
})
export class Module000157 { }
