// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001266',
  templateUrl: './my.001266.component.html'
})
export class My001266Component {
  @Input() parentName = '';
  myName = 'My001266Component';
}
