// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001270',
  templateUrl: './my.001270.component.html'
})
export class My001270Component {
  @Input() parentName = '';
  myName = 'My001270Component';
}
