// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000827Component } from './my.000827.component';
import { My000828Component } from './my.000828.component';
import { My000829Component } from './my.000829.component';
import { My000830Component } from './my.000830.component';
import { My000831Component } from './my.000831.component';
import { My000832Component } from './my.000832.component';

@NgModule({
  declarations: [
    My000827Component,
    My000828Component,
    My000829Component,
    My000830Component,
    My000831Component,
    My000832Component,
  ],
  imports: [CommonModule],
  exports: [
    My000827Component,
  ]
})
export class Module000137 { }
