// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001341',
  templateUrl: './my.001341.component.html'
})
export class My001341Component {
  @Input() parentName = '';
  myName = 'My001341Component';
}
