// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001338',
  templateUrl: './my.001338.component.html'
})
export class My001338Component {
  @Input() parentName = '';
  myName = 'My001338Component';
}
