// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001337',
  templateUrl: './my.001337.component.html'
})
export class My001337Component {
  @Input() parentName = '';
  myName = 'My001337Component';
}
