// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001340',
  templateUrl: './my.001340.component.html'
})
export class My001340Component {
  @Input() parentName = '';
  myName = 'My001340Component';
}
