// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000981Component } from './my.000981.component';
import { My000982Component } from './my.000982.component';
import { My000983Component } from './my.000983.component';
import { My000984Component } from './my.000984.component';
import { My000985Component } from './my.000985.component';
import { My000986Component } from './my.000986.component';

@NgModule({
  declarations: [
    My000981Component,
    My000982Component,
    My000983Component,
    My000984Component,
    My000985Component,
    My000986Component,
  ],
  imports: [CommonModule],
  exports: [
    My000981Component,
  ]
})
export class Module000146 { }
