// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000881Component } from './my.000881.component';
import { My000882Component } from './my.000882.component';
import { My000883Component } from './my.000883.component';
import { My000884Component } from './my.000884.component';
import { My000885Component } from './my.000885.component';
import { My000886Component } from './my.000886.component';

@NgModule({
  declarations: [
    My000881Component,
    My000882Component,
    My000883Component,
    My000884Component,
    My000885Component,
    My000886Component,
  ],
  imports: [CommonModule],
  exports: [
    My000881Component,
  ]
})
export class Module000146 { }
