// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000981',
  templateUrl: './my.000981.component.html'
})
export class My000981Component {
  @Input() parentName = '';
  myName = 'My000981Component';
}
