// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000587Component } from './my.000587.component';
import { My000588Component } from './my.000588.component';
import { My000589Component } from './my.000589.component';
import { My000590Component } from './my.000590.component';
import { My000591Component } from './my.000591.component';
import { My000592Component } from './my.000592.component';

@NgModule({
  declarations: [
    My000587Component,
    My000588Component,
    My000589Component,
    My000590Component,
    My000591Component,
    My000592Component,
  ],
  imports: [CommonModule],
  exports: [
    My000587Component,
  ]
})
export class Module000097 { }
