// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001288',
  templateUrl: './my.001288.component.html'
})
export class My001288Component {
  @Input() parentName = '';
  myName = 'My001288Component';
}
