// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001760',
  templateUrl: './my.001760.component.html'
})
export class My001760Component {
  @Input() parentName = '';
  myName = 'My001760Component';
}
