// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001321',
  templateUrl: './my.001321.component.html'
})
export class My001321Component {
  @Input() parentName = '';
  myName = 'My001321Component';
}
