// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001764',
  templateUrl: './my.001764.component.html'
})
export class My001764Component {
  @Input() parentName = '';
  myName = 'My001764Component';
}
