// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001761',
  templateUrl: './my.001761.component.html'
})
export class My001761Component {
  @Input() parentName = '';
  myName = 'My001761Component';
}
