// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001763',
  templateUrl: './my.001763.component.html'
})
export class My001763Component {
  @Input() parentName = '';
  myName = 'My001763Component';
}
