// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001762',
  templateUrl: './my.001762.component.html'
})
export class My001762Component {
  @Input() parentName = '';
  myName = 'My001762Component';
}
