// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000581Component } from './my.000581.component';
import { My000582Component } from './my.000582.component';
import { My000583Component } from './my.000583.component';
import { My000584Component } from './my.000584.component';
import { My000585Component } from './my.000585.component';
import { My000586Component } from './my.000586.component';
import { My000587Component } from './my.000587.component';

@NgModule({
  declarations: [
    My000581Component,
    My000582Component,
    My000583Component,
    My000584Component,
    My000585Component,
    My000586Component,
    My000587Component,
  ],
  imports: [CommonModule],
  exports: [
    My000581Component,
  ]
})
export class Module000083 { }
