// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000503Component } from './my.000503.component';
import { My000504Component } from './my.000504.component';
import { My000505Component } from './my.000505.component';
import { My000506Component } from './my.000506.component';
import { My000507Component } from './my.000507.component';
import { My000508Component } from './my.000508.component';

@NgModule({
  declarations: [
    My000503Component,
    My000504Component,
    My000505Component,
    My000506Component,
    My000507Component,
    My000508Component,
  ],
  imports: [CommonModule],
  exports: [
    My000503Component,
  ]
})
export class Module000083 { }
