// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001175Component } from './my.001175.component';
import { My001176Component } from './my.001176.component';
import { My001177Component } from './my.001177.component';
import { My001178Component } from './my.001178.component';
import { My001179Component } from './my.001179.component';
import { My001180Component } from './my.001180.component';

@NgModule({
  declarations: [
    My001175Component,
    My001176Component,
    My001177Component,
    My001178Component,
    My001179Component,
    My001180Component,
  ],
  imports: [CommonModule],
  exports: [
    My001175Component,
  ]
})
export class Module000195 { }
