// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001570',
  templateUrl: './my.001570.component.html'
})
export class My001570Component {
  @Input() parentName = '';
  myName = 'My001570Component';
}
