// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001178',
  templateUrl: './my.001178.component.html'
})
export class My001178Component {
  @Input() parentName = '';
  myName = 'My001178Component';
}
