// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001569',
  templateUrl: './my.001569.component.html'
})
export class My001569Component {
  @Input() parentName = '';
  myName = 'My001569Component';
}
