// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001572',
  templateUrl: './my.001572.component.html'
})
export class My001572Component {
  @Input() parentName = '';
  myName = 'My001572Component';
}
