// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001568',
  templateUrl: './my.001568.component.html'
})
export class My001568Component {
  @Input() parentName = '';
  myName = 'My001568Component';
}
