// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001573',
  templateUrl: './my.001573.component.html'
})
export class My001573Component {
  @Input() parentName = '';
  myName = 'My001573Component';
}
