// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001176',
  templateUrl: './my.001176.component.html'
})
export class My001176Component {
  @Input() parentName = '';
  myName = 'My001176Component';
}
