// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001151Component } from './my.001151.component';
import { My001152Component } from './my.001152.component';
import { My001153Component } from './my.001153.component';
import { My001154Component } from './my.001154.component';
import { My001155Component } from './my.001155.component';
import { My001156Component } from './my.001156.component';

@NgModule({
  declarations: [
    My001151Component,
    My001152Component,
    My001153Component,
    My001154Component,
    My001155Component,
    My001156Component,
  ],
  imports: [CommonModule],
  exports: [
    My001151Component,
  ]
})
export class Module000191 { }
