// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001535Component } from './my.001535.component';
import { My001536Component } from './my.001536.component';
import { My001537Component } from './my.001537.component';
import { My001538Component } from './my.001538.component';
import { My001539Component } from './my.001539.component';
import { My001540Component } from './my.001540.component';
import { My001541Component } from './my.001541.component';
import { My001542Component } from './my.001542.component';

@NgModule({
  declarations: [
    My001535Component,
    My001536Component,
    My001537Component,
    My001538Component,
    My001539Component,
    My001540Component,
    My001541Component,
    My001542Component,
  ],
  imports: [CommonModule],
  exports: [
    My001535Component,
  ]
})
export class Module000191 { }
