// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001536',
  templateUrl: './my.001536.component.html'
})
export class My001536Component {
  @Input() parentName = '';
  myName = 'My001536Component';
}
