// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001542',
  templateUrl: './my.001542.component.html'
})
export class My001542Component {
  @Input() parentName = '';
  myName = 'My001542Component';
}
