// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001538',
  templateUrl: './my.001538.component.html'
})
export class My001538Component {
  @Input() parentName = '';
  myName = 'My001538Component';
}
