// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001541',
  templateUrl: './my.001541.component.html'
})
export class My001541Component {
  @Input() parentName = '';
  myName = 'My001541Component';
}
