// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001535',
  templateUrl: './my.001535.component.html'
})
export class My001535Component {
  @Input() parentName = '';
  myName = 'My001535Component';
}
