// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001537',
  templateUrl: './my.001537.component.html'
})
export class My001537Component {
  @Input() parentName = '';
  myName = 'My001537Component';
}
