// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000303Component } from './my.000303.component';
import { My000304Component } from './my.000304.component';
import { My000305Component } from './my.000305.component';
import { My000306Component } from './my.000306.component';
import { My000307Component } from './my.000307.component';
import { My000308Component } from './my.000308.component';
import { My000309Component } from './my.000309.component';
import { My000310Component } from './my.000310.component';

@NgModule({
  declarations: [
    My000303Component,
    My000304Component,
    My000305Component,
    My000306Component,
    My000307Component,
    My000308Component,
    My000309Component,
    My000310Component,
  ],
  imports: [CommonModule],
  exports: [
    My000303Component,
  ]
})
export class Module000037 { }
