// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000448Component } from './my.000448.component';
import { My000449Component } from './my.000449.component';
import { My000450Component } from './my.000450.component';
import { My000451Component } from './my.000451.component';
import { My000452Component } from './my.000452.component';
import { My000453Component } from './my.000453.component';
import { My000454Component } from './my.000454.component';

@NgModule({
  declarations: [
    My000448Component,
    My000449Component,
    My000450Component,
    My000451Component,
    My000452Component,
    My000453Component,
    My000454Component,
  ],
  imports: [CommonModule],
  exports: [
    My000448Component,
  ]
})
export class Module000064 { }
