// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001808',
  templateUrl: './my.001808.component.html'
})
export class My001808Component {
  @Input() parentName = '';
  myName = 'My001808Component';
}
