// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001814',
  templateUrl: './my.001814.component.html'
})
export class My001814Component {
  @Input() parentName = '';
  myName = 'My001814Component';
}
