// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001812',
  templateUrl: './my.001812.component.html'
})
export class My001812Component {
  @Input() parentName = '';
  myName = 'My001812Component';
}
