// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001811',
  templateUrl: './my.001811.component.html'
})
export class My001811Component {
  @Input() parentName = '';
  myName = 'My001811Component';
}
