// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001359',
  templateUrl: './my.001359.component.html'
})
export class My001359Component {
  @Input() parentName = '';
  myName = 'My001359Component';
}
