// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001813',
  templateUrl: './my.001813.component.html'
})
export class My001813Component {
  @Input() parentName = '';
  myName = 'My001813Component';
}
