// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000923Component } from './my.000923.component';
import { My000924Component } from './my.000924.component';
import { My000925Component } from './my.000925.component';
import { My000926Component } from './my.000926.component';
import { My000927Component } from './my.000927.component';
import { My000928Component } from './my.000928.component';

@NgModule({
  declarations: [
    My000923Component,
    My000924Component,
    My000925Component,
    My000926Component,
    My000927Component,
    My000928Component,
  ],
  imports: [CommonModule],
  exports: [
    My000923Component,
  ]
})
export class Module000153 { }
