// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001231Component } from './my.001231.component';
import { My001232Component } from './my.001232.component';
import { My001233Component } from './my.001233.component';
import { My001234Component } from './my.001234.component';
import { My001235Component } from './my.001235.component';
import { My001236Component } from './my.001236.component';
import { My001237Component } from './my.001237.component';
import { My001238Component } from './my.001238.component';

@NgModule({
  declarations: [
    My001231Component,
    My001232Component,
    My001233Component,
    My001234Component,
    My001235Component,
    My001236Component,
    My001237Component,
    My001238Component,
  ],
  imports: [CommonModule],
  exports: [
    My001231Component,
  ]
})
export class Module000153 { }
