// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001233',
  templateUrl: './my.001233.component.html'
})
export class My001233Component {
  @Input() parentName = '';
  myName = 'My001233Component';
}
