// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001238',
  templateUrl: './my.001238.component.html'
})
export class My001238Component {
  @Input() parentName = '';
  myName = 'My001238Component';
}
