// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001237',
  templateUrl: './my.001237.component.html'
})
export class My001237Component {
  @Input() parentName = '';
  myName = 'My001237Component';
}
