// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001373Component } from './my.001373.component';
import { My001374Component } from './my.001374.component';
import { My001375Component } from './my.001375.component';
import { My001376Component } from './my.001376.component';
import { My001377Component } from './my.001377.component';
import { My001378Component } from './my.001378.component';

@NgModule({
  declarations: [
    My001373Component,
    My001374Component,
    My001375Component,
    My001376Component,
    My001377Component,
    My001378Component,
  ],
  imports: [CommonModule],
  exports: [
    My001373Component,
  ]
})
export class Module000228 { }
