// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001831Component } from './my.001831.component';
import { My001832Component } from './my.001832.component';
import { My001833Component } from './my.001833.component';
import { My001834Component } from './my.001834.component';
import { My001835Component } from './my.001835.component';
import { My001836Component } from './my.001836.component';
import { My001837Component } from './my.001837.component';
import { My001838Component } from './my.001838.component';

@NgModule({
  declarations: [
    My001831Component,
    My001832Component,
    My001833Component,
    My001834Component,
    My001835Component,
    My001836Component,
    My001837Component,
    My001838Component,
  ],
  imports: [CommonModule],
  exports: [
    My001831Component,
  ]
})
export class Module000228 { }
