// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001376',
  templateUrl: './my.001376.component.html'
})
export class My001376Component {
  @Input() parentName = '';
  myName = 'My001376Component';
}
