// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001833',
  templateUrl: './my.001833.component.html'
})
export class My001833Component {
  @Input() parentName = '';
  myName = 'My001833Component';
}
