// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001835',
  templateUrl: './my.001835.component.html'
})
export class My001835Component {
  @Input() parentName = '';
  myName = 'My001835Component';
}
