// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001374',
  templateUrl: './my.001374.component.html'
})
export class My001374Component {
  @Input() parentName = '';
  myName = 'My001374Component';
}
