// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001832',
  templateUrl: './my.001832.component.html'
})
export class My001832Component {
  @Input() parentName = '';
  myName = 'My001832Component';
}
