// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001837',
  templateUrl: './my.001837.component.html'
})
export class My001837Component {
  @Input() parentName = '';
  myName = 'My001837Component';
}
