// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001215Component } from './my.001215.component';
import { My001216Component } from './my.001216.component';
import { My001217Component } from './my.001217.component';
import { My001218Component } from './my.001218.component';
import { My001219Component } from './my.001219.component';
import { My001220Component } from './my.001220.component';
import { My001221Component } from './my.001221.component';
import { My001222Component } from './my.001222.component';

@NgModule({
  declarations: [
    My001215Component,
    My001216Component,
    My001217Component,
    My001218Component,
    My001219Component,
    My001220Component,
    My001221Component,
    My001222Component,
  ],
  imports: [CommonModule],
  exports: [
    My001215Component,
  ]
})
export class Module000151 { }
