// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001220',
  templateUrl: './my.001220.component.html'
})
export class My001220Component {
  @Input() parentName = '';
  myName = 'My001220Component';
}
