// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000911',
  templateUrl: './my.000911.component.html'
})
export class My000911Component {
  @Input() parentName = '';
  myName = 'My000911Component';
}
