// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001221',
  templateUrl: './my.001221.component.html'
})
export class My001221Component {
  @Input() parentName = '';
  myName = 'My001221Component';
}
