// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000273Component } from './my.000273.component';
import { My000274Component } from './my.000274.component';
import { My000275Component } from './my.000275.component';
import { My000276Component } from './my.000276.component';
import { My000277Component } from './my.000277.component';
import { My000278Component } from './my.000278.component';
import { My000279Component } from './my.000279.component';

@NgModule({
  declarations: [
    My000273Component,
    My000274Component,
    My000275Component,
    My000276Component,
    My000277Component,
    My000278Component,
    My000279Component,
  ],
  imports: [CommonModule],
  exports: [
    My000273Component,
  ]
})
export class Module000039 { }
