// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000959Component } from './my.000959.component';
import { My000960Component } from './my.000960.component';
import { My000961Component } from './my.000961.component';
import { My000962Component } from './my.000962.component';
import { My000963Component } from './my.000963.component';
import { My000964Component } from './my.000964.component';

@NgModule({
  declarations: [
    My000959Component,
    My000960Component,
    My000961Component,
    My000962Component,
    My000963Component,
    My000964Component,
  ],
  imports: [CommonModule],
  exports: [
    My000959Component,
  ]
})
export class Module000159 { }
