// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001280',
  templateUrl: './my.001280.component.html'
})
export class My001280Component {
  @Input() parentName = '';
  myName = 'My001280Component';
}
