// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001285',
  templateUrl: './my.001285.component.html'
})
export class My001285Component {
  @Input() parentName = '';
  myName = 'My001285Component';
}
