// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000246',
  templateUrl: './my.000246.component.html'
})
export class My000246Component {
  @Input() parentName = '';
  myName = 'My000246Component';
}
