// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001452',
  templateUrl: './my.001452.component.html'
})
export class My001452Component {
  @Input() parentName = '';
  myName = 'My001452Component';
}
