// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001086',
  templateUrl: './my.001086.component.html'
})
export class My001086Component {
  @Input() parentName = '';
  myName = 'My001086Component';
}
