// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000485Component } from './my.000485.component';
import { My000486Component } from './my.000486.component';
import { My000487Component } from './my.000487.component';
import { My000488Component } from './my.000488.component';
import { My000489Component } from './my.000489.component';
import { My000490Component } from './my.000490.component';

@NgModule({
  declarations: [
    My000485Component,
    My000486Component,
    My000487Component,
    My000488Component,
    My000489Component,
    My000490Component,
  ],
  imports: [CommonModule],
  exports: [
    My000485Component,
  ]
})
export class Module000080 { }
