// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000564',
  templateUrl: './my.000564.component.html'
})
export class My000564Component {
  @Input() parentName = '';
  myName = 'My000564Component';
}
