// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000485',
  templateUrl: './my.000485.component.html'
})
export class My000485Component {
  @Input() parentName = '';
  myName = 'My000485Component';
}
