// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000021Component } from './my.000021.component';
import { My000022Component } from './my.000022.component';
import { My000023Component } from './my.000023.component';
import { My000024Component } from './my.000024.component';
import { My000025Component } from './my.000025.component';
import { My000026Component } from './my.000026.component';
import { My000027Component } from './my.000027.component';

@NgModule({
  declarations: [
    My000021Component,
    My000022Component,
    My000023Component,
    My000024Component,
    My000025Component,
    My000026Component,
    My000027Component,
  ],
  imports: [CommonModule],
  exports: [
    My000021Component,
  ]
})
export class Module000003 { }
