// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001235Component } from './my.001235.component';
import { My001236Component } from './my.001236.component';
import { My001237Component } from './my.001237.component';
import { My001238Component } from './my.001238.component';
import { My001239Component } from './my.001239.component';
import { My001240Component } from './my.001240.component';

@NgModule({
  declarations: [
    My001235Component,
    My001236Component,
    My001237Component,
    My001238Component,
    My001239Component,
    My001240Component,
  ],
  imports: [CommonModule],
  exports: [
    My001235Component,
  ]
})
export class Module000205 { }
