// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001654',
  templateUrl: './my.001654.component.html'
})
export class My001654Component {
  @Input() parentName = '';
  myName = 'My001654Component';
}
