// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001647',
  templateUrl: './my.001647.component.html'
})
export class My001647Component {
  @Input() parentName = '';
  myName = 'My001647Component';
}
