// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001235',
  templateUrl: './my.001235.component.html'
})
export class My001235Component {
  @Input() parentName = '';
  myName = 'My001235Component';
}
