// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001648',
  templateUrl: './my.001648.component.html'
})
export class My001648Component {
  @Input() parentName = '';
  myName = 'My001648Component';
}
