// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001649',
  templateUrl: './my.001649.component.html'
})
export class My001649Component {
  @Input() parentName = '';
  myName = 'My001649Component';
}
