// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001239',
  templateUrl: './my.001239.component.html'
})
export class My001239Component {
  @Input() parentName = '';
  myName = 'My001239Component';
}
