// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001652',
  templateUrl: './my.001652.component.html'
})
export class My001652Component {
  @Input() parentName = '';
  myName = 'My001652Component';
}
