// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000251',
  templateUrl: './my.000251.component.html'
})
export class My000251Component {
  @Input() parentName = '';
  myName = 'My000251Component';
}
