// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000127Component } from './my.000127.component';
import { My000128Component } from './my.000128.component';
import { My000129Component } from './my.000129.component';
import { My000130Component } from './my.000130.component';
import { My000131Component } from './my.000131.component';
import { My000132Component } from './my.000132.component';
import { My000133Component } from './my.000133.component';
import { My000134Component } from './my.000134.component';

@NgModule({
  declarations: [
    My000127Component,
    My000128Component,
    My000129Component,
    My000130Component,
    My000131Component,
    My000132Component,
    My000133Component,
    My000134Component,
  ],
  imports: [CommonModule],
  exports: [
    My000127Component,
  ]
})
export class Module000015 { }
