// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000785Component } from './my.000785.component';
import { My000786Component } from './my.000786.component';
import { My000787Component } from './my.000787.component';
import { My000788Component } from './my.000788.component';
import { My000789Component } from './my.000789.component';
import { My000790Component } from './my.000790.component';

@NgModule({
  declarations: [
    My000785Component,
    My000786Component,
    My000787Component,
    My000788Component,
    My000789Component,
    My000790Component,
  ],
  imports: [CommonModule],
  exports: [
    My000785Component,
  ]
})
export class Module000130 { }
