// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001047',
  templateUrl: './my.001047.component.html'
})
export class My001047Component {
  @Input() parentName = '';
  myName = 'My001047Component';
}
