// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001051',
  templateUrl: './my.001051.component.html'
})
export class My001051Component {
  @Input() parentName = '';
  myName = 'My001051Component';
}
