// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000644Component } from './my.000644.component';
import { My000645Component } from './my.000645.component';
import { My000646Component } from './my.000646.component';
import { My000647Component } from './my.000647.component';
import { My000648Component } from './my.000648.component';
import { My000649Component } from './my.000649.component';
import { My000650Component } from './my.000650.component';

@NgModule({
  declarations: [
    My000644Component,
    My000645Component,
    My000646Component,
    My000647Component,
    My000648Component,
    My000649Component,
    My000650Component,
  ],
  imports: [CommonModule],
  exports: [
    My000644Component,
  ]
})
export class Module000092 { }
