// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001327Component } from './my.001327.component';
import { My001328Component } from './my.001328.component';
import { My001329Component } from './my.001329.component';
import { My001330Component } from './my.001330.component';
import { My001331Component } from './my.001331.component';
import { My001332Component } from './my.001332.component';
import { My001333Component } from './my.001333.component';
import { My001334Component } from './my.001334.component';

@NgModule({
  declarations: [
    My001327Component,
    My001328Component,
    My001329Component,
    My001330Component,
    My001331Component,
    My001332Component,
    My001333Component,
    My001334Component,
  ],
  imports: [CommonModule],
  exports: [
    My001327Component,
  ]
})
export class Module000165 { }
