// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001328',
  templateUrl: './my.001328.component.html'
})
export class My001328Component {
  @Input() parentName = '';
  myName = 'My001328Component';
}
