// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001333',
  templateUrl: './my.001333.component.html'
})
export class My001333Component {
  @Input() parentName = '';
  myName = 'My001333Component';
}
