// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000969Component } from './my.000969.component';
import { My000970Component } from './my.000970.component';
import { My000971Component } from './my.000971.component';
import { My000972Component } from './my.000972.component';
import { My000973Component } from './my.000973.component';
import { My000974Component } from './my.000974.component';

@NgModule({
  declarations: [
    My000969Component,
    My000970Component,
    My000971Component,
    My000972Component,
    My000973Component,
    My000974Component,
  ],
  imports: [CommonModule],
  exports: [
    My000969Component,
  ]
})
export class Module000144 { }
