// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000869Component } from './my.000869.component';
import { My000870Component } from './my.000870.component';
import { My000871Component } from './my.000871.component';
import { My000872Component } from './my.000872.component';
import { My000873Component } from './my.000873.component';
import { My000874Component } from './my.000874.component';

@NgModule({
  declarations: [
    My000869Component,
    My000870Component,
    My000871Component,
    My000872Component,
    My000873Component,
    My000874Component,
  ],
  imports: [CommonModule],
  exports: [
    My000869Component,
  ]
})
export class Module000144 { }
