// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000972',
  templateUrl: './my.000972.component.html'
})
export class My000972Component {
  @Input() parentName = '';
  myName = 'My000972Component';
}
