// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001060',
  templateUrl: './my.001060.component.html'
})
export class My001060Component {
  @Input() parentName = '';
  myName = 'My001060Component';
}
