// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001412',
  templateUrl: './my.001412.component.html'
})
export class My001412Component {
  @Input() parentName = '';
  myName = 'My001412Component';
}
