// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001407',
  templateUrl: './my.001407.component.html'
})
export class My001407Component {
  @Input() parentName = '';
  myName = 'My001407Component';
}
