// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001139Component } from './my.001139.component';
import { My001140Component } from './my.001140.component';
import { My001141Component } from './my.001141.component';
import { My001142Component } from './my.001142.component';
import { My001143Component } from './my.001143.component';
import { My001144Component } from './my.001144.component';

@NgModule({
  declarations: [
    My001139Component,
    My001140Component,
    My001141Component,
    My001142Component,
    My001143Component,
    My001144Component,
  ],
  imports: [CommonModule],
  exports: [
    My001139Component,
  ]
})
export class Module000189 { }
