// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001519Component } from './my.001519.component';
import { My001520Component } from './my.001520.component';
import { My001521Component } from './my.001521.component';
import { My001522Component } from './my.001522.component';
import { My001523Component } from './my.001523.component';
import { My001524Component } from './my.001524.component';
import { My001525Component } from './my.001525.component';
import { My001526Component } from './my.001526.component';

@NgModule({
  declarations: [
    My001519Component,
    My001520Component,
    My001521Component,
    My001522Component,
    My001523Component,
    My001524Component,
    My001525Component,
    My001526Component,
  ],
  imports: [CommonModule],
  exports: [
    My001519Component,
  ]
})
export class Module000189 { }
