// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001525',
  templateUrl: './my.001525.component.html'
})
export class My001525Component {
  @Input() parentName = '';
  myName = 'My001525Component';
}
