// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001519',
  templateUrl: './my.001519.component.html'
})
export class My001519Component {
  @Input() parentName = '';
  myName = 'My001519Component';
}
