// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001379Component } from './my.001379.component';
import { My001380Component } from './my.001380.component';
import { My001381Component } from './my.001381.component';
import { My001382Component } from './my.001382.component';
import { My001383Component } from './my.001383.component';
import { My001384Component } from './my.001384.component';

@NgModule({
  declarations: [
    My001379Component,
    My001380Component,
    My001381Component,
    My001382Component,
    My001383Component,
    My001384Component,
  ],
  imports: [CommonModule],
  exports: [
    My001379Component,
  ]
})
export class Module000229 { }
