// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001382',
  templateUrl: './my.001382.component.html'
})
export class My001382Component {
  @Input() parentName = '';
  myName = 'My001382Component';
}
