// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001842',
  templateUrl: './my.001842.component.html'
})
export class My001842Component {
  @Input() parentName = '';
  myName = 'My001842Component';
}
