// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001840',
  templateUrl: './my.001840.component.html'
})
export class My001840Component {
  @Input() parentName = '';
  myName = 'My001840Component';
}
