// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001383',
  templateUrl: './my.001383.component.html'
})
export class My001383Component {
  @Input() parentName = '';
  myName = 'My001383Component';
}
