// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001381',
  templateUrl: './my.001381.component.html'
})
export class My001381Component {
  @Input() parentName = '';
  myName = 'My001381Component';
}
