// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001843',
  templateUrl: './my.001843.component.html'
})
export class My001843Component {
  @Input() parentName = '';
  myName = 'My001843Component';
}
