// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001839',
  templateUrl: './my.001839.component.html'
})
export class My001839Component {
  @Input() parentName = '';
  myName = 'My001839Component';
}
