// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000893Component } from './my.000893.component';
import { My000894Component } from './my.000894.component';
import { My000895Component } from './my.000895.component';
import { My000896Component } from './my.000896.component';
import { My000897Component } from './my.000897.component';
import { My000898Component } from './my.000898.component';

@NgModule({
  declarations: [
    My000893Component,
    My000894Component,
    My000895Component,
    My000896Component,
    My000897Component,
    My000898Component,
  ],
  imports: [CommonModule],
  exports: [
    My000893Component,
  ]
})
export class Module000148 { }
