// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000217Component } from './my.000217.component';
import { My000218Component } from './my.000218.component';
import { My000219Component } from './my.000219.component';
import { My000220Component } from './my.000220.component';
import { My000221Component } from './my.000221.component';
import { My000222Component } from './my.000222.component';
import { My000223Component } from './my.000223.component';

@NgModule({
  declarations: [
    My000217Component,
    My000218Component,
    My000219Component,
    My000220Component,
    My000221Component,
    My000222Component,
    My000223Component,
  ],
  imports: [CommonModule],
  exports: [
    My000217Component,
  ]
})
export class Module000031 { }
