// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001493Component } from './my.001493.component';
import { My001494Component } from './my.001494.component';
import { My001495Component } from './my.001495.component';
import { My001496Component } from './my.001496.component';
import { My001497Component } from './my.001497.component';
import { My001498Component } from './my.001498.component';

@NgModule({
  declarations: [
    My001493Component,
    My001494Component,
    My001495Component,
    My001496Component,
    My001497Component,
    My001498Component,
  ],
  imports: [CommonModule],
  exports: [
    My001493Component,
  ]
})
export class Module000248 { }
