// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001991Component } from './my.001991.component';
import { My001992Component } from './my.001992.component';
import { My001993Component } from './my.001993.component';
import { My001994Component } from './my.001994.component';
import { My001995Component } from './my.001995.component';
import { My001996Component } from './my.001996.component';
import { My001997Component } from './my.001997.component';
import { My001998Component } from './my.001998.component';

@NgModule({
  declarations: [
    My001991Component,
    My001992Component,
    My001993Component,
    My001994Component,
    My001995Component,
    My001996Component,
    My001997Component,
    My001998Component,
  ],
  imports: [CommonModule],
  exports: [
    My001991Component,
  ]
})
export class Module000248 { }
