// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001998',
  templateUrl: './my.001998.component.html'
})
export class My001998Component {
  @Input() parentName = '';
  myName = 'My001998Component';
}
