// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001497',
  templateUrl: './my.001497.component.html'
})
export class My001497Component {
  @Input() parentName = '';
  myName = 'My001497Component';
}
