// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001493',
  templateUrl: './my.001493.component.html'
})
export class My001493Component {
  @Input() parentName = '';
  myName = 'My001493Component';
}
