// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001498',
  templateUrl: './my.001498.component.html'
})
export class My001498Component {
  @Input() parentName = '';
  myName = 'My001498Component';
}
