// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001997',
  templateUrl: './my.001997.component.html'
})
export class My001997Component {
  @Input() parentName = '';
  myName = 'My001997Component';
}
