// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000437Component } from './my.000437.component';
import { My000438Component } from './my.000438.component';
import { My000439Component } from './my.000439.component';
import { My000440Component } from './my.000440.component';
import { My000441Component } from './my.000441.component';
import { My000442Component } from './my.000442.component';

@NgModule({
  declarations: [
    My000437Component,
    My000438Component,
    My000439Component,
    My000440Component,
    My000441Component,
    My000442Component,
  ],
  imports: [CommonModule],
  exports: [
    My000437Component,
  ]
})
export class Module000072 { }
