// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000583Component } from './my.000583.component';
import { My000584Component } from './my.000584.component';
import { My000585Component } from './my.000585.component';
import { My000586Component } from './my.000586.component';
import { My000587Component } from './my.000587.component';
import { My000588Component } from './my.000588.component';
import { My000589Component } from './my.000589.component';
import { My000590Component } from './my.000590.component';

@NgModule({
  declarations: [
    My000583Component,
    My000584Component,
    My000585Component,
    My000586Component,
    My000587Component,
    My000588Component,
    My000589Component,
    My000590Component,
  ],
  imports: [CommonModule],
  exports: [
    My000583Component,
  ]
})
export class Module000072 { }
