// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001751',
  templateUrl: './my.001751.component.html'
})
export class My001751Component {
  @Input() parentName = '';
  myName = 'My001751Component';
}
