// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001756',
  templateUrl: './my.001756.component.html'
})
export class My001756Component {
  @Input() parentName = '';
  myName = 'My001756Component';
}
