// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001754',
  templateUrl: './my.001754.component.html'
})
export class My001754Component {
  @Input() parentName = '';
  myName = 'My001754Component';
}
