// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001753',
  templateUrl: './my.001753.component.html'
})
export class My001753Component {
  @Input() parentName = '';
  myName = 'My001753Component';
}
