// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001758',
  templateUrl: './my.001758.component.html'
})
export class My001758Component {
  @Input() parentName = '';
  myName = 'My001758Component';
}
