// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001752',
  templateUrl: './my.001752.component.html'
})
export class My001752Component {
  @Input() parentName = '';
  myName = 'My001752Component';
}
