// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001755',
  templateUrl: './my.001755.component.html'
})
export class My001755Component {
  @Input() parentName = '';
  myName = 'My001755Component';
}
