// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001211Component } from './my.001211.component';
import { My001212Component } from './my.001212.component';
import { My001213Component } from './my.001213.component';
import { My001214Component } from './my.001214.component';
import { My001215Component } from './my.001215.component';
import { My001216Component } from './my.001216.component';

@NgModule({
  declarations: [
    My001211Component,
    My001212Component,
    My001213Component,
    My001214Component,
    My001215Component,
    My001216Component,
  ],
  imports: [CommonModule],
  exports: [
    My001211Component,
  ]
})
export class Module000201 { }
