// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001215',
  templateUrl: './my.001215.component.html'
})
export class My001215Component {
  @Input() parentName = '';
  myName = 'My001215Component';
}
