// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001616',
  templateUrl: './my.001616.component.html'
})
export class My001616Component {
  @Input() parentName = '';
  myName = 'My001616Component';
}
