// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001618',
  templateUrl: './my.001618.component.html'
})
export class My001618Component {
  @Input() parentName = '';
  myName = 'My001618Component';
}
