// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001615',
  templateUrl: './my.001615.component.html'
})
export class My001615Component {
  @Input() parentName = '';
  myName = 'My001615Component';
}
