// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001619',
  templateUrl: './my.001619.component.html'
})
export class My001619Component {
  @Input() parentName = '';
  myName = 'My001619Component';
}
