// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001216',
  templateUrl: './my.001216.component.html'
})
export class My001216Component {
  @Input() parentName = '';
  myName = 'My001216Component';
}
