// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000435',
  templateUrl: './my.000435.component.html'
})
export class My000435Component {
  @Input() parentName = '';
  myName = 'My000435Component';
}
