// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000438',
  templateUrl: './my.000438.component.html'
})
export class My000438Component {
  @Input() parentName = '';
  myName = 'My000438Component';
}
