// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000503',
  templateUrl: './my.000503.component.html'
})
export class My000503Component {
  @Input() parentName = '';
  myName = 'My000503Component';
}
