// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000143Component } from './my.000143.component';
import { My000144Component } from './my.000144.component';
import { My000145Component } from './my.000145.component';
import { My000146Component } from './my.000146.component';
import { My000147Component } from './my.000147.component';
import { My000148Component } from './my.000148.component';

@NgModule({
  declarations: [
    My000143Component,
    My000144Component,
    My000145Component,
    My000146Component,
    My000147Component,
    My000148Component,
  ],
  imports: [CommonModule],
  exports: [
    My000143Component,
  ]
})
export class Module000023 { }
