// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000144',
  templateUrl: './my.000144.component.html'
})
export class My000144Component {
  @Input() parentName = '';
  myName = 'My000144Component';
}
