// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000819Component } from './my.000819.component';
import { My000820Component } from './my.000820.component';
import { My000821Component } from './my.000821.component';
import { My000822Component } from './my.000822.component';
import { My000823Component } from './my.000823.component';
import { My000824Component } from './my.000824.component';

@NgModule({
  declarations: [
    My000819Component,
    My000820Component,
    My000821Component,
    My000822Component,
    My000823Component,
    My000824Component,
  ],
  imports: [CommonModule],
  exports: [
    My000819Component,
  ]
})
export class Module000119 { }
