// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000964',
  templateUrl: './my.000964.component.html'
})
export class My000964Component {
  @Input() parentName = '';
  myName = 'My000964Component';
}
