// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001503',
  templateUrl: './my.001503.component.html'
})
export class My001503Component {
  @Input() parentName = '';
  myName = 'My001503Component';
}
