// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001510',
  templateUrl: './my.001510.component.html'
})
export class My001510Component {
  @Input() parentName = '';
  myName = 'My001510Component';
}
