// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001509',
  templateUrl: './my.001509.component.html'
})
export class My001509Component {
  @Input() parentName = '';
  myName = 'My001509Component';
}
