// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001505',
  templateUrl: './my.001505.component.html'
})
export class My001505Component {
  @Input() parentName = '';
  myName = 'My001505Component';
}
