// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001504',
  templateUrl: './my.001504.component.html'
})
export class My001504Component {
  @Input() parentName = '';
  myName = 'My001504Component';
}
