// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001508',
  templateUrl: './my.001508.component.html'
})
export class My001508Component {
  @Input() parentName = '';
  myName = 'My001508Component';
}
