// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001506',
  templateUrl: './my.001506.component.html'
})
export class My001506Component {
  @Input() parentName = '';
  myName = 'My001506Component';
}
