// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000084Component } from './my.000084.component';
import { My000085Component } from './my.000085.component';
import { My000086Component } from './my.000086.component';
import { My000087Component } from './my.000087.component';
import { My000088Component } from './my.000088.component';
import { My000089Component } from './my.000089.component';
import { My000090Component } from './my.000090.component';

@NgModule({
  declarations: [
    My000084Component,
    My000085Component,
    My000086Component,
    My000087Component,
    My000088Component,
    My000089Component,
    My000090Component,
  ],
  imports: [CommonModule],
  exports: [
    My000084Component,
  ]
})
export class Module000012 { }
