// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000077Component } from './my.000077.component';
import { My000078Component } from './my.000078.component';
import { My000079Component } from './my.000079.component';
import { My000080Component } from './my.000080.component';
import { My000081Component } from './my.000081.component';
import { My000082Component } from './my.000082.component';

@NgModule({
  declarations: [
    My000077Component,
    My000078Component,
    My000079Component,
    My000080Component,
    My000081Component,
    My000082Component,
  ],
  imports: [CommonModule],
  exports: [
    My000077Component,
  ]
})
export class Module000012 { }
