// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000086',
  templateUrl: './my.000086.component.html'
})
export class My000086Component {
  @Input() parentName = '';
  myName = 'My000086Component';
}
