// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001371',
  templateUrl: './my.001371.component.html'
})
export class My001371Component {
  @Input() parentName = '';
  myName = 'My001371Component';
}
