// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001373',
  templateUrl: './my.001373.component.html'
})
export class My001373Component {
  @Input() parentName = '';
  myName = 'My001373Component';
}
