// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001037Component } from './my.001037.component';
import { My001038Component } from './my.001038.component';
import { My001039Component } from './my.001039.component';
import { My001040Component } from './my.001040.component';
import { My001041Component } from './my.001041.component';
import { My001042Component } from './my.001042.component';

@NgModule({
  declarations: [
    My001037Component,
    My001038Component,
    My001039Component,
    My001040Component,
    My001041Component,
    My001042Component,
  ],
  imports: [CommonModule],
  exports: [
    My001037Component,
  ]
})
export class Module000172 { }
