// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001390',
  templateUrl: './my.001390.component.html'
})
export class My001390Component {
  @Input() parentName = '';
  myName = 'My001390Component';
}
