// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001389',
  templateUrl: './my.001389.component.html'
})
export class My001389Component {
  @Input() parentName = '';
  myName = 'My001389Component';
}
