// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001384',
  templateUrl: './my.001384.component.html'
})
export class My001384Component {
  @Input() parentName = '';
  myName = 'My001384Component';
}
