// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000356',
  templateUrl: './my.000356.component.html'
})
export class My000356Component {
  @Input() parentName = '';
  myName = 'My000356Component';
}
