// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000035Component } from './my.000035.component';
import { My000036Component } from './my.000036.component';
import { My000037Component } from './my.000037.component';
import { My000038Component } from './my.000038.component';
import { My000039Component } from './my.000039.component';
import { My000040Component } from './my.000040.component';
import { My000041Component } from './my.000041.component';

@NgModule({
  declarations: [
    My000035Component,
    My000036Component,
    My000037Component,
    My000038Component,
    My000039Component,
    My000040Component,
    My000041Component,
  ],
  imports: [CommonModule],
  exports: [
    My000035Component,
  ]
})
export class Module000005 { }
