// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000039',
  templateUrl: './my.000039.component.html'
})
export class My000039Component {
  @Input() parentName = '';
  myName = 'My000039Component';
}
