// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000725Component } from './my.000725.component';
import { My000726Component } from './my.000726.component';
import { My000727Component } from './my.000727.component';
import { My000728Component } from './my.000728.component';
import { My000729Component } from './my.000729.component';
import { My000730Component } from './my.000730.component';

@NgModule({
  declarations: [
    My000725Component,
    My000726Component,
    My000727Component,
    My000728Component,
    My000729Component,
    My000730Component,
  ],
  imports: [CommonModule],
  exports: [
    My000725Component,
  ]
})
export class Module000120 { }
