// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000825Component } from './my.000825.component';
import { My000826Component } from './my.000826.component';
import { My000827Component } from './my.000827.component';
import { My000828Component } from './my.000828.component';
import { My000829Component } from './my.000829.component';
import { My000830Component } from './my.000830.component';

@NgModule({
  declarations: [
    My000825Component,
    My000826Component,
    My000827Component,
    My000828Component,
    My000829Component,
    My000830Component,
  ],
  imports: [CommonModule],
  exports: [
    My000825Component,
  ]
})
export class Module000120 { }
