// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000971',
  templateUrl: './my.000971.component.html'
})
export class My000971Component {
  @Input() parentName = '';
  myName = 'My000971Component';
}
