// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001471Component } from './my.001471.component';
import { My001472Component } from './my.001472.component';
import { My001473Component } from './my.001473.component';
import { My001474Component } from './my.001474.component';
import { My001475Component } from './my.001475.component';
import { My001476Component } from './my.001476.component';
import { My001477Component } from './my.001477.component';
import { My001478Component } from './my.001478.component';

@NgModule({
  declarations: [
    My001471Component,
    My001472Component,
    My001473Component,
    My001474Component,
    My001475Component,
    My001476Component,
    My001477Component,
    My001478Component,
  ],
  imports: [CommonModule],
  exports: [
    My001471Component,
  ]
})
export class Module000183 { }
