// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001108',
  templateUrl: './my.001108.component.html'
})
export class My001108Component {
  @Input() parentName = '';
  myName = 'My001108Component';
}
