// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001475',
  templateUrl: './my.001475.component.html'
})
export class My001475Component {
  @Input() parentName = '';
  myName = 'My001475Component';
}
