// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001471',
  templateUrl: './my.001471.component.html'
})
export class My001471Component {
  @Input() parentName = '';
  myName = 'My001471Component';
}
