// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001377',
  templateUrl: './my.001377.component.html'
})
export class My001377Component {
  @Input() parentName = '';
  myName = 'My001377Component';
}
