// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001031',
  templateUrl: './my.001031.component.html'
})
export class My001031Component {
  @Input() parentName = '';
  myName = 'My001031Component';
}
