// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001380',
  templateUrl: './my.001380.component.html'
})
export class My001380Component {
  @Input() parentName = '';
  myName = 'My001380Component';
}
