// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001375',
  templateUrl: './my.001375.component.html'
})
export class My001375Component {
  @Input() parentName = '';
  myName = 'My001375Component';
}
