// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001695Component } from './my.001695.component';
import { My001696Component } from './my.001696.component';
import { My001697Component } from './my.001697.component';
import { My001698Component } from './my.001698.component';
import { My001699Component } from './my.001699.component';
import { My001700Component } from './my.001700.component';
import { My001701Component } from './my.001701.component';
import { My001702Component } from './my.001702.component';

@NgModule({
  declarations: [
    My001695Component,
    My001696Component,
    My001697Component,
    My001698Component,
    My001699Component,
    My001700Component,
    My001701Component,
    My001702Component,
  ],
  imports: [CommonModule],
  exports: [
    My001695Component,
  ]
})
export class Module000211 { }
