// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001696',
  templateUrl: './my.001696.component.html'
})
export class My001696Component {
  @Input() parentName = '';
  myName = 'My001696Component';
}
