// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001274',
  templateUrl: './my.001274.component.html'
})
export class My001274Component {
  @Input() parentName = '';
  myName = 'My001274Component';
}
