// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001701',
  templateUrl: './my.001701.component.html'
})
export class My001701Component {
  @Input() parentName = '';
  myName = 'My001701Component';
}
