// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001699',
  templateUrl: './my.001699.component.html'
})
export class My001699Component {
  @Input() parentName = '';
  myName = 'My001699Component';
}
