// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001697',
  templateUrl: './my.001697.component.html'
})
export class My001697Component {
  @Input() parentName = '';
  myName = 'My001697Component';
}
