// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001698',
  templateUrl: './my.001698.component.html'
})
export class My001698Component {
  @Input() parentName = '';
  myName = 'My001698Component';
}
