// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000018Component } from './my.000018.component';
import { My000019Component } from './my.000019.component';
import { My000020Component } from './my.000020.component';
import { My000021Component } from './my.000021.component';
import { My000022Component } from './my.000022.component';
import { My000023Component } from './my.000023.component';
import { My000024Component } from './my.000024.component';
import { My000025Component } from './my.000025.component';
import { My000026Component } from './my.000026.component';

@NgModule({
  declarations: [
    My000018Component,
    My000019Component,
    My000020Component,
    My000021Component,
    My000022Component,
    My000023Component,
    My000024Component,
    My000025Component,
    My000026Component,
  ],
  imports: [CommonModule],
  exports: [
    My000018Component,
  ]
})
export class Module000002 { }
