// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000014Component } from './my.000014.component';
import { My000015Component } from './my.000015.component';
import { My000016Component } from './my.000016.component';
import { My000017Component } from './my.000017.component';
import { My000018Component } from './my.000018.component';
import { My000019Component } from './my.000019.component';
import { My000020Component } from './my.000020.component';

@NgModule({
  declarations: [
    My000014Component,
    My000015Component,
    My000016Component,
    My000017Component,
    My000018Component,
    My000019Component,
    My000020Component,
  ],
  imports: [CommonModule],
  exports: [
    My000014Component,
  ]
})
export class Module000002 { }
