// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000019',
  templateUrl: './my.000019.component.html'
})
export class My000019Component {
  @Input() parentName = '';
  myName = 'My000019Component';
}
