// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001442',
  templateUrl: './my.001442.component.html'
})
export class My001442Component {
  @Input() parentName = '';
  myName = 'My001442Component';
}
