// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001444',
  templateUrl: './my.001444.component.html'
})
export class My001444Component {
  @Input() parentName = '';
  myName = 'My001444Component';
}
