// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001427Component } from './my.001427.component';
import { My001428Component } from './my.001428.component';
import { My001429Component } from './my.001429.component';
import { My001430Component } from './my.001430.component';
import { My001431Component } from './my.001431.component';
import { My001432Component } from './my.001432.component';

@NgModule({
  declarations: [
    My001427Component,
    My001428Component,
    My001429Component,
    My001430Component,
    My001431Component,
    My001432Component,
  ],
  imports: [CommonModule],
  exports: [
    My001427Component,
  ]
})
export class Module000237 { }
