// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001905',
  templateUrl: './my.001905.component.html'
})
export class My001905Component {
  @Input() parentName = '';
  myName = 'My001905Component';
}
