// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001908',
  templateUrl: './my.001908.component.html'
})
export class My001908Component {
  @Input() parentName = '';
  myName = 'My001908Component';
}
