// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001903',
  templateUrl: './my.001903.component.html'
})
export class My001903Component {
  @Input() parentName = '';
  myName = 'My001903Component';
}
