// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001909',
  templateUrl: './my.001909.component.html'
})
export class My001909Component {
  @Input() parentName = '';
  myName = 'My001909Component';
}
