// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001429',
  templateUrl: './my.001429.component.html'
})
export class My001429Component {
  @Input() parentName = '';
  myName = 'My001429Component';
}
