// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001907',
  templateUrl: './my.001907.component.html'
})
export class My001907Component {
  @Input() parentName = '';
  myName = 'My001907Component';
}
