// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001119Component } from './my.001119.component';
import { My001120Component } from './my.001120.component';
import { My001121Component } from './my.001121.component';
import { My001122Component } from './my.001122.component';
import { My001123Component } from './my.001123.component';
import { My001124Component } from './my.001124.component';
import { My001125Component } from './my.001125.component';
import { My001126Component } from './my.001126.component';

@NgModule({
  declarations: [
    My001119Component,
    My001120Component,
    My001121Component,
    My001122Component,
    My001123Component,
    My001124Component,
    My001125Component,
    My001126Component,
  ],
  imports: [CommonModule],
  exports: [
    My001119Component,
  ]
})
export class Module000139 { }
