// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001125',
  templateUrl: './my.001125.component.html'
})
export class My001125Component {
  @Input() parentName = '';
  myName = 'My001125Component';
}
