// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000545Component } from './my.000545.component';
import { My000546Component } from './my.000546.component';
import { My000547Component } from './my.000547.component';
import { My000548Component } from './my.000548.component';
import { My000549Component } from './my.000549.component';
import { My000550Component } from './my.000550.component';

@NgModule({
  declarations: [
    My000545Component,
    My000546Component,
    My000547Component,
    My000548Component,
    My000549Component,
    My000550Component,
  ],
  imports: [CommonModule],
  exports: [
    My000545Component,
  ]
})
export class Module000090 { }
