// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000759Component } from './my.000759.component';
import { My000760Component } from './my.000760.component';
import { My000761Component } from './my.000761.component';
import { My000762Component } from './my.000762.component';
import { My000763Component } from './my.000763.component';
import { My000764Component } from './my.000764.component';

@NgModule({
  declarations: [
    My000759Component,
    My000760Component,
    My000761Component,
    My000762Component,
    My000763Component,
    My000764Component,
  ],
  imports: [CommonModule],
  exports: [
    My000759Component,
  ]
})
export class Module000109 { }
