// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000884',
  templateUrl: './my.000884.component.html'
})
export class My000884Component {
  @Input() parentName = '';
  myName = 'My000884Component';
}
