// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001935Component } from './my.001935.component';
import { My001936Component } from './my.001936.component';
import { My001937Component } from './my.001937.component';
import { My001938Component } from './my.001938.component';
import { My001939Component } from './my.001939.component';
import { My001940Component } from './my.001940.component';
import { My001941Component } from './my.001941.component';
import { My001942Component } from './my.001942.component';

@NgModule({
  declarations: [
    My001935Component,
    My001936Component,
    My001937Component,
    My001938Component,
    My001939Component,
    My001940Component,
    My001941Component,
    My001942Component,
  ],
  imports: [CommonModule],
  exports: [
    My001935Component,
  ]
})
export class Module000241 { }
