// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001451Component } from './my.001451.component';
import { My001452Component } from './my.001452.component';
import { My001453Component } from './my.001453.component';
import { My001454Component } from './my.001454.component';
import { My001455Component } from './my.001455.component';
import { My001456Component } from './my.001456.component';

@NgModule({
  declarations: [
    My001451Component,
    My001452Component,
    My001453Component,
    My001454Component,
    My001455Component,
    My001456Component,
  ],
  imports: [CommonModule],
  exports: [
    My001451Component,
  ]
})
export class Module000241 { }
