// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001455',
  templateUrl: './my.001455.component.html'
})
export class My001455Component {
  @Input() parentName = '';
  myName = 'My001455Component';
}
