// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001942',
  templateUrl: './my.001942.component.html'
})
export class My001942Component {
  @Input() parentName = '';
  myName = 'My001942Component';
}
