// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001453',
  templateUrl: './my.001453.component.html'
})
export class My001453Component {
  @Input() parentName = '';
  myName = 'My001453Component';
}
