// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001940',
  templateUrl: './my.001940.component.html'
})
export class My001940Component {
  @Input() parentName = '';
  myName = 'My001940Component';
}
