// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001937',
  templateUrl: './my.001937.component.html'
})
export class My001937Component {
  @Input() parentName = '';
  myName = 'My001937Component';
}
