// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001935',
  templateUrl: './my.001935.component.html'
})
export class My001935Component {
  @Input() parentName = '';
  myName = 'My001935Component';
}
