// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001939',
  templateUrl: './my.001939.component.html'
})
export class My001939Component {
  @Input() parentName = '';
  myName = 'My001939Component';
}
