// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001097Component } from './my.001097.component';
import { My001098Component } from './my.001098.component';
import { My001099Component } from './my.001099.component';
import { My001100Component } from './my.001100.component';
import { My001101Component } from './my.001101.component';
import { My001102Component } from './my.001102.component';

@NgModule({
  declarations: [
    My001097Component,
    My001098Component,
    My001099Component,
    My001100Component,
    My001101Component,
    My001102Component,
  ],
  imports: [CommonModule],
  exports: [
    My001097Component,
  ]
})
export class Module000182 { }
