// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001464',
  templateUrl: './my.001464.component.html'
})
export class My001464Component {
  @Input() parentName = '';
  myName = 'My001464Component';
}
