// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001465',
  templateUrl: './my.001465.component.html'
})
export class My001465Component {
  @Input() parentName = '';
  myName = 'My001465Component';
}
