// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001470',
  templateUrl: './my.001470.component.html'
})
export class My001470Component {
  @Input() parentName = '';
  myName = 'My001470Component';
}
