// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000033',
  templateUrl: './my.000033.component.html'
})
export class My000033Component {
  @Input() parentName = '';
  myName = 'My000033Component';
}
