// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000653Component } from './my.000653.component';
import { My000654Component } from './my.000654.component';
import { My000655Component } from './my.000655.component';
import { My000656Component } from './my.000656.component';
import { My000657Component } from './my.000657.component';
import { My000658Component } from './my.000658.component';

@NgModule({
  declarations: [
    My000653Component,
    My000654Component,
    My000655Component,
    My000656Component,
    My000657Component,
    My000658Component,
  ],
  imports: [CommonModule],
  exports: [
    My000653Component,
  ]
})
export class Module000108 { }
