// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000877',
  templateUrl: './my.000877.component.html'
})
export class My000877Component {
  @Input() parentName = '';
  myName = 'My000877Component';
}
