// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000756',
  templateUrl: './my.000756.component.html'
})
export class My000756Component {
  @Input() parentName = '';
  myName = 'My000756Component';
}
