// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000689',
  templateUrl: './my.000689.component.html'
})
export class My000689Component {
  @Input() parentName = '';
  myName = 'My000689Component';
}
