// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000000Component } from './my.000000.component';
import { My000001Component } from './my.000001.component';
import { My000002Component } from './my.000002.component';
import { My000003Component } from './my.000003.component';
import { My000004Component } from './my.000004.component';
import { My000005Component } from './my.000005.component';
import { My000006Component } from './my.000006.component';

@NgModule({
  declarations: [
    My000000Component,
    My000001Component,
    My000002Component,
    My000003Component,
    My000004Component,
    My000005Component,
    My000006Component,
  ],
  imports: [CommonModule],
  exports: [
    My000000Component,
  ]
})
export class Module000000 { }
