// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000000',
  templateUrl: './my.000000.component.html'
})
export class My000000Component {
  @Input() parentName = '';
  myName = 'My000000Component';
}
