// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000007',
  templateUrl: './my.000007.component.html'
})
export class My000007Component {
  @Input() parentName = '';
  myName = 'My000007Component';
}
