// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000425Component } from './my.000425.component';
import { My000426Component } from './my.000426.component';
import { My000427Component } from './my.000427.component';
import { My000428Component } from './my.000428.component';
import { My000429Component } from './my.000429.component';
import { My000430Component } from './my.000430.component';

@NgModule({
  declarations: [
    My000425Component,
    My000426Component,
    My000427Component,
    My000428Component,
    My000429Component,
    My000430Component,
  ],
  imports: [CommonModule],
  exports: [
    My000425Component,
  ]
})
export class Module000070 { }
