// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000490Component } from './my.000490.component';
import { My000491Component } from './my.000491.component';
import { My000492Component } from './my.000492.component';
import { My000493Component } from './my.000493.component';
import { My000494Component } from './my.000494.component';
import { My000495Component } from './my.000495.component';
import { My000496Component } from './my.000496.component';

@NgModule({
  declarations: [
    My000490Component,
    My000491Component,
    My000492Component,
    My000493Component,
    My000494Component,
    My000495Component,
    My000496Component,
  ],
  imports: [CommonModule],
  exports: [
    My000490Component,
  ]
})
export class Module000070 { }
