// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000479Component } from './my.000479.component';
import { My000480Component } from './my.000480.component';
import { My000481Component } from './my.000481.component';
import { My000482Component } from './my.000482.component';
import { My000483Component } from './my.000483.component';
import { My000484Component } from './my.000484.component';

@NgModule({
  declarations: [
    My000479Component,
    My000480Component,
    My000481Component,
    My000482Component,
    My000483Component,
    My000484Component,
  ],
  imports: [CommonModule],
  exports: [
    My000479Component,
  ]
})
export class Module000079 { }
