// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001495Component } from './my.001495.component';
import { My001496Component } from './my.001496.component';
import { My001497Component } from './my.001497.component';
import { My001498Component } from './my.001498.component';
import { My001499Component } from './my.001499.component';
import { My001500Component } from './my.001500.component';
import { My001501Component } from './my.001501.component';
import { My001502Component } from './my.001502.component';

@NgModule({
  declarations: [
    My001495Component,
    My001496Component,
    My001497Component,
    My001498Component,
    My001499Component,
    My001500Component,
    My001501Component,
    My001502Component,
  ],
  imports: [CommonModule],
  exports: [
    My001495Component,
  ]
})
export class Module000186 { }
