// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001122',
  templateUrl: './my.001122.component.html'
})
export class My001122Component {
  @Input() parentName = '';
  myName = 'My001122Component';
}
