// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001499',
  templateUrl: './my.001499.component.html'
})
export class My001499Component {
  @Input() parentName = '';
  myName = 'My001499Component';
}
