// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001495',
  templateUrl: './my.001495.component.html'
})
export class My001495Component {
  @Input() parentName = '';
  myName = 'My001495Component';
}
