// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001415Component } from './my.001415.component';
import { My001416Component } from './my.001416.component';
import { My001417Component } from './my.001417.component';
import { My001418Component } from './my.001418.component';
import { My001419Component } from './my.001419.component';
import { My001420Component } from './my.001420.component';
import { My001421Component } from './my.001421.component';
import { My001422Component } from './my.001422.component';

@NgModule({
  declarations: [
    My001415Component,
    My001416Component,
    My001417Component,
    My001418Component,
    My001419Component,
    My001420Component,
    My001421Component,
    My001422Component,
  ],
  imports: [CommonModule],
  exports: [
    My001415Component,
  ]
})
export class Module000176 { }
