// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001418',
  templateUrl: './my.001418.component.html'
})
export class My001418Component {
  @Input() parentName = '';
  myName = 'My001418Component';
}
