// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001416',
  templateUrl: './my.001416.component.html'
})
export class My001416Component {
  @Input() parentName = '';
  myName = 'My001416Component';
}
