// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001063',
  templateUrl: './my.001063.component.html'
})
export class My001063Component {
  @Input() parentName = '';
  myName = 'My001063Component';
}
