// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001978',
  templateUrl: './my.001978.component.html'
})
export class My001978Component {
  @Input() parentName = '';
  myName = 'My001978Component';
}
