// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001980',
  templateUrl: './my.001980.component.html'
})
export class My001980Component {
  @Input() parentName = '';
  myName = 'My001980Component';
}
