// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001977',
  templateUrl: './my.001977.component.html'
})
export class My001977Component {
  @Input() parentName = '';
  myName = 'My001977Component';
}
