// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001982',
  templateUrl: './my.001982.component.html'
})
export class My001982Component {
  @Input() parentName = '';
  myName = 'My001982Component';
}
