// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001981',
  templateUrl: './my.001981.component.html'
})
export class My001981Component {
  @Input() parentName = '';
  myName = 'My001981Component';
}
