// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001979',
  templateUrl: './my.001979.component.html'
})
export class My001979Component {
  @Input() parentName = '';
  myName = 'My001979Component';
}
