// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000551Component } from './my.000551.component';
import { My000552Component } from './my.000552.component';
import { My000553Component } from './my.000553.component';
import { My000554Component } from './my.000554.component';
import { My000555Component } from './my.000555.component';
import { My000556Component } from './my.000556.component';

@NgModule({
  declarations: [
    My000551Component,
    My000552Component,
    My000553Component,
    My000554Component,
    My000555Component,
    My000556Component,
  ],
  imports: [CommonModule],
  exports: [
    My000551Component,
  ]
})
export class Module000091 { }
