// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000735Component } from './my.000735.component';
import { My000736Component } from './my.000736.component';
import { My000737Component } from './my.000737.component';
import { My000738Component } from './my.000738.component';
import { My000739Component } from './my.000739.component';
import { My000740Component } from './my.000740.component';
import { My000741Component } from './my.000741.component';
import { My000742Component } from './my.000742.component';

@NgModule({
  declarations: [
    My000735Component,
    My000736Component,
    My000737Component,
    My000738Component,
    My000739Component,
    My000740Component,
    My000741Component,
    My000742Component,
  ],
  imports: [CommonModule],
  exports: [
    My000735Component,
  ]
})
export class Module000091 { }
