// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000641',
  templateUrl: './my.000641.component.html'
})
export class My000641Component {
  @Input() parentName = '';
  myName = 'My000641Component';
}
