// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001320',
  templateUrl: './my.001320.component.html'
})
export class My001320Component {
  @Input() parentName = '';
  myName = 'My001320Component';
}
