// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001319',
  templateUrl: './my.001319.component.html'
})
export class My001319Component {
  @Input() parentName = '';
  myName = 'My001319Component';
}
