// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001323',
  templateUrl: './my.001323.component.html'
})
export class My001323Component {
  @Input() parentName = '';
  myName = 'My001323Component';
}
