// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001324',
  templateUrl: './my.001324.component.html'
})
export class My001324Component {
  @Input() parentName = '';
  myName = 'My001324Component';
}
