// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000107Component } from './my.000107.component';
import { My000108Component } from './my.000108.component';
import { My000109Component } from './my.000109.component';
import { My000110Component } from './my.000110.component';
import { My000111Component } from './my.000111.component';
import { My000112Component } from './my.000112.component';

@NgModule({
  declarations: [
    My000107Component,
    My000108Component,
    My000109Component,
    My000110Component,
    My000111Component,
    My000112Component,
  ],
  imports: [CommonModule],
  exports: [
    My000107Component,
  ]
})
export class Module000017 { }
