// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000121',
  templateUrl: './my.000121.component.html'
})
export class My000121Component {
  @Input() parentName = '';
  myName = 'My000121Component';
}
