// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000110',
  templateUrl: './my.000110.component.html'
})
export class My000110Component {
  @Input() parentName = '';
  myName = 'My000110Component';
}
