// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000124',
  templateUrl: './my.000124.component.html'
})
export class My000124Component {
  @Input() parentName = '';
  myName = 'My000124Component';
}
