// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000567Component } from './my.000567.component';
import { My000568Component } from './my.000568.component';
import { My000569Component } from './my.000569.component';
import { My000570Component } from './my.000570.component';
import { My000571Component } from './my.000571.component';
import { My000572Component } from './my.000572.component';
import { My000573Component } from './my.000573.component';

@NgModule({
  declarations: [
    My000567Component,
    My000568Component,
    My000569Component,
    My000570Component,
    My000571Component,
    My000572Component,
    My000573Component,
  ],
  imports: [CommonModule],
  exports: [
    My000567Component,
  ]
})
export class Module000081 { }
