// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000795Component } from './my.000795.component';
import { My000796Component } from './my.000796.component';
import { My000797Component } from './my.000797.component';
import { My000798Component } from './my.000798.component';
import { My000799Component } from './my.000799.component';
import { My000800Component } from './my.000800.component';

@NgModule({
  declarations: [
    My000795Component,
    My000796Component,
    My000797Component,
    My000798Component,
    My000799Component,
    My000800Component,
  ],
  imports: [CommonModule],
  exports: [
    My000795Component,
  ]
})
export class Module000115 { }
