// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000927Component } from './my.000927.component';
import { My000928Component } from './my.000928.component';
import { My000929Component } from './my.000929.component';
import { My000930Component } from './my.000930.component';
import { My000931Component } from './my.000931.component';
import { My000932Component } from './my.000932.component';
import { My000933Component } from './my.000933.component';
import { My000934Component } from './my.000934.component';

@NgModule({
  declarations: [
    My000927Component,
    My000928Component,
    My000929Component,
    My000930Component,
    My000931Component,
    My000932Component,
    My000933Component,
    My000934Component,
  ],
  imports: [CommonModule],
  exports: [
    My000927Component,
  ]
})
export class Module000115 { }
