// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000075',
  templateUrl: './my.000075.component.html'
})
export class My000075Component {
  @Input() parentName = '';
  myName = 'My000075Component';
}
