// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000151Component } from './my.000151.component';
import { My000152Component } from './my.000152.component';
import { My000153Component } from './my.000153.component';
import { My000154Component } from './my.000154.component';
import { My000155Component } from './my.000155.component';
import { My000156Component } from './my.000156.component';
import { My000157Component } from './my.000157.component';
import { My000158Component } from './my.000158.component';

@NgModule({
  declarations: [
    My000151Component,
    My000152Component,
    My000153Component,
    My000154Component,
    My000155Component,
    My000156Component,
    My000157Component,
    My000158Component,
  ],
  imports: [CommonModule],
  exports: [
    My000151Component,
  ]
})
export class Module000018 { }
