// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000132',
  templateUrl: './my.000132.component.html'
})
export class My000132Component {
  @Input() parentName = '';
  myName = 'My000132Component';
}
