// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000887Component } from './my.000887.component';
import { My000888Component } from './my.000888.component';
import { My000889Component } from './my.000889.component';
import { My000890Component } from './my.000890.component';
import { My000891Component } from './my.000891.component';
import { My000892Component } from './my.000892.component';

@NgModule({
  declarations: [
    My000887Component,
    My000888Component,
    My000889Component,
    My000890Component,
    My000891Component,
    My000892Component,
  ],
  imports: [CommonModule],
  exports: [
    My000887Component,
  ]
})
export class Module000147 { }
