// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000987Component } from './my.000987.component';
import { My000988Component } from './my.000988.component';
import { My000989Component } from './my.000989.component';
import { My000990Component } from './my.000990.component';
import { My000991Component } from './my.000991.component';
import { My000992Component } from './my.000992.component';

@NgModule({
  declarations: [
    My000987Component,
    My000988Component,
    My000989Component,
    My000990Component,
    My000991Component,
    My000992Component,
  ],
  imports: [CommonModule],
  exports: [
    My000987Component,
  ]
})
export class Module000147 { }
