// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000183Component } from './my.000183.component';
import { My000184Component } from './my.000184.component';
import { My000185Component } from './my.000185.component';
import { My000186Component } from './my.000186.component';
import { My000187Component } from './my.000187.component';
import { My000188Component } from './my.000188.component';
import { My000189Component } from './my.000189.component';
import { My000190Component } from './my.000190.component';

@NgModule({
  declarations: [
    My000183Component,
    My000184Component,
    My000185Component,
    My000186Component,
    My000187Component,
    My000188Component,
    My000189Component,
    My000190Component,
  ],
  imports: [CommonModule],
  exports: [
    My000183Component,
  ]
})
export class Module000022 { }
