// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000137Component } from './my.000137.component';
import { My000138Component } from './my.000138.component';
import { My000139Component } from './my.000139.component';
import { My000140Component } from './my.000140.component';
import { My000141Component } from './my.000141.component';
import { My000142Component } from './my.000142.component';

@NgModule({
  declarations: [
    My000137Component,
    My000138Component,
    My000139Component,
    My000140Component,
    My000141Component,
    My000142Component,
  ],
  imports: [CommonModule],
  exports: [
    My000137Component,
  ]
})
export class Module000022 { }
