// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000971Component } from './my.000971.component';
import { My000972Component } from './my.000972.component';
import { My000973Component } from './my.000973.component';
import { My000974Component } from './my.000974.component';
import { My000975Component } from './my.000975.component';
import { My000976Component } from './my.000976.component';

@NgModule({
  declarations: [
    My000971Component,
    My000972Component,
    My000973Component,
    My000974Component,
    My000975Component,
    My000976Component,
  ],
  imports: [CommonModule],
  exports: [
    My000971Component,
  ]
})
export class Module000161 { }
