// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001299',
  templateUrl: './my.001299.component.html'
})
export class My001299Component {
  @Input() parentName = '';
  myName = 'My001299Component';
}
