// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001295',
  templateUrl: './my.001295.component.html'
})
export class My001295Component {
  @Input() parentName = '';
  myName = 'My001295Component';
}
