// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001298',
  templateUrl: './my.001298.component.html'
})
export class My001298Component {
  @Input() parentName = '';
  myName = 'My001298Component';
}
