// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001302',
  templateUrl: './my.001302.component.html'
})
export class My001302Component {
  @Input() parentName = '';
  myName = 'My001302Component';
}
