// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000523',
  templateUrl: './my.000523.component.html'
})
export class My000523Component {
  @Input() parentName = '';
  myName = 'My000523Component';
}
