// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000266Component } from './my.000266.component';
import { My000267Component } from './my.000267.component';
import { My000268Component } from './my.000268.component';
import { My000269Component } from './my.000269.component';
import { My000270Component } from './my.000270.component';
import { My000271Component } from './my.000271.component';
import { My000272Component } from './my.000272.component';

@NgModule({
  declarations: [
    My000266Component,
    My000267Component,
    My000268Component,
    My000269Component,
    My000270Component,
    My000271Component,
    My000272Component,
  ],
  imports: [CommonModule],
  exports: [
    My000266Component,
  ]
})
export class Module000038 { }
