// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000605Component } from './my.000605.component';
import { My000606Component } from './my.000606.component';
import { My000607Component } from './my.000607.component';
import { My000608Component } from './my.000608.component';
import { My000609Component } from './my.000609.component';
import { My000610Component } from './my.000610.component';

@NgModule({
  declarations: [
    My000605Component,
    My000606Component,
    My000607Component,
    My000608Component,
    My000609Component,
    My000610Component,
  ],
  imports: [CommonModule],
  exports: [
    My000605Component,
  ]
})
export class Module000100 { }
