// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000607',
  templateUrl: './my.000607.component.html'
})
export class My000607Component {
  @Input() parentName = '';
  myName = 'My000607Component';
}
