// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000599',
  templateUrl: './my.000599.component.html'
})
export class My000599Component {
  @Input() parentName = '';
  myName = 'My000599Component';
}
