// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001091Component } from './my.001091.component';
import { My001092Component } from './my.001092.component';
import { My001093Component } from './my.001093.component';
import { My001094Component } from './my.001094.component';
import { My001095Component } from './my.001095.component';
import { My001096Component } from './my.001096.component';

@NgModule({
  declarations: [
    My001091Component,
    My001092Component,
    My001093Component,
    My001094Component,
    My001095Component,
    My001096Component,
  ],
  imports: [CommonModule],
  exports: [
    My001091Component,
  ]
})
export class Module000181 { }
