// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000801Component } from './my.000801.component';
import { My000802Component } from './my.000802.component';
import { My000803Component } from './my.000803.component';
import { My000804Component } from './my.000804.component';
import { My000805Component } from './my.000805.component';
import { My000806Component } from './my.000806.component';

@NgModule({
  declarations: [
    My000801Component,
    My000802Component,
    My000803Component,
    My000804Component,
    My000805Component,
    My000806Component,
  ],
  imports: [CommonModule],
  exports: [
    My000801Component,
  ]
})
export class Module000116 { }
