// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000843Component } from './my.000843.component';
import { My000844Component } from './my.000844.component';
import { My000845Component } from './my.000845.component';
import { My000846Component } from './my.000846.component';
import { My000847Component } from './my.000847.component';
import { My000848Component } from './my.000848.component';

@NgModule({
  declarations: [
    My000843Component,
    My000844Component,
    My000845Component,
    My000846Component,
    My000847Component,
    My000848Component,
  ],
  imports: [CommonModule],
  exports: [
    My000843Component,
  ]
})
export class Module000123 { }
