// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000744',
  templateUrl: './my.000744.component.html'
})
export class My000744Component {
  @Input() parentName = '';
  myName = 'My000744Component';
}
