// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000743',
  templateUrl: './my.000743.component.html'
})
export class My000743Component {
  @Input() parentName = '';
  myName = 'My000743Component';
}
