// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000069',
  templateUrl: './my.000069.component.html'
})
export class My000069Component {
  @Input() parentName = '';
  myName = 'My000069Component';
}
