// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001015Component } from './my.001015.component';
import { My001016Component } from './my.001016.component';
import { My001017Component } from './my.001017.component';
import { My001018Component } from './my.001018.component';
import { My001019Component } from './my.001019.component';
import { My001020Component } from './my.001020.component';
import { My001021Component } from './my.001021.component';
import { My001022Component } from './my.001022.component';

@NgModule({
  declarations: [
    My001015Component,
    My001016Component,
    My001017Component,
    My001018Component,
    My001019Component,
    My001020Component,
    My001021Component,
    My001022Component,
  ],
  imports: [CommonModule],
  exports: [
    My001015Component,
  ]
})
export class Module000126 { }
