// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001021',
  templateUrl: './my.001021.component.html'
})
export class My001021Component {
  @Input() parentName = '';
  myName = 'My001021Component';
}
