// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001255Component } from './my.001255.component';
import { My001256Component } from './my.001256.component';
import { My001257Component } from './my.001257.component';
import { My001258Component } from './my.001258.component';
import { My001259Component } from './my.001259.component';
import { My001260Component } from './my.001260.component';
import { My001261Component } from './my.001261.component';
import { My001262Component } from './my.001262.component';

@NgModule({
  declarations: [
    My001255Component,
    My001256Component,
    My001257Component,
    My001258Component,
    My001259Component,
    My001260Component,
    My001261Component,
    My001262Component,
  ],
  imports: [CommonModule],
  exports: [
    My001255Component,
  ]
})
export class Module000156 { }
