// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001259',
  templateUrl: './my.001259.component.html'
})
export class My001259Component {
  @Input() parentName = '';
  myName = 'My001259Component';
}
