// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001260',
  templateUrl: './my.001260.component.html'
})
export class My001260Component {
  @Input() parentName = '';
  myName = 'My001260Component';
}
