// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001255',
  templateUrl: './my.001255.component.html'
})
export class My001255Component {
  @Input() parentName = '';
  myName = 'My001255Component';
}
