// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000532Component } from './my.000532.component';
import { My000533Component } from './my.000533.component';
import { My000534Component } from './my.000534.component';
import { My000535Component } from './my.000535.component';
import { My000536Component } from './my.000536.component';
import { My000537Component } from './my.000537.component';
import { My000538Component } from './my.000538.component';

@NgModule({
  declarations: [
    My000532Component,
    My000533Component,
    My000534Component,
    My000535Component,
    My000536Component,
    My000537Component,
    My000538Component,
  ],
  imports: [CommonModule],
  exports: [
    My000532Component,
  ]
})
export class Module000076 { }
