// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000461Component } from './my.000461.component';
import { My000462Component } from './my.000462.component';
import { My000463Component } from './my.000463.component';
import { My000464Component } from './my.000464.component';
import { My000465Component } from './my.000465.component';
import { My000466Component } from './my.000466.component';

@NgModule({
  declarations: [
    My000461Component,
    My000462Component,
    My000463Component,
    My000464Component,
    My000465Component,
    My000466Component,
  ],
  imports: [CommonModule],
  exports: [
    My000461Component,
  ]
})
export class Module000076 { }
