// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000462',
  templateUrl: './my.000462.component.html'
})
export class My000462Component {
  @Input() parentName = '';
  myName = 'My000462Component';
}
