// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001655Component } from './my.001655.component';
import { My001656Component } from './my.001656.component';
import { My001657Component } from './my.001657.component';
import { My001658Component } from './my.001658.component';
import { My001659Component } from './my.001659.component';
import { My001660Component } from './my.001660.component';
import { My001661Component } from './my.001661.component';
import { My001662Component } from './my.001662.component';

@NgModule({
  declarations: [
    My001655Component,
    My001656Component,
    My001657Component,
    My001658Component,
    My001659Component,
    My001660Component,
    My001661Component,
    My001662Component,
  ],
  imports: [CommonModule],
  exports: [
    My001655Component,
  ]
})
export class Module000206 { }
