// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001658',
  templateUrl: './my.001658.component.html'
})
export class My001658Component {
  @Input() parentName = '';
  myName = 'My001658Component';
}
