// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001660',
  templateUrl: './my.001660.component.html'
})
export class My001660Component {
  @Input() parentName = '';
  myName = 'My001660Component';
}
