// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001242',
  templateUrl: './my.001242.component.html'
})
export class My001242Component {
  @Input() parentName = '';
  myName = 'My001242Component';
}
