// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001655',
  templateUrl: './my.001655.component.html'
})
export class My001655Component {
  @Input() parentName = '';
  myName = 'My001655Component';
}
