// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001661',
  templateUrl: './my.001661.component.html'
})
export class My001661Component {
  @Input() parentName = '';
  myName = 'My001661Component';
}
