// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001656',
  templateUrl: './my.001656.component.html'
})
export class My001656Component {
  @Input() parentName = '';
  myName = 'My001656Component';
}
