// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001657',
  templateUrl: './my.001657.component.html'
})
export class My001657Component {
  @Input() parentName = '';
  myName = 'My001657Component';
}
