// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001799Component } from './my.001799.component';
import { My001800Component } from './my.001800.component';
import { My001801Component } from './my.001801.component';
import { My001802Component } from './my.001802.component';
import { My001803Component } from './my.001803.component';
import { My001804Component } from './my.001804.component';
import { My001805Component } from './my.001805.component';
import { My001806Component } from './my.001806.component';

@NgModule({
  declarations: [
    My001799Component,
    My001800Component,
    My001801Component,
    My001802Component,
    My001803Component,
    My001804Component,
    My001805Component,
    My001806Component,
  ],
  imports: [CommonModule],
  exports: [
    My001799Component,
  ]
})
export class Module000224 { }
