// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001799',
  templateUrl: './my.001799.component.html'
})
export class My001799Component {
  @Input() parentName = '';
  myName = 'My001799Component';
}
