// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001803',
  templateUrl: './my.001803.component.html'
})
export class My001803Component {
  @Input() parentName = '';
  myName = 'My001803Component';
}
