// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001802',
  templateUrl: './my.001802.component.html'
})
export class My001802Component {
  @Input() parentName = '';
  myName = 'My001802Component';
}
