// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001805',
  templateUrl: './my.001805.component.html'
})
export class My001805Component {
  @Input() parentName = '';
  myName = 'My001805Component';
}
