// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001351',
  templateUrl: './my.001351.component.html'
})
export class My001351Component {
  @Input() parentName = '';
  myName = 'My001351Component';
}
