// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001806',
  templateUrl: './my.001806.component.html'
})
export class My001806Component {
  @Input() parentName = '';
  myName = 'My001806Component';
}
