// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001800',
  templateUrl: './my.001800.component.html'
})
export class My001800Component {
  @Input() parentName = '';
  myName = 'My001800Component';
}
