// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001804',
  templateUrl: './my.001804.component.html'
})
export class My001804Component {
  @Input() parentName = '';
  myName = 'My001804Component';
}
