// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001801',
  templateUrl: './my.001801.component.html'
})
export class My001801Component {
  @Input() parentName = '';
  myName = 'My001801Component';
}
