// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000231Component } from './my.000231.component';
import { My000232Component } from './my.000232.component';
import { My000233Component } from './my.000233.component';
import { My000234Component } from './my.000234.component';
import { My000235Component } from './my.000235.component';
import { My000236Component } from './my.000236.component';
import { My000237Component } from './my.000237.component';

@NgModule({
  declarations: [
    My000231Component,
    My000232Component,
    My000233Component,
    My000234Component,
    My000235Component,
    My000236Component,
    My000237Component,
  ],
  imports: [CommonModule],
  exports: [
    My000231Component,
  ]
})
export class Module000033 { }
