// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000203',
  templateUrl: './my.000203.component.html'
})
export class My000203Component {
  @Input() parentName = '';
  myName = 'My000203Component';
}
