// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000602Component } from './my.000602.component';
import { My000603Component } from './my.000603.component';
import { My000604Component } from './my.000604.component';
import { My000605Component } from './my.000605.component';
import { My000606Component } from './my.000606.component';
import { My000607Component } from './my.000607.component';
import { My000608Component } from './my.000608.component';

@NgModule({
  declarations: [
    My000602Component,
    My000603Component,
    My000604Component,
    My000605Component,
    My000606Component,
    My000607Component,
    My000608Component,
  ],
  imports: [CommonModule],
  exports: [
    My000602Component,
  ]
})
export class Module000086 { }
