// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000521Component } from './my.000521.component';
import { My000522Component } from './my.000522.component';
import { My000523Component } from './my.000523.component';
import { My000524Component } from './my.000524.component';
import { My000525Component } from './my.000525.component';
import { My000526Component } from './my.000526.component';

@NgModule({
  declarations: [
    My000521Component,
    My000522Component,
    My000523Component,
    My000524Component,
    My000525Component,
    My000526Component,
  ],
  imports: [CommonModule],
  exports: [
    My000521Component,
  ]
})
export class Module000086 { }
