// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000602',
  templateUrl: './my.000602.component.html'
})
export class My000602Component {
  @Input() parentName = '';
  myName = 'My000602Component';
}
