// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000525',
  templateUrl: './my.000525.component.html'
})
export class My000525Component {
  @Input() parentName = '';
  myName = 'My000525Component';
}
