// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My000609Component } from './my.000609.component';
import { My000610Component } from './my.000610.component';
import { My000611Component } from './my.000611.component';
import { My000612Component } from './my.000612.component';
import { My000613Component } from './my.000613.component';
import { My000614Component } from './my.000614.component';
import { My000615Component } from './my.000615.component';

@NgModule({
  declarations: [
    My000609Component,
    My000610Component,
    My000611Component,
    My000612Component,
    My000613Component,
    My000614Component,
    My000615Component,
  ],
  imports: [CommonModule],
  exports: [
    My000609Component,
  ]
})
export class Module000087 { }
