// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-000759',
  templateUrl: './my.000759.component.html'
})
export class My000759Component {
  @Input() parentName = '';
  myName = 'My000759Component';
}
