// Code generated by angular-stress-test

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { My001815Component } from './my.001815.component';
import { My001816Component } from './my.001816.component';
import { My001817Component } from './my.001817.component';
import { My001818Component } from './my.001818.component';
import { My001819Component } from './my.001819.component';
import { My001820Component } from './my.001820.component';
import { My001821Component } from './my.001821.component';
import { My001822Component } from './my.001822.component';

@NgModule({
  declarations: [
    My001815Component,
    My001816Component,
    My001817Component,
    My001818Component,
    My001819Component,
    My001820Component,
    My001821Component,
    My001822Component,
  ],
  imports: [CommonModule],
  exports: [
    My001815Component,
  ]
})
export class Module000226 { }
