// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001364',
  templateUrl: './my.001364.component.html'
})
export class My001364Component {
  @Input() parentName = '';
  myName = 'My001364Component';
}
