// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001818',
  templateUrl: './my.001818.component.html'
})
export class My001818Component {
  @Input() parentName = '';
  myName = 'My001818Component';
}
