// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001815',
  templateUrl: './my.001815.component.html'
})
export class My001815Component {
  @Input() parentName = '';
  myName = 'My001815Component';
}
