// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001821',
  templateUrl: './my.001821.component.html'
})
export class My001821Component {
  @Input() parentName = '';
  myName = 'My001821Component';
}
