// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001822',
  templateUrl: './my.001822.component.html'
})
export class My001822Component {
  @Input() parentName = '';
  myName = 'My001822Component';
}
