// Code generated by angular-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-comp-001816',
  templateUrl: './my.001816.component.html'
})
export class My001816Component {
  @Input() parentName = '';
  myName = 'My001816Component';
}
